import { useNavigate } from "react-router-dom";
import { ArrowLeft, Shield } from "lucide-react";
import { BrandLockup } from "@/components/brand/BrandLogo";
import { SUPPORT_EMAIL, SUPPORT_MAILTO } from "@/config/contact";
import { isFeedbackIntelligenceClientEnabled, isFeedbackTextClientEnabled } from "@/lib/feedbackIntelligenceApi";
import { usePublicLanguage } from "@/contexts/PublicLanguageContext";
import { PublicLanguageSwitch } from "@/components/public/PublicLanguageSwitch";

const Privacy = () => {
  const { tr } = usePublicLanguage();
  const navigate = useNavigate();
  const feedbackEnabled = isFeedbackIntelligenceClientEnabled() && isFeedbackTextClientEnabled();
  const webAnalyticsEnabled = import.meta.env.VITE_WEB_ANALYTICS_ENABLED === "true";

  const goBack = () => {
    if (window.history.length > 1) {
      navigate(-1);
      return;
    }
    navigate("/settings", { replace: true });
  };

  return (
    <main className="min-h-screen bg-background text-foreground px-6 py-10">
      <div className="max-w-3xl mx-auto">
        <div className="mb-10 flex items-center justify-between gap-4">
          <button
            type="button"
            onClick={goBack}
            className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="w-4 h-4" />
            {tr("Zurück", "Back")}
          </button>
          <div className="flex items-center gap-3">
            <BrandLockup className="hidden sm:inline-flex" symbolSize={24} textClassName="text-sm" />
            <PublicLanguageSwitch />
          </div>
        </div>

        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
            <Shield className="w-5 h-5 text-primary" />
          </div>
          <p className="text-xs uppercase tracking-[0.2em] text-primary font-semibold">{tr("Datenschutz", "Privacy")}</p>
        </div>

        <h1 className="font-heading text-3xl md:text-4xl font-bold mb-4">{tr("RewirePerform Datenschutz", "RewirePerform Privacy Notice")}</h1>
        <p className="text-sm text-muted-foreground mb-8">
          {tr("Stand: 8. September 2026. Diese Seite erklärt, welche Daten RewirePerform erhebt, warum, auf welcher Rechtsgrundlage und was mit ihnen passiert — und was ausdrücklich nicht passiert.", "Last updated: 8 September 2026. This page explains what data RewirePerform collects, why, on what legal basis, what happens to it — and what explicitly does not happen.")}
        </p>

        <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Verantwortlicher", "Data controller")}</h2>
            <p className="text-foreground">{tr("Mahle Herzog, handelnd unter RewirePerform", "Mahle Herzog, trading as RewirePerform")}</p>
            <p className="mt-2">{tr("Postanschrift:", "Postal address:")}</p>
            <address className="not-italic">
              Wiefeldick 16<br />
              42699 Solingen<br />
              {tr("Deutschland", "Germany")}
            </address>
            <p className="mt-2">
              {tr("Datenschutzkontakt:", "Privacy contact:")} <a href={SUPPORT_MAILTO} className="text-primary hover:underline">{SUPPORT_EMAIL}</a>
            </p>
          </section>

          <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5">
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Die kurze Wahrheit zuerst", "The short version first")}</h2>
            <ul className="space-y-2">
              <li><span className="text-foreground">{tr("Deine Journale, privaten Reflexionen und sonstigen freien Antworten werden nicht gelesen, analysiert oder von einer KI verarbeitet.", "Your journals, private reflections and other free-text answers are not read, analyzed or processed by AI.")}</span> {tr("Sie liegen zugriffsgeschützt in deinem Konto, damit du sie später wieder sehen kannst.", "They are stored with access protection in your account so you can view them again later.")}</li>
              {feedbackEnabled ? (
                <li><span className="text-foreground">{tr("Feedback Intelligence ist freiwillig und klar getrennt.", "Feedback Intelligence is voluntary and clearly separate.")}</span> {tr("Für Tag 10, 24, 39 und 55 kannst du überspringbare Auswahlfragen beantworten. Verpasst du einen dieser Zeitpunkte, kann dir der älteste noch offene Zwischenstand beim nächsten späteren Login erneut angeboten werden. Du kannst ihn später erinnern lassen oder für diesen Zeitpunkt entscheiden, kein Feedback zu geben. Jarvis darf dafür nur pseudonymisierte Auswahlantworten und minimierte Aktivitätszahlen kurzzeitig im Arbeitsspeicher verarbeiten. Ausgegeben werden ausschließlich Gruppenzusammenfassungen pro Frage ab mindestens fünf unterschiedlichen Teilnehmenden; die pseudonymen Referenzen werden weder ausgegeben noch dauerhaft gespeichert. Freitexte erhält Jarvis nicht und die Daten werden nicht zum Trainieren eines KI-Modells verwendet. Einen klar als Produktfeedback markierten Kommentar verarbeitet RewirePerform nur nach deiner zusätzlichen ausdrücklichen Einwilligung; dein Nein hat keinen Nachteil.", "On days 10, 24, 39 and 55, you may answer optional multiple-choice questions. If you miss one of these points, the oldest still-open checkpoint may be offered again at your next later sign-in. You may ask to be reminded later or decide not to give feedback at that checkpoint. For this purpose, Jarvis may briefly process only pseudonymized multiple-choice answers and minimized activity counts in memory. Only group summaries per question involving at least five different participants are output; pseudonymous references are neither output nor stored permanently. Jarvis receives no free text, and the data is not used to train an AI model. RewirePerform processes a comment clearly marked as product feedback only with your separate explicit consent; saying no has no disadvantage.")}</li>
              ) : (
                <li><span className="text-foreground">{tr("Feedback Intelligence ist nicht Teil dieser V1.1-Auslieferung.", "Feedback Intelligence is not part of this V1.1 release.")}</span> {tr("In V1.1 werden keine Feedback-Checkpoints, keine freiwilligen Produktfeedback-Kommentare und keine hierfür vorgesehenen Analysedaten erhoben oder verarbeitet.", "In V1.1, no feedback checkpoints, voluntary product-feedback comments or related analysis data are collected or processed.")}</li>
              )}
              <li><span className="text-foreground">{tr("Trainer sehen keine privaten Athleteninhalte.", "Coaches do not see private athlete content.")}</span> {tr("Keine einzelnen Zustandswerte, keine Journale, keine freien Antworten und keine individuellen Assessment-Ergebnisse. Sichtbar sind nur operative Teilnahmeinformationen und ausreichend große Teamaggregate. Trainer können außerdem eigene, strukturierte Beobachtungen zu sichtbarem Sportverhalten erfassen.", "They see no individual state scores, journals, free-text answers or individual assessment results. Only operational participation information and sufficiently large team aggregates are visible. Coaches may also record their own structured observations of visible sporting behavior.")}</li>
              <li><span className="text-foreground">{tr("Gruppierte Fortschrittsdaten ohne direkte Identifikatoren", "Grouped progress data without direct identifiers")}</span> {tr("können beobachtete Veränderungen und Datenqualität dokumentieren - aber nur, wenn du aktiv zustimmst. Du entscheidest. Du kannst jederzeit widerrufen.", "can document observed changes and data quality — but only if you actively consent. The choice is yours. You can withdraw at any time.")}</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Warum überhaupt Daten erhoben werden", "Why data is collected at all")}</h2>
            <p>
              {tr("RewirePerform ist kein Inhaltsarchiv, sondern ein 56-Tage-Prozess. Ohne minimale Daten kann das System nicht erkennen, an welchem Tag du stehst, welche Aufgabe heute zu dir passt, ob deine Veränderung zwischen Anfang und Ende sichtbar wird oder ob eine Erinnerung gesendet werden soll.", "RewirePerform is not a content archive but a 56-day process. Without minimal data, the system cannot determine which day you are on, which task fits today, whether change from start to finish can be shown, or whether a reminder should be sent.")}
            </p>
            <p className="mt-3">
              {tr("Erhoben wird ausschließlich, was für vier klar getrennte Zwecke nötig ist:", "Only what is needed for four clearly separate purposes is collected:")}
              <span className="text-foreground"> (1)</span> {tr("dein Programm sauber durchzuführen,", "to run your program properly,")}
              <span className="text-foreground"> (2)</span> {tr("dir am Ende ehrlich zu zeigen, was sich verändert hat, und", "to show you honestly what changed by the end, and")}
              <span className="text-foreground"> (3)</span> {tr("- wenn du zustimmst - beobachtete Veränderungen gruppiert und mit klaren Aussagegrenzen auszuwerten.", "— if you consent — to evaluate observed changes in groups with clear limits on what can be concluded.")}
              {feedbackEnabled
                ? tr(" (4) freiwilliges Produktfeedback zu nutzen, um RewirePerform verständlicher und hilfreicher zu machen.", " (4) to use voluntary product feedback to make RewirePerform clearer and more helpful.")
                : tr(" Eine spätere, getrennt freizugebende Feedback-Intelligence-Funktion ist nicht Teil dieser V1.1-Auslieferung.", " A future Feedback Intelligence feature requiring separate approval is not part of this V1.1 release.")}
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Rechtsgrundlage (DSGVO)", "Legal basis (GDPR)")}</h2>
            <ul className="space-y-2">
              <li><span className="text-foreground">{tr("Art. 6 Abs. 1 lit. b DSGVO — Bereitstellung des Angebots:", "GDPR Article 6(1)(b) — providing the service:")}</span> {tr("Konto, Teamzugang, Programmfortschritt, Tageslogik, Check-ins, Assessments, Kalender- und Trainingsplanung sowie auf Wunsch Erinnerungen. Ohne die jeweils erforderlichen Daten kann die zugehörige Funktion nicht erbracht werden.", "Account, team access, program progress, day logic, check-ins, assessments, calendar and training planning, and reminders if requested. Without the data required for each function, that function cannot be provided.")}</li>
              {webAnalyticsEnabled && <li><span className="text-foreground">{tr("Art. 6 Abs. 1 lit. f DSGVO — datensparsame Reichweitenmessung der öffentlichen Website:", "GDPR Article 6(1)(f) — privacy-conscious reach measurement for the public website:")}</span> {tr("Wir werten aggregiert aus, welche öffentlichen Seiten aufgerufen werden und über welche Quellen Menschen die Website finden, damit wir die Information über RewirePerform verständlicher machen können. Dafür werden keine RewirePerform-Konten, Trainings-, Gesundheits-, Feedback- oder Freitextdaten verwendet und keine Werbeprofile erstellt.", "We analyze in aggregate which public pages are visited and how people find the website, so we can make information about RewirePerform clearer. No RewirePerform account, training, health, feedback or free-text data is used for this, and no advertising profiles are created.")}</li>}
              <li><span className="text-foreground">{tr("Team- und Organisationsanfragen:", "Team and organization inquiries:")}</span> {tr("Soweit du selbst vorvertragliche Schritte anfragst, erfolgt die Bearbeitung auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO. Soweit du eine Organisation vertrittst, stützen wir die angefragte geschäftliche Kommunikation und die angemessene Vorbereitung auf Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse besteht darin, die von dir initiierte Anfrage sicher und passend zu beantworten. Der technische Missbrauchsschutz und die Prüfung offensichtlicher Fake-/Spam-Anfragen beruhen ebenfalls auf diesem Sicherheitsinteresse.", "Where you request pre-contractual steps for yourself, processing is based on GDPR Article 6(1)(b). Where you represent an organization, the requested business communication and appropriate preparation are based on GDPR Article 6(1)(f). Our legitimate interest is to answer the inquiry you initiated safely and appropriately. Technical abuse protection and checks for obvious fake or spam inquiries are based on the same security interest.")}</li>
              <li><span className="text-foreground">{tr("Art. 6 Abs. 1 lit. a DSGVO - Einwilligung:", "GDPR Article 6(1)(a) — consent:")}</span> {tr("Die Nutzung freiwillig freigegebener Pilotdaten für interne Analysen sowie nicht identifizierende Pilotberichte und Präsentationen.", "The use of voluntarily shared pilot data for internal analyses and non-identifying pilot reports and presentations.")} {feedbackEnabled ? tr("Dies gilt außerdem für freiwillige Feedback-Checkpoints. Ein Produktfeedback-Kommentar und seine interne Prüfung zur Produktverbesserung erfordern eine zusätzliche ausdrückliche Einwilligung, die jederzeit ohne Nachteil widerrufbar ist.", "This also applies to voluntary feedback checkpoints. A product-feedback comment and its internal review for product improvement require additional explicit consent, which can be withdrawn at any time without disadvantage.") : tr("Feedback Intelligence, Feedback-Kommentare und ein Jarvis-Zugriff sind nicht Teil dieser V1.1-Auslieferung.", "Feedback Intelligence, feedback comments and Jarvis access are not part of this V1.1 release.")}</li>
              <li><span className="text-foreground">{tr("Art. 9 Abs. 2 lit. a DSGVO - ausdrückliche Einwilligung:", "GDPR Article 9(2)(a) — explicit consent:")}</span> {tr("Soweit psychologisch sensible Angaben verarbeitet werden, ist dafür eine gesonderte, ausdrückliche Einwilligung erforderlich.", "Where psychologically sensitive information is processed, separate explicit consent is required.")}</li>
              <li><span className="text-foreground">{tr("Minderjährige und Länderumfang:", "Minors and country scope:")}</span> {tr("RewirePerform ist ab 13 Jahren vorgesehen und wird derzeit ausschließlich für Deutschland angeboten. Von 13 bis einschließlich 15 werden datenabhängige Programmfunktionen erst freigeschaltet, wenn eine sorgeberechtigte Person und der Jugendliche selbst der aktuellen Version zugestimmt haben. Mit 16 oder 17 entscheidet der Jugendliche selbst. Zugriffe aus nicht freigegebenen Ländern bleiben technisch gesperrt. Bei einer späteren internationalen Einführung werden Rechts-, Datenschutz- und Store-Anforderungen erneut für den dann vorgesehenen Umfang geprüft. Der Verein ist an diesem Freigabeprozess nicht beteiligt.", "RewirePerform is intended for ages 13 and up and is currently offered only in Germany. For ages 13 through 15, data-dependent program features are enabled only after both a parent or guardian and the young person have agreed to the current version. At ages 16 or 17, the young person decides for themselves. Access from countries that have not been approved remains technically blocked. Before any future international launch, legal, privacy and store requirements will be reassessed for the intended scope. The club is not involved in this approval process.")}</li>
            </ul>
          </section>

          <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5">
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Freigabe für Minderjährige", "Authorization for minors")}</h2>
            <ul className="space-y-2">
              <li>{tr("Wir speichern nur die Altersgruppe, kein Geburtsdatum und keine Ausweiskopie.", "We store only the age group, not a date of birth or ID copy.")}</li>
              <li>{tr("Die E-Mail-Adresse der sorgeberechtigten Person wird vom Jugendlichen selbst eingegeben, im Autorisierungssystem verschlüsselt gespeichert und nur für Einladung, Nachweis, Support und Widerruf verwendet.", "The young person enters their parent or guardian's email address themselves. It is stored encrypted in the authorization system and used only for the invitation, records, support and withdrawal.")}</li>
              <li>{tr("Der Einmallink ist 48 Stunden gültig. Einladungs- und Widerrufstoken werden nur als Hash gespeichert und nach den unten genannten Fristen automatisiert entfernt.", "The one-time link is valid for 48 hours. Invitation and withdrawal tokens are stored only as hashes and automatically removed after the periods stated below.")}</li>
              <li>{tr("Trainer und Verein sehen weder die E-Mail-Adresse der sorgeberechtigten Person noch ihre Entscheidung oder einen Ablehnungsgrund.", "Coaches and the club see neither the parent or guardian's email address nor their decision or reason for refusal.")}</li>
              <li>{tr("Die Programmfreigabe und die getrennte Pilot-Auswertung können über den persönlichen Widerrufslink, in der App oder über den Datenschutzkontakt widerrufen werden.", "Program authorization and the separate pilot evaluation can be withdrawn through the personal withdrawal link, in the app or through the privacy contact.")}</li>
              <li>{tr("Die Pilot-Auswertung wird nur aktiviert, wenn die altersgerechten Entscheidungen in der aktuellen Textversion vorliegen: von 13 bis einschließlich 15 durch die sorgeberechtigte Person und den Jugendlichen, mit 16 oder 17 durch den Jugendlichen selbst.", "Pilot evaluation is enabled only if the age-appropriate decisions for the current text version are on record: for ages 13 through 15, from both the parent or guardian and the young person; for ages 16 or 17, from the young person themselves.")}</li>
              <li>{feedbackEnabled ? tr("Bei 13- bis 15-Jährigen öffnet eine aktuelle Guardian-Freigabe nur die Möglichkeit für Produktfeedback-Kommentare. Der Jugendliche entscheidet an jedem Checkpoint zusätzlich selbst; ohne beide Entscheidungen wird kein Kommentar gespeichert oder für die interne Prüfung freigegeben. Auswahlfragen bleiben auch ohne Kommentar nutzbar. In die interne Jarvis-Zusammenfassung strukturierter Auswahlantworten werden Minderjährige nur einbezogen, wenn zusätzlich die aktuelle altersgerechte Datenbeitragsfreigabe vollständig gültig ist — unter 16 durch Guardian und Jugendlichen, ab 16 durch den Jugendlichen selbst.", "For ages 13 through 15, current guardian authorization only opens the option to submit product-feedback comments. The young person also decides at each checkpoint; without both decisions, no comment is stored or released for internal review. Multiple-choice questions remain usable without a comment. Minors are included in the internal Jarvis summary of structured answers only if current age-appropriate data-contribution authorization is also fully valid — from both guardian and young person under 16, and from the young person at 16 or 17.") : tr("Feedback Intelligence mit Checkpoints, Kommentaren oder einem Jarvis-Zugriff ist nicht Teil dieser V1.1-Auslieferung. Dafür wird in V1.1 keine zusätzliche Minderjährigen-Freigabe erhoben oder genutzt.", "Feedback Intelligence with checkpoints, comments or Jarvis access is not part of this V1.1 release. No additional authorization for minors is collected or used for this in V1.1.")}</li>
              <li>{tr("Eine externe wissenschaftliche Studie oder weitergehende Forschungsnutzung würde eine neue, getrennte Information und Entscheidung erfordern.", "An external scientific study or broader research use would require new, separate information and a separate decision.")}</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Welche Daten konkret verarbeitet werden", "What data is processed")}</h2>
            <ul className="space-y-2">
              <li><span className="text-foreground">{tr("Konto:", "Account:")}</span> {tr("E-Mail, Passwort-Hash, Rolle (Athlet, Trainer oder Administrator) und Sportprofil-Angaben.", "Email, password hash, role (athlete, coach or administrator) and sports-profile information.")}</li>
              <li><span className="text-foreground">{tr("Programmfortschritt:", "Program progress:")}</span> {tr("Programmlauf und Startdatum, aktueller Tag, geöffnete und erledigte Aufgaben, Abschlusszeitpunkte, Bearbeitungsdauer, Serien und Phase. Bei einer Ruhetags-Visualisierung wird nur der Abschluss gespeichert, nicht die vorgestellte Szene.", "Program run and start date, current day, opened and completed tasks, completion times, time spent, streaks and phase. For a rest-day visualization, only completion is stored, not the imagined scene.")}</li>
              <li><span className="text-foreground">{tr("Täglicher Check-in:", "Daily check-in:")}</span> {tr("Ereignisart sowie Stimmung, Energie, mentale Klarheit beziehungsweise Fokus, Stress beziehungsweise innere Spannung, Erholung, Schlafqualität, körperliche Bereitschaft, Bereitschaft beziehungsweise Motivation, Leistungsdruck und Verbindung zum sportlichen Umfeld als Zahlenwerte pro Tag. Zusätzlich wird gespeichert, welche vorgesehenen Schritte abgeschlossen wurden.", "Event type and numerical daily values for mood, energy, mental clarity or focus, stress or inner tension, recovery, sleep quality, physical readiness, readiness or motivation, performance pressure and connection to the sporting environment. We also store which scheduled steps were completed.")}</li>
              <li><span className="text-foreground">{tr("Strukturierte Assessments und Fragebögen:", "Structured assessments and questionnaires:")}</span> {tr("Werte zu Beginn, in der Mitte und am Ende, um beobachtete Veränderungen über die 56 Tage zu dokumentieren. Aussagekraft, Version und Nutzungsrechte jedes Instruments werden getrennt bewertet.", "Values at the beginning, middle and end to document observed changes across 56 days. The validity, version and usage rights of each instrument are assessed separately.")}</li>
              <li><span className="text-foreground">{tr("Strukturierte Transfer-Beobachtungen:", "Structured transfer observations:")}</span> {tr("An ausgewählten Tagen eine kurze Antwort zu einem konkreten Verhalten in Training oder Wettkampf. Sie ersetzt die optionale freie Reflexion und enthält keinen Freitext.", "On selected days, a short answer about specific behavior in training or competition. It replaces the optional free-form reflection and contains no free text.")}</li>
              <li><span className="text-foreground">{tr("Kalender und Training:", "Calendar and training:")}</span> {tr("eigene beziehungsweise teambezogene Trainings-, Wettkampf- und Ruhetage, Zeiten, Zeitzone und Erinnerungsplanung, soweit diese Funktionen genutzt werden.", "Individual or team-related training, competition and rest days, times, time zone and reminder scheduling, where these functions are used.")}</li>
              <li><span className="text-foreground">{tr("Trainer-Beobachtungen:", "Coach observations:")}</span> {tr("Strukturierte Bewertungen direkt beobachtbaren Sportverhaltens. Sie enthalten keine Diagnose und keinen Pflicht-Freitext. Sie gehören derzeit nicht zur Pilot-Auswertung und werden nicht an Jarvis oder in externe Auswertungs-Exporte übermittelt.", "Structured ratings of directly observable sporting behavior. They contain no diagnosis and no mandatory free text. They are currently not part of pilot evaluation and are not sent to Jarvis or external evaluation exports.")}</li>
              <li><span className="text-foreground">{tr("Coach-Teamzugänge:", "Coach team access:")}</span> {tr("Teamzuordnung, Coach-Rolle und ein hochentropischer Teamlink. Der Lead Coach verwaltet diesen Link; jeder Co-Coach verwendet ein eigenes bestätigtes Konto.", "Team assignment, coach role and a high-entropy team link. The lead coach manages this link; each co-coach uses their own confirmed account.")}</li>
              <li><span className="text-foreground">{tr("Journale, private Reflexionen und sonstige freie Antworten:", "Journals, private reflections and other free-text answers:")}</span> {tr("werden ausschließlich gespeichert, damit du sie wiederfindest.", "are stored only so you can find them again.")} <span className="text-foreground">{tr("Sie werden nicht ausgewertet, nicht durchsucht, nicht von einer KI gelesen, nicht in Gruppenwerte einbezogen und nicht für Personalisierung verwendet.", "They are not evaluated, searched, read by AI, included in group values or used for personalization.")}</span></li>
              <li><span className="text-foreground">Feedback Intelligence:</span> {feedbackEnabled ? tr("Für Tag 10, 24, 39 und 55 freiwillige, überspringbare Auswahlantworten. Ein verpasster, noch offener Zwischenstand kann beim nächsten späteren Login erneut angeboten oder später erinnert werden; für jeden Zeitpunkt kann auch entschieden werden, kein Feedback zu geben. Jarvis verarbeitet dafür pseudonymisierte Einzelzeilen nur vorübergehend im Arbeitsspeicher und gibt ausschließlich Gruppenzusammenfassungen pro Frage ab mindestens fünf unterschiedlichen Teilnehmenden aus. Ein optionaler, klar markierter Produktfeedback-Kommentar wird nach getrennter Einwilligung ausschließlich für die geschützte menschliche Admin-Prüfung gespeichert und niemals an Jarvis übermittelt. Dein Coach sieht keine Einzelantworten oder Kommentare. Name, E-Mail-Adresse, Journale, private Reflexionen, Supporttexte, Team- und Coach-IDs sind ausgeschlossen.", "Voluntary, skippable multiple-choice answers on days 10, 24, 39 and 55. A missed checkpoint that remains open may be offered again at a later sign-in or deferred with a reminder; you may also decide not to give feedback for that checkpoint. Jarvis processes pseudonymized individual rows only temporarily in memory and outputs only group summaries per question involving at least five different participants. An optional, clearly marked product-feedback comment is stored only with separate consent for protected human admin review and is never sent to Jarvis. Your coach sees no individual answers or comments. Names, email addresses, journals, private reflections, support texts, team IDs and coach IDs are excluded.") : tr("Die vorgesehenen Checkpoints an Tag 10, 24, 39 und 55, freiwillige Produktfeedback-Kommentare und ein zugehöriger Analyseexport sind nicht Teil dieser V1.1-Auslieferung. Dafür werden in V1.1 keine Daten erhoben.", "The planned checkpoints on days 10, 24, 39 and 55, voluntary product-feedback comments and a related analysis export are not part of this V1.1 release. No data is collected for them in V1.1.")}</li>
              <li><span className="text-foreground">{tr("Direkte Support- und Feedbacknachrichten:", "Direct support and feedback messages:")}</span> {tr("Wenn du unter „Mehr“ einen Fehler, Vorschlag oder allgemeinen Hinweis sendest, speichern wir Nachricht, Kategorie, Zeitpunkt und minimierte technische Angaben wie Plattform, App-Version, Online-Status und die bereinigte App-Seite. Diese Nachrichten werden von berechtigten Administratoren zur Bearbeitung gelesen, aber nicht mit Feedback Intelligence vermischt und nicht an Jarvis übermittelt.", "If you send an error report, suggestion or general note under ‘More’, we store the message, category, time and minimized technical information such as platform, app version, online status and sanitized app page. Authorized administrators read these messages to handle them. They are not combined with Feedback Intelligence or sent to Jarvis.")}</li>
              <li><span className="text-foreground">{tr("Technische Fehlerdaten:", "Technical error data:")}</span> {tr("Bei einem fehlgeschlagenen Kernvorgang können ein normalisierter Fehlercode, eine bereinigte App-Seite, Zeitpunkt, Plattform, App-Version und Testkennzeichnung gespeichert werden. Normale Nutzung wird nicht als technisches Fehlerereignis protokolliert.", "If a core operation fails, a normalized error code, sanitized app page, time, platform, app version and test indicator may be stored. Normal use is not recorded as a technical error event.")}</li>
              <li><span className="text-foreground">{tr("Team- und Organisationsanfragen:", "Team and organization inquiries:")}</span> {tr("Name, E-Mail-Adresse, Funktion sowie die angegebenen Team-, Organisations-, Sport- und Projektinformationen. Eine Telefonnummer wird nur in der ausführlichen Organisationsstrecke und nur freiwillig beziehungsweise passend zum gewählten Kontaktweg erhoben. Bitte übermittle dabei keine Namen oder persönlichen Daten von Athleten.", "Name, email address, role and the team, organization, sport and project information provided. A phone number is collected only in the detailed organization path and only voluntarily or where appropriate to the selected contact method. Please do not submit athletes' names or personal data.")}</li>
              <li><span className="text-foreground">{tr("Trainingszeiten und Benachrichtigungseinstellungen:", "Training times and notification settings:")}</span> {tr("nur, wenn du Erinnerungen aktivierst.", "only if you enable reminders.")}</li>
            </ul>
          </section>

          <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5">
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Freiwillige Spracheingabe", "Optional voice input")}</h2>
            <p>
              {tr("In der nativen iPhone- und iPad-App kannst du bestimmte Antworten freiwillig einsprechen. Die Funktion wird nur angeboten, wenn das Gerät die deutsche Spracherkennung vollständig lokal unterstützt. Die Audiodaten bleiben auf dem Gerät, werden nicht zu RewirePerform oder einem Spracherkennungsserver übertragen und nicht als Aufnahme gespeichert.", "In the native iPhone and iPad app, you may optionally dictate certain answers. This feature is offered only if the device fully supports on-device German speech recognition. Audio data stays on the device, is not sent to RewirePerform or a speech-recognition server, and is not stored as a recording.")}
            </p>
            <p className="mt-3">
              {tr("Gespeichert wird nur der übernommene und weiterhin bearbeitbare Text - genauso, als hättest du ihn getippt. Für Journale und private Reflexionen gelten anschließend unverändert die privaten Schutzregeln dieser Erklärung.", "Only the accepted text, which remains editable, is stored — just as if you had typed it. The private-protection rules in this notice continue to apply to journals and private reflections.")} {feedbackEnabled ? tr("Für ein klar markiertes Produktfeedback-Kommentarfeld gelten die getrennte Einwilligung und die Feedback-Regeln dieser Erklärung.", "A clearly marked product-feedback comment field is subject to separate consent and the feedback rules in this notice.") : tr("Ein Produktfeedback-Kommentarfeld ist nicht Teil dieser V1.1-Auslieferung.", "A product-feedback comment field is not part of this V1.1 release.")} {tr("Unterstützt ein iPhone die lokale Erkennung nicht, erfolgt kein automatischer Server-Fallback; Tippen bleibt jederzeit möglich.", "If an iPhone does not support on-device recognition, there is no automatic server fallback; typing remains available at all times.")}
            </p>
            <p className="mt-3">
              {tr("In der Web-App kann die optionale Spracherkennung technisch durch den verwendeten Browser beziehungsweise dessen Anbieter bereitgestellt werden. Der Browser kann Audiodaten dafür nach seinen eigenen Datenschutzbedingungen verarbeiten. RewirePerform erstellt oder speichert auch dort keine Audioaufnahme.", "In the web app, optional speech recognition may technically be provided by the browser or its provider. The browser may process audio data under its own privacy terms. RewirePerform does not create or store an audio recording there either.")}
            </p>
          </section>

          <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5">
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Journale & private Reflexionen — die ehrliche Klarstellung", "Journals and private reflections — an honest clarification")}</h2>
            <p>
              {tr("In früheren Versionen dieser Seite stand sinngemäß, das System könne „wiederkehrende Themen vorsichtig erkennen“. Das stimmt nicht und wird hiermit korrigiert.", "Earlier versions of this page suggested that the system could ‘cautiously identify recurring themes’. That was incorrect, and we correct it here.")}
            </p>
            <p className="mt-3 text-foreground">
              {tr("Wahrheit: Deine Journale, privaten Reflexionen und sonstigen freien Antworten werden gespeichert, damit du sie selbst wieder lesen kannst. Sonst nichts.", "The truth: your journals, private reflections and other free-text answers are stored so you can read them again yourself. Nothing else.")}
            </p>
            <p className="mt-3">
              {tr("Konkret bedeutet das: Keine KI verarbeitet sie. Keine Mustererkennung läuft darüber. Keine Personalisierung greift auf sie zu. Keine Mitarbeiter lesen sie zur Verbesserung des Produkts. Sie fließen nicht in die anonymen Aggregat-Statistiken ein, selbst wenn du deren Nutzung erlaubst. Trainer sehen sie nie — auch nicht in Ausschnitten, auch nicht in Stichwörtern, auch nicht gruppiert.", "Specifically: no AI processes them. No pattern recognition runs on them. Personalization does not use them. Staff do not read them to improve the product. They are not included in anonymous aggregate statistics, even if you permit the use of those statistics. Coaches never see them — not as excerpts, keywords or grouped content.")}
            </p>
            <p className="mt-3">
              {feedbackEnabled
                ? tr("Die einzige Ausnahme ist ein klar als Produktfeedback markiertes Kommentarfeld an einem Feedback-Checkpoint. Es wird ausschließlich nach der getrennten Freitext-Einwilligung verarbeitet. Diese Ausnahme gilt nie für Journale, private Reflexionen oder sonstige freie Antworten.", "The only exception is a comment field clearly marked as product feedback at a feedback checkpoint. It is processed only after separate consent for free text. This exception never applies to journals, private reflections or other free-text answers.")
                : tr("In V1.1 gibt es keine als Produktfeedback markierten Felder, Feedback-Checkpoints oder freiwilligen Produktfeedback-Kommentare. Für deine Journale und privaten Reflexionen gibt es damit keine Ausnahme.", "In V1.1 there are no fields marked as product feedback, feedback checkpoints or voluntary product-feedback comments. There is therefore no exception for your journals and private reflections.")}
            </p>
            <p className="mt-3">
              {tr("Reflexion funktioniert nur, wenn sie ehrlich ist. Ehrlich wird sie nur, wenn sie sicher ist. Deshalb diese Linie. Sie bleibt.", "Reflection works only when it is honest. It can be honest only when it feels safe. That is why this boundary exists. It will remain.")}
            </p>
          </section>

          <section className="rounded-2xl border border-primary/30 bg-primary/10 p-5">
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Pilot-Auswertung - hilf anderen Athleten", "Pilot evaluation — help other athletes")}</h2>
            <p>
              {tr("Wenn du zustimmst, dürfen ausgewählte strukturierte Fortschritts- und Performancedaten für interne Pilot-Analysen sowie", "If you consent, selected structured progress and performance data may be evaluated for internal pilot analyses and")} <span className="text-foreground">{tr("gruppierte Berichte und Präsentationen ohne direkte Identifikatoren", "grouped reports and presentations without direct identifiers")}</span>{tr(" ausgewertet werden. Sie dokumentieren Nutzung, Datenqualität und beobachtete Veränderungen. Sie beweisen für sich allein weder Ursache noch sportliche Leistungssteigerung.", ". They document use, data quality and observed changes. On their own, they prove neither causation nor improved sporting performance.")}
            </p>
            <p className="mt-3 text-foreground">{tr("Was konkret in solche Aggregate einfließen darf:", "What may be included in these aggregates:")}</p>
            <ul className="mt-2 space-y-1">
              <li>– {tr("Programmfortschritt (Tage, Serien und Abschlussquoten)", "Program progress (days, streaks and completion rates)")}</li>
              <li>– {tr("Veränderungen zwischen Anfang und Ende aus freigegebenen, versionierten Assessments und Fragebögen", "Changes from start to finish based on approved, versioned assessments and questionnaires")}</li>
              <li>– {tr("zeitliche Entwicklungen bei Stimmung, Energie und Fokus", "Trends over time in mood, energy and focus")}</li>
              <li>– {tr("strukturierte Transfer-Antworten", "Structured transfer answers")}</li>
            </ul>
            <p className="mt-3 text-foreground">{tr("Was niemals einfließt — auch nicht mit deiner Zustimmung:", "What is never included — even with your consent:")}</p>
            <ul className="mt-2 space-y-1">
              <li>– {tr("Journaltexte, persönliche Reflexionen und sonstige freie Antworten", "Journal text, personal reflections and other free-text answers")}</li>
              <li>– {tr("strukturierte Team- oder Einzelbeobachtungen von Trainern", "Structured team or individual coach observations")}</li>
              <li>– {tr("identifizierbare Einzelantworten oder individuelle Athletenprofile in Berichten und Präsentationen", "Identifiable individual answers or athlete profiles in reports and presentations")}</li>
              <li>– {tr("Identifizierende Merkmale (Name, E-Mail, Geburtsdatum, Position, Verein)", "Identifying details (name, email, date of birth, position, club)")}</li>
              <li>– {tr("Werte aus Gruppen mit weniger als fünf freigegebenen Personen", "Values from groups with fewer than five consenting people")}</li>
            </ul>
            <p className="mt-3">
              {feedbackEnabled
                ? tr("Feedback-Auswahlantworten und ausdrücklich freigegebene Produktfeedback-Kommentare dienen der internen Produktverbesserung. Sie erscheinen nie in Coach-Ansichten. Kommentare werden nicht in Client-Analytics, technische Logs oder Standardexporte geschrieben und nicht für Werbung, Personalisierung oder automatisierte Entscheidungen verwendet.", "Feedback multiple-choice answers and explicitly authorized product-feedback comments are used for internal product improvement. They never appear in coach views. Comments are not written to client analytics, technical logs or standard exports, and are not used for advertising, personalization or automated decisions.")
                : tr("Feedback Intelligence mit strukturierten Checkpoints, Kommentaren oder einem Analyseexport ist nicht Teil dieser V1.1-Auslieferung. Aus diesem späteren Funktionsbereich fließen in V1.1 keine Daten in Gruppenaggregate, Coach-Ansichten, Client-Analytics, Logs oder Standardexporte ein.", "Feedback Intelligence with structured checkpoints, comments or an analysis export is not part of this V1.1 release. In V1.1, no data from this future feature area enters group aggregates, coach views, client analytics, logs or standard exports.")}
            </p>
            <p className="mt-3">
              {tr("Gruppenaggregate werden erst ab mindestens fünf freigegebenen Personen ausgegeben und enthalten keine Namen oder E-Mail-Adressen. Die Einwilligung ist freiwillig, jederzeit in den Einstellungen widerrufbar und beeinflusst", "Group aggregates are output only with at least five consenting people and contain no names or email addresses. Consent is voluntary, can be withdrawn in Settings at any time and does not")} <span className="text-foreground">{tr("in keiner Weise", "in any way")}</span> {tr("wie die App für dich funktioniert. Nach einem Widerruf werden keine neuen Pilotdaten erhoben, vorhandene personenbezogene Transferdaten aus der Pilot-Auswertung entfernt und nicht mehr in neue Auswertungen einbezogen. Bereits gebildete, wirklich anonyme Gruppenaggregate können bestehen bleiben.", "affect how the app works for you. After withdrawal, no new pilot data is collected; existing personal transfer data is removed from pilot evaluation and no longer included in new evaluations. Group aggregates already created may remain if they are genuinely anonymous.")}
            </p>
            <p className="mt-3">
              {tr("In einer früheren Guardian-Information wurden freigegebene Coach-Beobachtungen als möglicher Pilotdatenbereich genannt. Dieser Bereich ist im aktuellen technischen Umfang nicht aktiviert und wird nicht auf Grundlage dieser Formulierung verarbeitet. Eine spätere Einbeziehung erfordert eine neue, konkrete Information und eine neue Entscheidung.", "An earlier guardian notice mentioned authorized coach observations as a possible pilot-data area. That area is not enabled in the current technical scope and is not processed on the basis of that wording. Any later inclusion requires new, specific information and a new decision.")}
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Wie das Hintergrundsystem deine Angaben nutzt", "How the system uses your information")}</h2>
            <p>
              {tr("Das System ordnet Check-ins, Aufgaben und Assessments dem richtigen Programmtag zu, berechnet Serien und Abschlüsse, entscheidet, welcher Tagesinhalt heute angezeigt wird, und bereitet deinen Vergleich zwischen Anfang und Ende auf. Der feste 56-Tage-Inhalt und seine Missionen werden nicht von einer KI erzeugt. Kurze, deterministische Einordnungen können den Programmtag, den Kalenderkontext und strukturierte Angaben zu Sport, Rolle oder Tageszustand berücksichtigen —", "The system assigns check-ins, tasks and assessments to the correct program day, calculates streaks and completions, decides which daily content to show, and prepares your comparison between start and finish. The fixed 56-day content and its missions are not generated by AI. Short, deterministic classifications may take into account the program day, calendar context and structured information about sport, role or daily state —")} <span className="text-foreground">{tr("nie Journaltexte oder private Reflexionen", "never journal text or private reflections")}</span>.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Trainer- und Team-Sicht", "Coach and team view")}</h2>
            <p>
              {tr("Trainer sehen für ihr zugeordnetes Team operative Programmdaten wie letzte Aktivität, erledigte Tage, Abschlussquote, aktuelle Serie, Check-ins der letzten sieben Tage, Journal-Anzahl (nie Inhalt) und Inaktivitäts-Hinweis. Sensible Team-Zustandswerte erscheinen erst ab fünf freigegebenen Athleten.", "For their assigned team, coaches see operational program data such as latest activity, completed days, completion rate, current streak, check-ins over the past seven days, the number of journal entries (never their content), and an inactivity indicator. Sensitive team-state values appear only with at least five consenting athletes.")}
            </p>
            <p className="mt-3">
              {tr("Ausdrücklich nicht sichtbar für Trainer: einzelne Werte zu Stimmung, Energie oder Fokus, Journaltexte, private Freitextantworten, individuelle Assessment-Ergebnisse oder persönliche Entwicklungsbezeichnungen.", "Coaches explicitly cannot see individual mood, energy or focus values, journal text, private free-text answers, individual assessment results or personal development labels.")}
            </p>
            <p className="mt-3">
              {tr("Ein Trainer kann zusätzlich eigene strukturierte Team- oder Einzelbeobachtungen zu fünf direkt sichtbaren Verhaltensbereichen speichern. Eine Einzelbeobachtung kann nur der eingebende Trainer erneut öffnen. Sie wird weder dem Athleten angezeigt noch in Website-, KI- oder externe Auswertungs-Exporte aufgenommen.", "A coach may also store their own structured team or individual observations across five directly observable behavior areas. An individual observation can be reopened only by the coach who entered it. It is not shown to the athlete or included in website, AI or external evaluation exports.")}
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Deine Rechte", "Your rights")}</h2>
            <ul className="space-y-2">
              <li><span className="text-foreground">{tr("Auskunft (Art. 15):", "Access (Art. 15):")}</span> {tr("Du kannst eine Kopie aller gespeicherten Daten anfordern.", "You can request a copy of all stored data.")}</li>
              <li><span className="text-foreground">{tr("Berichtigung (Art. 16):", "Rectification (Art. 16):")}</span> {tr("Falsche Angaben korrigieren wir auf Wunsch.", "We will correct inaccurate information on request.")}</li>
              <li><span className="text-foreground">{tr("Löschung (Art. 17):", "Erasure (Art. 17):")}</span> {tr("Unter „Einstellungen → Konto & Daten“ kannst du dein Konto und die zugehörigen personenbezogenen Daten direkt löschen.", "Under ‘Settings → Account & Data’, you can directly delete your account and associated personal data.")}</li>
              <li><span className="text-foreground">{tr("Datenübertragbarkeit (Art. 20):", "Data portability (Art. 20):")}</span> {tr("Export deiner Daten in einem maschinenlesbaren Format.", "Export of your data in a machine-readable format.")}</li>
              <li><span className="text-foreground">{tr("Widerruf (Art. 7 Abs. 3):", "Withdrawal (Art. 7(3)):")}</span> {tr("Einwilligungen kannst du jederzeit widerrufen, ohne Begründung, ohne Nachteil.", "You can withdraw consent at any time, without giving a reason and without disadvantage.")}</li>
              <li><span className="text-foreground">{tr("Beschwerde (Art. 77):", "Complaint (Art. 77):")}</span> {tr("Bei der zuständigen Datenschutz-Aufsichtsbehörde.", "You can complain to the competent data-protection supervisory authority.")}</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Speicherdauer", "Retention periods")}</h2>
            <p>
              {tr("Programmdaten bleiben gespeichert, solange dein Konto aktiv ist. Bei der Kontolöschung werden dein Zugang und die personenbezogenen Daten direkt aus dem aktiven System entfernt. RewirePerform betreibt derzeit keinen regelmäßigen eigenen Datenbank-Backupdienst. Falls für eine freigegebene Migration oder Wiederherstellungsprüfung vorübergehend ein eigener verschlüsselter Sicherungsexport erstellt wird, bleibt er vom Produktzugriff getrennt und wird spätestens sieben Kalendertage nach seiner Erstellung gelöscht. Soweit gelöschte Daten vorübergehend in nicht direkt zugänglichen providerseitigen technischen Sicherungs- oder Betriebsdaten enthalten sind, werden sie nicht für Produkt, Support, Analyse oder Evidence genutzt und nach den vertraglichen Providerfristen gelöscht. Bei einer Beendigung des Supabase-Vertrags sieht der aktuelle Auftragsverarbeitungsvertrag nach einer Rückgabefrist von 30 Tagen die Löschung aller dort verarbeiteten personenbezogenen Daten vor. Diese Providerfrist ist von der unmittelbaren Löschung im aktiven System zu unterscheiden. Bereits zuvor mit Einwilligung gebildete Gruppenstatistiken können bestehen bleiben, wenn sie vollständig aggregiert sind und keinen Rückschluss auf einzelne Personen zulassen.", "Program data remains stored while your account is active. When the account is deleted, access and personal data are removed directly from the active system. RewirePerform currently operates no regular proprietary database-backup service. If a temporary encrypted backup export is created for an approved migration or recovery check, it remains separate from product access and is deleted no later than seven calendar days after creation. If deleted data temporarily remains in provider-side technical backups or operational data that are not directly accessible, it is not used for the product, support, analysis or evidence, and is deleted according to the provider's contractual periods. When the Supabase contract ends, the current data-processing agreement provides for deletion of all personal data processed there after a 30-day return period. This provider period is separate from immediate deletion in the active system. Group statistics previously formed with consent may remain if fully aggregated and no individual can be identified from them.")}
            </p>
            <ul className="mt-3 space-y-1">
              <li>– {tr("Einladungsdaten einschließlich der verschlüsselten Elternadresse: spätestens sieben Tage nach Erstellung der Einladung", "Invitation data, including the encrypted parent or guardian address: no later than seven days after the invitation is created")}</li>
              <li>– {tr("wiederverwendbarer Co-Coach-Teamlink: bis zur Erneuerung durch den Lead Coach oder bis zur Löschung des zugehörigen Teams; bereits angenommene Coach-Zugänge bleiben davon unberührt", "Reusable co-coach team link: until the lead coach renews it or the associated team is deleted; coach access already accepted is unaffected")}</li>
              <li>– {tr("gehashter Widerrufslink der sorgeberechtigten Person: bis zu 370 Tage aktiv; nach Nutzung, Widerruf oder Ablauf Löschung innerhalb von sieben Tagen", "Hashed parent or guardian withdrawal link: active for up to 370 days; deleted within seven days after use, withdrawal or expiry")}</li>
              <li>– {tr("minimierte Einwilligungsnachweise ohne E-Mail-Adresse der sorgeberechtigten Person: bis zu drei Jahre ab der jeweiligen Entscheidung", "Minimized consent records without the parent or guardian's email address: up to three years from each decision")}</li>
              <li>– {tr("interne technische Fehlerereignisse: höchstens 30 Tage", "Internal technical error events: no more than 30 days")}</li>
              <li>– {tr("Push-Zustellprotokolle: höchstens 90 Tage nach ihrer Erstellung", "Push-delivery logs: no more than 90 days after creation")}</li>
              <li>– {tr("direkte Support- und Feedbacknachrichten: solange sie für Bearbeitung und Nachvollziehbarkeit benötigt werden; bei Kontolöschung werden sie aus dem aktiven System entfernt. Eine kürzere automatische Regelfrist ist derzeit noch nicht technisch eingerichtet", "Direct support and feedback messages: for as long as needed to handle and document them; they are removed from the active system on account deletion. A shorter automatic standard period is not yet technically configured")}</li>
              <li>– {tr("personenbezogene Pilot-Auswertungsdaten: bis zum frühesten Zeitpunkt aus Widerruf, Kontolöschung, dokumentiertem Zweckende oder spätestens 365 Tage nach Speicherung im Evidenzmodell; bei Widerruf werden die personenbezogenen, pseudonymisierten Evidenzdaten unmittelbar aus der Pilot-Auswertung entfernt", "Personal pilot-evaluation data: until the earliest of withdrawal, account deletion, documented end of purpose or 365 days after storage in the evidence model; on withdrawal, personal pseudonymized evidence data is removed immediately from pilot evaluation")}</li>
              <li>– {tr("Feedback-Checkpoints, Produktfeedback-Kommentare und personenbeziehbare Analyseableitungen:", "Feedback checkpoints, product-feedback comments and person-related analysis derivatives:")} {feedbackEnabled ? tr("Produktfeedback-Kommentare und personenbeziehbare Ableitungen höchstens 365 Tage und früher bei Widerruf, Kontolöschung oder Zweckende; Auswahlantworten getrennt nach den für das Konto und die interne Produktverbesserung geltenden Fristen", "Product-feedback comments and person-related derivatives for no more than 365 days, or less if consent is withdrawn, the account is deleted or the purpose ends; multiple-choice answers are retained separately according to the periods applicable to the account and internal product improvement") : tr("nicht Teil dieser V1.1-Auslieferung; dafür werden in V1.1 keine Daten gespeichert", "not part of this V1.1 release; no data is stored for this in V1.1")}</li>
              <li>– {tr("abgelehnte, zurückgezogene oder nicht weiterverfolgte Team- und Organisationsanfragen: spätestens zwölf Monate nach Abschluss; bestätigte Fake- oder Spam-Anfragen können sofort vollständig gelöscht werden", "Rejected, withdrawn or abandoned team and organization inquiries: no later than twelve months after closure; confirmed fake or spam inquiries may be deleted immediately and completely")}</li>
              <li>– {tr("bei einer Zusammenarbeit: nur die für Organisation, Vertrag und laufende Betreuung erforderlichen Angaben nach den dafür geltenden gesetzlichen und vertraglichen Fristen; die ursprüngliche Anfrage wird nicht unbegrenzt als separater Interessenten-Datensatz weitergeführt", "If collaboration begins: only the data needed for organization, contract and ongoing support under the applicable legal and contractual periods; the original inquiry is not retained indefinitely as a separate prospect record")}</li>
              <li>– {tr("vollständig anonyme Aggregate: solange sie keinen Personenbezug mehr besitzen", "Fully anonymous aggregates: as long as they no longer relate to an identifiable person")}</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Auftragsverarbeiter", "Data processors")}</h2>
            <ul className="space-y-2">
              <li><span className="text-foreground">Supabase:</span> {tr("Authentifizierung, Datenbank und Edge Functions. Das bestätigte Hauptprojekt liegt in Frankfurt (eu-central-1). Technische Betriebs- und Sicherheitsdaten können nach Anbieterbedingungen und Auftragsverarbeitungsvertrag verarbeitet werden.", "Authentication, database and Edge Functions. The confirmed main project is located in Frankfurt (eu-central-1). Technical operational and security data may be processed under the provider terms and data-processing agreement.")}</li>
              <li><span className="text-foreground">Vercel:</span> {tr("Auslieferung der Website und Web-App. Dabei fallen technisch notwendige Anfrage- und Sicherheitsmetadaten an.", "Delivery of the website and web app. Technically necessary request and security metadata is generated in the process.")} {webAnalyticsEnabled ? tr("Für die öffentliche Website nutzen wir zusätzlich Vercel Web Analytics: cookie-freie, aggregierte Aufrufstatistiken zu Seiten, Referrern sowie groben Geräte-, Browser- und Regionsmerkmalen. Diese Daten werden nicht mit RewirePerform-Konten oder Produktdaten verknüpft und nicht für Werbung, individualisierte Profile oder automatisierte Entscheidungen eingesetzt.", "For the public website, we also use Vercel Web Analytics: cookie-free, aggregated visit statistics for pages, referrers and broad device, browser and region characteristics. These data are not linked to RewirePerform accounts or product data and are not used for advertising, individualized profiles or automated decisions.") : ""} {tr("Soweit Daten außerhalb des EWR verarbeitet werden, stützt sich der Anbieter unter anderem auf die vereinbarten Standardvertragsklauseln.", "Where data is processed outside the EEA, the provider relies, among other safeguards, on the agreed standard contractual clauses.")}</li>
              <li><span className="text-foreground">Cloudflare Turnstile:</span> {tr("Missbrauchsschutz für das öffentliche Team- und Organisationsformular. Dabei werden ausschließlich die für die Sicherheitsprüfung notwendigen technischen Anfrage- und Gerätedaten verarbeitet; Turnstile wird nicht für Werbung, Nutzerprofile oder appübergreifendes Tracking eingesetzt.", "Abuse protection for the public team and organization form. Only technical request and device data needed for the security check are processed; Turnstile is not used for advertising, user profiles or cross-app tracking.")}</li>
              <li><span className="text-foreground">Resend:</span> {tr("ausschließlich für transaktionale E-Mails an sorgeberechtigte Personen sowie für nach persönlicher Freigabe versendete Coach-Zugänge. Verarbeitet werden Empfängeradresse, Nachrichteninhalt einschließlich eines einmaligen persönlichen Zugangslinks und Zustellmetadaten. Die per E-Mail versendete Coach-Einladung ist an diese E-Mail-Adresse gebunden, einmalig und sieben Tage gültig. Öffnungs- und Link-Tracking werden für diesen Versand nicht genutzt.", "used exclusively for transactional emails to parents or guardians and for coach access sent after personal approval. The recipient address, message content including a one-time personal access link, and delivery metadata are processed. An emailed coach invitation is bound to that email address, can be used once and is valid for seven days. Open and link tracking are not used for these emails.")}</li>
              <li><span className="text-foreground">{tr("Co-Coach-Teamlink:", "Co-coach team link:")}</span> {tr("Der Lead Coach teilt den im geschützten RewirePerform-System geführten Teamlink über einen selbst gewählten Kanal. Er wird nicht über Resend versendet, bleibt bis zu seiner Erneuerung aktiv und kann ein neues, eigenes Coach-Konto nur einmal mit diesem Team verbinden.", "The lead coach shares the team link held in RewirePerform's protected system through a channel of their choice. It is not sent via Resend, remains active until renewed, and can link a new individual coach account to this team only once.")}</li>
              <li><span className="text-foreground">{tr("Push-Infrastruktur:", "Push infrastructure:")}</span> {tr("Browser- beziehungsweise Betriebssystemanbieter transportieren optionale Benachrichtigungen. Private Journal- oder Antwortinhalte werden nicht in Push-Nachrichten aufgenommen.", "Browser or operating-system providers deliver optional notifications. Private journal or answer content is not included in push messages.")}</li>
            </ul>
            <p className="mt-3">
              {feedbackEnabled
                ? tr("Ausdrücklich freigegebene Produktfeedback-Kommentare sind ausschließlich in einer geschützten, pseudonymisierten und nur lesenden Admin-Ansicht zugänglich. Das intern und lokal betriebene Jarvis-System darf ausschließlich pseudonymisierte Auswahlantworten und minimierte Aktivitätszahlen kurzzeitig im Arbeitsspeicher verarbeiten, um Gruppenzusammenfassungen pro Frage ab fünf unterschiedlichen Teilnehmenden zu bilden. Die pseudonymen Referenzen werden weder im Ergebnis ausgegeben noch dauerhaft gespeichert. Jarvis erhält keine Produktfeedback-Kommentare. Namen, E-Mail-Adressen und direkte Nutzerkennungen bleiben ausgeschlossen. Journale, private Reflexionen, Supporttexte sowie Team- und Coach-IDs bleiben ausgeschlossen. Die Daten werden nicht zum Trainieren eines KI-Modells und nicht für automatisierte Einzelentscheidungen verwendet.", "Explicitly authorized product-feedback comments are accessible only in a protected, pseudonymized, read-only admin view. The internally and locally operated Jarvis system may briefly process only pseudonymized multiple-choice answers and minimized activity counts in memory to create group summaries per question from at least five different participants. Pseudonymous references are neither output in the result nor stored permanently. Jarvis receives no product-feedback comments. Names, email addresses and direct user identifiers remain excluded. Journals, private reflections, support texts, team IDs and coach IDs remain excluded. The data is not used to train an AI model or for automated decisions about individuals.")
                : tr("Feedback Intelligence und ein Jarvis-Zugriff sind nicht Teil dieser V1.1-Auslieferung. Es gibt dafür keinen Produktdatenexport, keinen Reader und keine Verarbeitung von Athletendaten.", "Feedback Intelligence and Jarvis access are not part of this V1.1 release. There is no product-data export, reader or processing of athlete data for this purpose.")}
            </p>
            <p className="mt-3">
              {feedbackEnabled
                ? tr("Kein externer KI-Anbieter erhält Produktfeedbackdaten oder -kommentare. Eine spätere externe Übermittlung oder Jarvis-Freitextanalyse erfordert eine neue konkrete Information, eine neue Empfängerprüfung und, soweit erforderlich, eine neue Einwilligung.", "No external AI provider receives product-feedback data or comments. Any future external transfer or Jarvis free-text analysis requires new specific information, a new recipient assessment and, where required, new consent.")
                : tr("Kein externer KI-Anbieter erhält in V1.1 Produktdaten. Vor einer späteren Änderung werden konkreter Empfänger, Verarbeitungsort, Schutzgrundlage und die notwendige Einwilligungsinformation getrennt benannt und geprüft.", "No external AI provider receives product data in V1.1. Before any later change, the specific recipient, processing location, legal safeguard and necessary consent information will be identified and assessed separately.")}
            </p>
            <p className="mt-3">{tr("Es findet keine Weitergabe an Werbenetzwerke oder Datenhändler statt. Sentry ist nicht mehr mit der App verbunden und erhält keine neuen App-Ereignisse.", "No data is shared with advertising networks or data brokers. Sentry is no longer connected to the app and receives no new app events.")}</p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Benachrichtigungen", "Notifications")}</h2>
            <p>
              {tr("Push-Benachrichtigungen sind optional. Wenn du sie aktivierst, speichern wir nur eine technische Push-Berechtigung und deine gewählten Erinnerungszeiten. In der iOS- beziehungsweise Android-App wird zusätzlich ein technischer APNs- beziehungsweise FCM-Gerätetoken gespeichert, damit wir dir aktivierte Erinnerungen und teambezogene Programmhinweise zustellen können. Der Token enthält weder deinen Namen noch Antworten, Journaltexte oder Standortdaten und wird beim Deaktivieren der Benachrichtigungen oder beim Löschen deines Accounts entfernt.", "Push notifications are optional. If you enable them, we store only a technical push permission and your chosen reminder times. In the iOS or Android app, a technical APNs or FCM device token is also stored so we can deliver enabled reminders and team-related program notices. The token contains neither your name nor answers, journal text or location data, and is removed when notifications are disabled or your account is deleted.")}
            </p>
            <p className="mt-3">
              {tr("Für den zuverlässigen Versand speichern wir außerdem Benachrichtigungstyp, Versanddatum, Versandstatus sowie gegebenenfalls Öffnungszeitpunkt und Fehlerzeitpunkt. Diese Angaben dienen ausschließlich Zustellung, Fehlerbehebung und der von dir geöffneten Zielseite. Ein Coach kann einmal am Tag eine feste, freundliche Erinnerung an noch offene Check-ins seines Teams auslösen; dabei werden ausschließlich der offene Abschlussstatus und technische Zustellinformationen verwendet. Private Journal- oder Antwortinhalte werden weder protokolliert noch in Benachrichtigungen aufgenommen.", "For reliable delivery, we also store notification type, send date, delivery status and, where applicable, opening and error times. These details are used only for delivery, troubleshooting and the destination page you open. Once per day, a coach may trigger a fixed, friendly reminder about outstanding team check-ins; only outstanding completion status and technical delivery information are used. Private journal or answer content is neither logged nor included in notifications.")}
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Keine Diagnose", "No diagnosis")}</h2>
            <p>
              {tr("RewirePerform ist ein Performance- und Reflexionssystem. Die App stellt keine medizinische Diagnose, ersetzt keine Behandlung und ist nicht für akute psychische Krisen gedacht.", "RewirePerform is a performance and reflection system. The app does not provide a medical diagnosis, replace treatment or serve acute mental-health crises.")}
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground mb-2">{tr("Kontakt", "Contact")}</h2>
            <p>
              {tr("Für Datenschutz-, Widerrufs- oder Auskunftsanfragen:", "For privacy, withdrawal or access requests:")}{" "}
              <a href={SUPPORT_MAILTO} className="text-primary hover:underline">
                {SUPPORT_EMAIL}
              </a>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
};

export default Privacy;
