/**
 * 56-Tage-Skelett — Matrixdefinition aller Tage.
 *
 * Quelle: definiertes Master-Skelett (Phase I–IV).
 * Diese Datei darf NICHT von der KI geändert werden.
 * Inhalte (Tasks/Journal/Science Bite) liegen in dailyContent.ts.
 */

import type { MatrixDay } from "./matrixDayTypes";

export const MATRIX_DAYS: MatrixDay[] = [
  // ─────────── PHASE I — SICHTBAR WERDEN ───────────
  // Woche 1
  {
    dayNumber: 1, phase: 1, week: 1,
    lens: "Präsenz statt Autopilot",
    primaryMechanism: "Attentional Control",
    secondaryAxes: ["Presence vs Outcome", "Process vs Result"],
    practiceFocus: "Wegdriften bemerken",
    knowledgeLevel: "K4",
    dayRole: "Erster Zugang zur inneren Verfügbarkeit",
    systemFunction: "Seed",
    recurrenceType: "Grundöffnung",
  },
  {
    dayNumber: 2, phase: 1, week: 1,
    lens: "Der Fehler ist nicht das Problem",
    primaryMechanism: "Metacognitive Defusion",
    secondaryAxes: ["Learning vs Judgement", "Confidence vs Self-Doubt"],
    practiceFocus: "Erste innere Sätze nach Fehlern erkennen",
    knowledgeLevel: "K4",
    dayRole: "Fehler als inneres Ereignis sichtbar machen",
    systemFunction: "Seed",
    recurrenceType: "Grundöffnung",
  },
  {
    dayNumber: 3, phase: 1, week: 1,
    lens: "Was du bewertest, steuert dich",
    primaryMechanism: "Threat-to-Challenge Reappraisal",
    secondaryAxes: ["Fear vs Love", "Control vs Non-Control"],
    practiceFocus: "Bedeutung belastender Situationen erkennen",
    knowledgeLevel: "K4",
    dayRole: "Bewertung als Zustandshebel sichtbar machen",
    systemFunction: "Seed",
    recurrenceType: "Grundöffnung",
  },
  {
    dayNumber: 4, phase: 1, week: 1,
    lens: "Kontrolle beginnt mit Loslassen",
    primaryMechanism: "Acceptance-based Cognitive Load Reduction",
    secondaryAxes: ["Control vs Non-Control", "Presence vs Outcome"],
    practiceFocus: "Energieverluste an Unsteuerbares erkennen",
    knowledgeLevel: "K4",
    dayRole: "Kontrollillusion angreifen",
    systemFunction: "Seed",
    recurrenceType: "Grundöffnung",
  },
  {
    dayNumber: 5, phase: 1, week: 1,
    lens: "Ego erkennen",
    primaryMechanism: "Self-referential Processing Awareness",
    secondaryAxes: ["Ego vs Inner Excellence", "Identity vs Performance"],
    practiceFocus: "Selbstbezogenheit im Training erkennen",
    knowledgeLevel: "K4",
    dayRole: "Selbstbild als Leistungsstörfaktor sichtbar machen",
    systemFunction: "Seed",
    recurrenceType: "Grundöffnung",
  },
  {
    dayNumber: 6, phase: 1, week: 1,
    lens: "Dankbarkeit erweitert Wahrnehmung",
    primaryMechanism: "Affective State Shaping",
    secondaryAxes: ["Gratitude vs Anxiety", "Fear vs Love"],
    practiceFocus: "Aufmerksamkeit von Mangel auf Vorhandenes erweitern",
    knowledgeLevel: "K4",
    dayRole: "Erste emotionale Weitung",
    systemFunction: "Seed",
    recurrenceType: "Grundöffnung",
  },
  {
    dayNumber: 7, phase: 1, week: 1,
    lens: "Die Woche in dir lesen",
    primaryMechanism: "Reflective Consolidation",
    secondaryAxes: ["Learning vs Judgement", "Identity vs Performance"],
    practiceFocus: "Muster der Woche erkennen",
    knowledgeLevel: "K4",
    dayRole: "Erste Konsolidierung",
    systemFunction: "Integrate",
    recurrenceType: "Wochenintegration",
  },
  // Woche 2
  {
    dayNumber: 8, phase: 1, week: 2,
    lens: "Wer willst du im Training sein?",
    primaryMechanism: "Identity Encoding Through Action",
    secondaryAxes: ["Identity vs Performance", "Confidence vs Self-Doubt"],
    practiceFocus: "Gewünschte Version von sich vor dem Training definieren",
    knowledgeLevel: "K4",
    dayRole: "Erste Identitätslinie setzen",
    systemFunction: "Seed",
    recurrenceType: "Grundöffnung",
  },
  {
    dayNumber: 9, phase: 1, week: 2,
    lens: "Angst ist oft Bewertung",
    primaryMechanism: "Threat Appraisal Awareness",
    secondaryAxes: ["Fear vs Love", "Growth vs Winning"],
    practiceFocus: "Druck als innere Lesart erkennen",
    knowledgeLevel: "K4",
    dayRole: "Fear-Linie vorbereiten",
    systemFunction: "Return",
    recurrenceType: "frühe Rückkopplung",
  },
  {
    dayNumber: 10, phase: 1, week: 2,
    lens: "Confidence ist keine Stimmung",
    primaryMechanism: "Self-efficacy Framing",
    secondaryAxes: ["Confidence vs Self-Doubt", "Process vs Result"],
    practiceFocus: "Confidence als handlungsgebunden statt gefühlsgebunden verstehen",
    knowledgeLevel: "K4",
    dayRole: "Confidence neu definieren",
    systemFunction: "Seed",
    recurrenceType: "Grundöffnung",
  },
  {
    dayNumber: 11, phase: 1, week: 2,
    lens: "Lernen braucht Unsicherheit",
    primaryMechanism: "Prediction Error / Exploration",
    secondaryAxes: ["Growth vs Winning", "Learning vs Judgement"],
    practiceFocus: "Etwas bewusst Neues oder Unsicheres tun",
    knowledgeLevel: "K4",
    dayRole: "Growth-Linie eröffnen",
    systemFunction: "Seed",
    recurrenceType: "Grundöffnung",
  },
  {
    dayNumber: 12, phase: 1, week: 2,
    lens: "Exzellenz ist nicht Selbstdarstellung",
    primaryMechanism: "Value-based Attention Shift",
    secondaryAxes: ["Ego vs Inner Excellence", "Fear vs Love"],
    practiceFocus: "Qualität über Wirkung stellen",
    knowledgeLevel: "K4",
    dayRole: "Ego-Linie vertiefen",
    systemFunction: "Return",
    recurrenceType: "frühe Rückkopplung",
  },
  {
    dayNumber: 13, phase: 1, week: 2,
    lens: "Gedanken sind Ereignisse, keine Befehle",
    primaryMechanism: "Metacognitive Labeling",
    secondaryAxes: ["Learning vs Judgement", "Confidence vs Self-Doubt"],
    practiceFocus: "Gedanken benennen statt automatisch folgen",
    knowledgeLevel: "K4",
    dayRole: "Defusion-Linie vertiefen",
    systemFunction: "Deepen",
    recurrenceType: "erste Vertiefung",
  },
  {
    dayNumber: 14, phase: 1, week: 2,
    lens: "Ergebnisdenken raubt Gegenwart",
    primaryMechanism: "Outcome Detachment",
    secondaryAxes: ["Process vs Result", "Presence vs Outcome"],
    practiceFocus: "Vor und nach Aktionen Prozess statt Ergebnis priorisieren",
    knowledgeLevel: "K4",
    dayRole: "Process-Linie eröffnen",
    systemFunction: "Seed",
    recurrenceType: "Grundöffnung",
  },

  // ─────────── PHASE II — UMCODIEREN ───────────
  // Woche 3
  {
    dayNumber: 15, phase: 2, week: 3,
    lens: "Präsenz aktiv zurückholen",
    primaryMechanism: "Re-engagement of Task Attention",
    secondaryAxes: ["Presence vs Outcome", "Control vs Non-Control"],
    practiceFocus: "Klaren Reset-Trigger im Training nutzen",
    knowledgeLevel: "K3",
    dayRole: "Presence von Beobachtung zu Handlung verschieben",
    systemFunction: "Convert",
    recurrenceType: "erste Umcodierung",
  },
  {
    dayNumber: 16, phase: 2, week: 3,
    lens: "Für etwas Größeres handeln",
    primaryMechanism: "Meaning-based Motivation",
    secondaryAxes: ["Fear vs Love", "Ego vs Inner Excellence"],
    practiceFocus: "Einen team- oder sinnbezogenen Grund setzen",
    knowledgeLevel: "K3",
    dayRole: "Fear-/Ego-Linie motivational umlenken",
    systemFunction: "Convert",
    recurrenceType: "erste Umcodierung",
  },
  {
    dayNumber: 17, phase: 2, week: 3,
    lens: "Beweise formen Selbstbild",
    primaryMechanism: "Identity Encoding Through Repetition",
    secondaryAxes: ["Identity vs Performance", "Confidence vs Self-Doubt"],
    practiceFocus: "Verhaltensbeweise sammeln",
    knowledgeLevel: "K3",
    dayRole: "Identität aus Verhalten bauen",
    systemFunction: "Convert",
    recurrenceType: "erste Umcodierung",
  },
  {
    dayNumber: 18, phase: 2, week: 3,
    lens: "Wachstum beginnt dort, wo du unsicher wirst",
    primaryMechanism: "Prediction Error Reinforcement",
    secondaryAxes: ["Growth vs Winning", "Fear vs Love"],
    practiceFocus: "Sichtbare Unsicherheit bewusst wählen",
    knowledgeLevel: "K3",
    dayRole: "Growth in Handlung übersetzen",
    systemFunction: "Convert",
    recurrenceType: "erste Umcodierung",
  },
  {
    dayNumber: 19, phase: 2, week: 3,
    lens: "Nicht kontrollierbar heißt nicht bedrohlich",
    primaryMechanism: "Acceptance-based Regulation",
    secondaryAxes: ["Control vs Non-Control", "Gratitude vs Anxiety"],
    practiceFocus: "Äußere Umstände nicht emotional aufladen",
    knowledgeLevel: "K3",
    dayRole: "Kontrolllinie vertiefen",
    systemFunction: "Deepen",
    recurrenceType: "erste Vertiefung",
  },
  {
    dayNumber: 20, phase: 2, week: 3,
    lens: "Fehler ohne Selbstangriff",
    primaryMechanism: "Defusion under Performance Feedback",
    secondaryAxes: ["Learning vs Judgement", "Confidence vs Self-Doubt"],
    practiceFocus: "Fehler dokumentieren ohne Identitätsangriff",
    knowledgeLevel: "K3",
    dayRole: "Judgement-Linie in reale Reaktion übertragen",
    systemFunction: "Convert",
    recurrenceType: "erste Umcodierung",
  },
  {
    dayNumber: 21, phase: 2, week: 3,
    lens: "Team vor Selbstbild",
    primaryMechanism: "Reduction of Self-referential Priority",
    secondaryAxes: ["Ego vs Inner Excellence", "Fear vs Love"],
    practiceFocus: "Teamdienliche Handlung statt imageorientierter Handlung",
    knowledgeLevel: "K3",
    dayRole: "Ego-Linie sozial verschieben",
    systemFunction: "Convert",
    recurrenceType: "erste Umcodierung",
  },
  // Woche 4
  {
    dayNumber: 22, phase: 2, week: 4,
    lens: "Prozess als Heimat",
    primaryMechanism: "Process Anchoring",
    secondaryAxes: ["Process vs Result", "Presence vs Outcome"],
    practiceFocus: "Pro Einheit klaren Prozessanker definieren",
    knowledgeLevel: "K3",
    dayRole: "Prozesslinie stabilisieren",
    systemFunction: "Deepen",
    recurrenceType: "erste Vertiefung",
  },
  {
    dayNumber: 23, phase: 2, week: 4,
    lens: "Dankbarkeit als Leistungszustand",
    primaryMechanism: "Positive Attentional Broadening",
    secondaryAxes: ["Gratitude vs Anxiety", "Fear vs Love"],
    practiceFocus: "Möglichkeit statt Mangel vor Training sehen",
    knowledgeLevel: "K3",
    dayRole: "Gratitude-Linie leistungsnah machen",
    systemFunction: "Convert",
    recurrenceType: "erste Umcodierung",
  },
  {
    dayNumber: 24, phase: 2, week: 4,
    lens: "Präsenz trotz Müdigkeit oder Unlust",
    primaryMechanism: "Attentional Stability under Low Motivation",
    secondaryAxes: ["Presence vs Outcome", "Voluntary Discomfort"],
    practiceFocus: "Fokus halten, wenn keine innere Lust da ist",
    knowledgeLevel: "K3",
    dayRole: "Presence unter niedriger Energie testen",
    systemFunction: "Stress-Test",
    recurrenceType: "erste Belastung",
  },
  {
    dayNumber: 25, phase: 2, week: 4,
    lens: "Handeln trotz Zweifel",
    primaryMechanism: "Action Before Confidence",
    secondaryAxes: ["Confidence vs Self-Doubt", "Identity vs Performance"],
    practiceFocus: "Nicht auf Gefühl warten, sondern handeln",
    knowledgeLevel: "K3",
    dayRole: "Confidence verhaltensbasiert machen",
    systemFunction: "Convert",
    recurrenceType: "erste Umcodierung",
  },
  {
    dayNumber: 26, phase: 2, week: 4,
    lens: "Gegner nicht fürchten, sondern ehren",
    primaryMechanism: "Fear-to-Respect Conversion",
    secondaryAxes: ["Fear vs Love", "Ego vs Inner Excellence"],
    practiceFocus: "Starke Gegner als Exzellenzreiz lesen",
    knowledgeLevel: "K3",
    dayRole: "Fear-Linie leistungsnah verschieben",
    systemFunction: "Deepen",
    recurrenceType: "erste Vertiefung",
  },
  {
    dayNumber: 27, phase: 2, week: 4,
    lens: "Scheitern bewusst riskieren",
    primaryMechanism: "Voluntary Exposure to Uncertainty",
    secondaryAxes: ["Growth vs Winning", "Learning vs Judgement"],
    practiceFocus: "Kalkuliertes Scheitern in Kauf nehmen",
    knowledgeLevel: "K3",
    dayRole: "Growth mit Reibung koppeln",
    systemFunction: "Stress-Test",
    recurrenceType: "erste Belastung",
  },
  {
    dayNumber: 28, phase: 2, week: 4,
    lens: "Unkontrollierbares im Wettkampfkontext",
    primaryMechanism: "Regulation under External Unfairness",
    secondaryAxes: ["Control vs Non-Control", "Process vs Result"],
    practiceFocus: "Schiri, Rolle, Gegner, Umstände funktional behandeln",
    knowledgeLevel: "K3",
    dayRole: "Kontrolllinie transferfähig machen",
    systemFunction: "Transfer",
    recurrenceType: "erste Leistungsübertragung",
  },

  // ─────────── PHASE III — TRAGEN UNTER REIBUNG ───────────
  // Woche 5
  {
    dayNumber: 29, phase: 3, week: 5,
    lens: "So handeln, wenn es zählt",
    primaryMechanism: "Identity Under Pressure",
    secondaryAxes: ["Identity vs Performance", "Confidence vs Self-Doubt"],
    practiceFocus: "Gewünschtes Verhalten unter erhöhter Bedeutung leben",
    knowledgeLevel: "K2",
    dayRole: "Identitätslinie unter Druck testen",
    systemFunction: "Stress-Test",
    recurrenceType: "Druckanwendung",
  },
  {
    dayNumber: 30, phase: 3, week: 5,
    lens: "Prozess unter Ergebnisdruck halten",
    primaryMechanism: "Outcome Pressure Buffering",
    secondaryAxes: ["Process vs Result", "Presence vs Outcome"],
    practiceFocus: "In wichtigen Momenten bei der Aufgabe bleiben",
    knowledgeLevel: "K2",
    dayRole: "Prozesslinie unter Druck testen",
    systemFunction: "Transfer",
    recurrenceType: "Leistungsübertragung",
  },
  {
    dayNumber: 31, phase: 3, week: 5,
    lens: "Nach Fehler nicht ins Ich kippen",
    primaryMechanism: "Self-reference Interruption",
    secondaryAxes: ["Ego vs Inner Excellence", "Learning vs Judgement"],
    practiceFocus: "Fehler nicht in Bildverteidigung übersetzen",
    knowledgeLevel: "K2",
    dayRole: "Ego-Linie im Fehlermoment testen",
    systemFunction: "Stress-Test",
    recurrenceType: "Druckanwendung",
  },
  {
    dayNumber: 32, phase: 3, week: 5,
    lens: "Lernen unter fremder Bewertung",
    primaryMechanism: "Defusion under Social Evaluation",
    secondaryAxes: ["Learning vs Judgement", "Fear vs Love"],
    practiceFocus: "Beobachtung und Bewertung aushalten ohne zu kippen",
    knowledgeLevel: "K2",
    dayRole: "Judgement-Linie sozial belasten",
    systemFunction: "Stress-Test",
    recurrenceType: "soziale Reibung",
  },
  {
    dayNumber: 33, phase: 3, week: 5,
    lens: "Gegen alte Muster entscheiden",
    primaryMechanism: "Response Inhibition + Replacement",
    secondaryAxes: ["Control vs Non-Control", "Confidence vs Self-Doubt"],
    practiceFocus: "Alten Reflex bewusst stoppen und ersetzen",
    knowledgeLevel: "K2",
    dayRole: "Aktive Umcodierung unter Spannung",
    systemFunction: "Convert",
    recurrenceType: "fortgeschrittene Umcodierung",
  },
  {
    dayNumber: 34, phase: 3, week: 5,
    lens: "Dankbarkeit im Belastungsmodus",
    primaryMechanism: "State Recovery During Load",
    secondaryAxes: ["Gratitude vs Anxiety", "Presence vs Outcome"],
    practiceFocus: "Weite im Schweren erzeugen",
    knowledgeLevel: "K2",
    dayRole: "Gratitude-Linie belastbar machen",
    systemFunction: "Deepen",
    recurrenceType: "Belastungsvertiefung",
  },
  {
    dayNumber: 35, phase: 3, week: 5,
    lens: "Verantwortung sichtbar übernehmen",
    primaryMechanism: "Confidence Through Public Action",
    secondaryAxes: ["Confidence vs Self-Doubt", "Ego vs Inner Excellence"],
    practiceFocus: "Initiative zeigen trotz möglicher Bewertung",
    knowledgeLevel: "K2",
    dayRole: "Confidence öffentlich machen",
    systemFunction: "Transfer",
    recurrenceType: "soziale Übertragung",
  },
  // Woche 6
  {
    dayNumber: 36, phase: 3, week: 6,
    lens: "Präsenz im Chaos",
    primaryMechanism: "Attention under Pressure and Noise",
    secondaryAxes: ["Presence vs Outcome", "Fear vs Love"],
    practiceFocus: "In Hektik, Lautstärke und Fehlerketten verfügbar bleiben",
    knowledgeLevel: "K2",
    dayRole: "Presence unter Chaos testen",
    systemFunction: "Stress-Test",
    recurrenceType: "Belastungsanwendung",
  },
  {
    dayNumber: 37, phase: 3, week: 6,
    lens: "Gelassenheit unter unfairen Umständen",
    primaryMechanism: "Emotional Regulation Through Acceptance",
    secondaryAxes: ["Control vs Non-Control", "Process vs Result"],
    practiceFocus: "Äußere Unfairness nicht weiter füttern",
    knowledgeLevel: "K2",
    dayRole: "Control-Linie unter Frust vertiefen",
    systemFunction: "Stress-Test",
    recurrenceType: "Belastungsanwendung",
  },
  {
    dayNumber: 38, phase: 3, week: 6,
    lens: "Angriff statt Schutz",
    primaryMechanism: "Challenge Orientation",
    secondaryAxes: ["Fear vs Love", "Growth vs Winning"],
    practiceFocus: "In Spannung nach vorne orientiert bleiben",
    knowledgeLevel: "K2",
    dayRole: "Fear-Linie in Challenge-Modus überführen",
    systemFunction: "Convert",
    recurrenceType: "fortgeschrittene Umcodierung",
  },
  {
    dayNumber: 39, phase: 3, week: 6,
    lens: "Stabil trotz Spielverlauf",
    primaryMechanism: "State Independence from Outcome Momentum",
    secondaryAxes: ["Process vs Result", "Confidence vs Self-Doubt"],
    practiceFocus: "Bei gutem oder schlechtem Verlauf gleich funktional bleiben",
    knowledgeLevel: "K2",
    dayRole: "Ergebnisunabhängigkeit testen",
    systemFunction: "Stress-Test",
    recurrenceType: "Leistungsanwendung",
  },
  {
    dayNumber: 40, phase: 3, week: 6,
    lens: "Wachstum trotz Ergebnisdruck",
    primaryMechanism: "Learning Preservation under Evaluation",
    secondaryAxes: ["Growth vs Winning", "Learning vs Judgement"],
    practiceFocus: "Auch unter Bewertung noch lernoffen handeln",
    knowledgeLevel: "K2",
    dayRole: "Growth-Linie unter Druck stabilisieren",
    systemFunction: "Transfer",
    recurrenceType: "Leistungsübertragung",
  },
  {
    dayNumber: 41, phase: 3, week: 6,
    lens: "Identität trotz Fehlern",
    primaryMechanism: "Identity Stability under Imperfection",
    secondaryAxes: ["Identity vs Performance", "Confidence vs Self-Doubt"],
    practiceFocus: "Fehler nicht mit eigenem Wert verwechseln",
    knowledgeLevel: "K2",
    dayRole: "Identitätslinie gegen Imperfektion absichern",
    systemFunction: "Deepen",
    recurrenceType: "Belastungsvertiefung",
  },
  {
    dayNumber: 42, phase: 3, week: 6,
    lens: "Was in dir bleibt, wenn Druck steigt",
    primaryMechanism: "Consolidation Check under Load",
    secondaryAxes: ["mehrere Hauptachsen leicht mitlaufend"],
    practiceFocus: "Rückblick auf stabile und instabile Muster unter Druck",
    knowledgeLevel: "K2",
    dayRole: "Erste große Belastungskonsolidierung",
    systemFunction: "Integrate",
    recurrenceType: "Druckintegration",
  },

  // ─────────── PHASE IV — VERKÖRPERN ───────────
  // Woche 7
  {
    dayNumber: 43, phase: 4, week: 7,
    lens: "Präsenz als Standard",
    primaryMechanism: "Automatic Attentional Return",
    secondaryAxes: ["Presence vs Outcome", "Process vs Result"],
    practiceFocus: "Fokus nicht suchen, sondern direkt wiederfinden",
    knowledgeLevel: "K1",
    dayRole: "Presence in Default überführen",
    systemFunction: "Integrate",
    recurrenceType: "Verkörperung",
  },
  {
    dayNumber: 44, phase: 4, week: 7,
    lens: "Demut in Stärke",
    primaryMechanism: "Low-ego Performance Orientation",
    secondaryAxes: ["Ego vs Inner Excellence", "Fear vs Love"],
    practiceFocus: "Hohe Qualität ohne Beweisdrang",
    knowledgeLevel: "K1",
    dayRole: "Ego-Linie identitätsnah verdichten",
    systemFunction: "Integrate",
    recurrenceType: "Verkörperung",
  },
  {
    dayNumber: 45, phase: 4, week: 7,
    lens: "Dankbarkeit ohne Anlass",
    primaryMechanism: "Baseline State Shaping",
    secondaryAxes: ["Gratitude vs Anxiety", "Identity vs Performance"],
    practiceFocus: "Nicht nur auf äußere gute Momente reagieren",
    knowledgeLevel: "K1",
    dayRole: "Gratitude als Grundzustand stabilisieren",
    systemFunction: "Integrate",
    recurrenceType: "Verkörperung",
  },
  {
    dayNumber: 46, phase: 4, week: 7,
    lens: "Urteil verliert Macht",
    primaryMechanism: "Deep Defusion",
    secondaryAxes: ["Learning vs Judgement", "Confidence vs Self-Doubt"],
    practiceFocus: "Bewertung weniger tief eindringen lassen",
    knowledgeLevel: "K1",
    dayRole: "Judgement-Linie tief verankern",
    systemFunction: "Integrate",
    recurrenceType: "Verkörperung",
  },
  {
    dayNumber: 47, phase: 4, week: 7,
    lens: "Ruhige Sicherheit",
    primaryMechanism: "Stable Confidence Encoding",
    secondaryAxes: ["Confidence vs Self-Doubt", "Process vs Result"],
    practiceFocus: "Sicherheit ruhig und funktionsbezogen halten",
    knowledgeLevel: "K1",
    dayRole: "Confidence von Stimmung lösen",
    systemFunction: "Integrate",
    recurrenceType: "Verkörperung",
  },
  {
    dayNumber: 48, phase: 4, week: 7,
    lens: "Akzeptanz als Stärke",
    primaryMechanism: "Non-reactive Control",
    secondaryAxes: ["Control vs Non-Control", "Presence vs Outcome"],
    practiceFocus: "Loslassen ohne Kraftverlust",
    knowledgeLevel: "K1",
    dayRole: "Control-Linie verkörpern",
    systemFunction: "Integrate",
    recurrenceType: "Verkörperung",
  },
  {
    dayNumber: 49, phase: 4, week: 7,
    lens: "Präsenz ist jetzt Teil von dir",
    primaryMechanism: "Identity-linked Attention Pattern",
    secondaryAxes: ["Identity vs Performance", "Presence vs Outcome"],
    practiceFocus: "Präsenz als Teil des Selbstbilds erleben",
    knowledgeLevel: "K1",
    dayRole: "Presence + Identity fusionieren",
    systemFunction: "Integrate",
    recurrenceType: "Identitätsintegration",
  },
  // Woche 8
  {
    dayNumber: 50, phase: 4, week: 8,
    lens: "Prozess als Heimat unter allem",
    primaryMechanism: "Deep Process Attachment",
    secondaryAxes: ["Process vs Result", "Fear vs Love"],
    practiceFocus: "Unter wechselnden äußeren Zuständen im Prozess bleiben",
    knowledgeLevel: "K1",
    dayRole: "Prozesslinie final verdichten",
    systemFunction: "Integrate",
    recurrenceType: "Identitätsintegration",
  },
  {
    dayNumber: 51, phase: 4, week: 8,
    lens: "Weite statt Bedrohung",
    primaryMechanism: "Anxiety Buffering through Gratitude and Meaning",
    secondaryAxes: ["Gratitude vs Anxiety", "Fear vs Love"],
    practiceFocus: "Auch in Spannung offen bleiben",
    knowledgeLevel: "K1",
    dayRole: "Anxiety-Linie in Weite überführen",
    systemFunction: "Integrate",
    recurrenceType: "Identitätsintegration",
  },
  {
    dayNumber: 52, phase: 4, week: 8,
    lens: "Liebe/Purpose als Performance State",
    primaryMechanism: "Meaning-driven High Performance Mode",
    secondaryAxes: ["Fear vs Love", "Ego vs Inner Excellence"],
    practiceFocus: "Für Team, Aufgabe und Beitrag handeln",
    knowledgeLevel: "K1",
    dayRole: "Fear-/Ego-Linien final motivational umlenken",
    systemFunction: "Integrate",
    recurrenceType: "Identitätsintegration",
  },
  {
    dayNumber: 53, phase: 4, week: 8,
    lens: "Wachstum als Default",
    primaryMechanism: "Automatic Growth Appraisal",
    secondaryAxes: ["Growth vs Winning", "Learning vs Judgement"],
    practiceFocus: "Reibung ohne Kampf als Wachstumsraum lesen",
    knowledgeLevel: "K1",
    dayRole: "Growth-Linie automatisieren",
    systemFunction: "Integrate",
    recurrenceType: "Identitätsintegration",
  },
  {
    dayNumber: 54, phase: 4, week: 8,
    lens: "Confidence ohne äußeren Beweis",
    primaryMechanism: "Internalized Self-efficacy",
    secondaryAxes: ["Confidence vs Self-Doubt", "Identity vs Performance"],
    practiceFocus: "Selbstbild nicht an Tagesform hängen",
    knowledgeLevel: "K1",
    dayRole: "Confidence-Linie final internalisieren",
    systemFunction: "Integrate",
    recurrenceType: "Identitätsintegration",
  },
  {
    dayNumber: 55, phase: 4, week: 8,
    lens: "Exzellenz ohne Ego",
    primaryMechanism: "Mastery Orientation",
    secondaryAxes: ["Ego vs Inner Excellence", "Process vs Result"],
    practiceFocus: "Höchste Qualität, geringste Selbstbesessenheit",
    knowledgeLevel: "K1",
    dayRole: "Ego-, Prozess- und Exzellenzlinien final verschmelzen",
    systemFunction: "Integrate",
    recurrenceType: "Identitätsintegration",
  },
  {
    dayNumber: 56, phase: 4, week: 8,
    lens: "Ich bin nicht hier, um zu beweisen — ich bin hier, um zu werden",
    primaryMechanism: "Global Integration / Identity Consolidation",
    secondaryAxes: ["alle Hauptachsen verdichtet"],
    practiceFocus: "Abschluss, Verdichtung, Zukunftsanker",
    knowledgeLevel: "K1",
    dayRole: "Gesamtsystem in Selbstbild überführen",
    systemFunction: "Integrate",
    recurrenceType: "Gesamtkonsolidierung",
  },
];

export const getMatrixDay = (dayNumber: number): MatrixDay | null =>
  MATRIX_DAYS.find((d) => d.dayNumber === dayNumber) ?? null;
