/**
 * Player-Format Tagesinhalte (Maximum-Qualität).
 *
 * Snake_case Autor-Format. Wird über `mapPlayerDayToDailyContent` ins
 * camelCase `DailyContent`-Schema übersetzt und in dailyContent.ts injiziert.
 *
 * Felder folgen dem mit dem User abgestimmten Tag-10-Niveau:
 *   - lens, today_trigger, core_shift, science_bite
 *   - 3 Tasks (trigger, when_to_use, action, why, explanation,
 *     self_talk, micro_reframe, reframe_step, system_function, icon)
 *   - journal (4 Fragen + gratitude_instruction + free_reflection_prompt)
 *   - self_talk_anchors (mit when), variants (training/rest/match)
 */

import type { DailyContent, DailyTask } from "./matrixDayTypes";

export interface PlayerTask {
  id: string;
  title: string;
  trigger: string;
  when_to_use: string;
  action: string;
  why: string;
  explanation: string;
  self_talk: string;
  micro_reframe: string;
  reframe_step: { trigger: string; reframe: string; anchor: string };
  system_function: string;
  icon: string;
}

export interface PlayerJournal {
  title: string;
  questions: { id: string; question: string; placeholder?: string }[];
  gratitude_instruction: string;
  free_reflection_prompt?: string;
}

export interface PlayerDay {
  day_id: number;
  title: string;
  phase: string;
  week: number;
  line: string;
  lens: string;
  primary_mechanism: string;
  today_trigger: string;
  core_shift: string;
  science_bite: string;
  tasks: PlayerTask[];
  journal: PlayerJournal;
  gratitude_prompt: string;
  self_talk_anchors: { text: string; when: string }[];
  variants: { training: string; rest: string; match: string };
}

const mapTask = (t: PlayerTask): DailyTask => ({
  id: t.id,
  title: t.title,
  why: t.why,
  detailedExplanation: t.explanation,
  concreteAction: t.action,
  systemFunction: t.system_function,
  whenToUse: t.when_to_use,
  microReframe: t.micro_reframe,
  selfTalk: t.self_talk,
  reframeStep: t.reframe_step,
  icon: t.icon,
  trigger: t.trigger,
});

export const mapPlayerDayToDailyContent = (d: PlayerDay): DailyContent => ({
  dayNumber: d.day_id,
  scienceBite: { fact: d.science_bite },
  todayTrigger: d.today_trigger,
  coreShift: d.core_shift,
  tasks: [mapTask(d.tasks[0]), mapTask(d.tasks[1]), mapTask(d.tasks[2])],
  journal: {
    journalTitle: d.journal.title,
    questions: d.journal.questions,
    gratitudeInstruction: d.journal.gratitude_instruction,
    freeReflectionPrompt: d.journal.free_reflection_prompt,
  },
  gratitudePrompt: d.gratitude_prompt,
  selfTalkAnchors: d.self_talk_anchors,
  variants: d.variants,
});

// ─────────── DAYS 1–5 (Player Format, Maximum-Qualität) ───────────

export const PLAYER_DAYS: PlayerDay[] = [
  {
    day_id: 1,
    title: "Präsenz statt Autopilot",
    phase: "Phase I — Sichtbar werden",
    week: 1,
    line: "Presence",
    lens: "Ich beginne heute zu merken, wie oft mein Körper da ist, aber mein Kopf nicht.",
    primary_mechanism: "Attentional Control",
    today_trigger:
      "Sobald du merkst, dass dein Kopf bei Fehlern, Bewertung, Zukunft oder innerem Lärm hängt statt bei der aktuellen Aktion, ist der Tag aktiv.",
    core_shift:
      "Heute verschiebst du dich von blindem Wegdriften zu erster bewusster Rückkehr in die aktuelle Aufgabe.",
    science_bite:
      "Präsenz ist keine Stimmung — sie ist Verfügbarkeit. Sobald dein Fokus nicht mehr bei dem liegt, was gerade wirklich vor dir ist, stehen deinem Gehirn weniger saubere Informationen für die nächste Entscheidung und Ausführung zur Verfügung. Der erste Schritt ist deshalb nicht perfekte Konzentration, sondern überhaupt zu merken, wann du nicht mehr ganz da bist.",
    tasks: [
      {
        id: "d1-t1",
        title: "Erwisch den Drift",
        trigger: "Wenn du merkst, dass dein Kopf weggeht — bei Frust, Unsicherheit, Ablenkung, Bewertung oder innerer Spannung",
        when_to_use: "Mitten im Training, in Übergängen, nach Fehlern, bei Leerlauf, bei Stress oder sobald du merkst, dass du nur noch halb da bist",
        action: "Markiere den Moment innerlich mit einem kurzen, klaren Wort: 'Weg.'",
        why: "Bevor du Fokus steuern kannst, musst du den Moment erkennen, in dem du ihn verlierst.",
        explanation: "Heute geht es nicht darum, perfekt konzentriert zu sein. Heute geht es darum, den Moment klar zu erwischen, in dem dein Körper noch in der Situation ist, dein Kopf aber schon woanders. Genau dort beginnt der Bruch mit Autopilot.",
        self_talk: "Weg.",
        micro_reframe: "Der Drift ist heute kein Scheitern, sondern dein Einstiegspunkt in den Tag.",
        reframe_step: {
          trigger: "Ich merke, dass ich nicht mehr ganz da bin.",
          reframe: "Gut — jetzt sehe ich den Drift zum ersten Mal bewusst.",
          anchor: "Weg.",
        },
        system_function: "Awareness-Trigger",
        icon: "eye",
      },
      {
        id: "d1-t2",
        title: "Zurück an die Aufgabe",
        trigger: "Direkt nachdem du bemerkt hast, dass du innerlich weg bist",
        when_to_use: "Sofort nach 'Weg', bevor dein Kopf wieder in alte Gedankenschleifen springt",
        action: "Richte deinen Fokus auf genau eine konkrete Sache: Ball, Gegenspieler, Position, Kommunikation oder nächste Bewegung.",
        why: "Präsenz wird erst praktisch, wenn du nach dem Drift wieder an der realen Aufgabe andockst.",
        explanation: "Es geht nicht darum, dich zusammenzureißen oder sofort einen perfekten mentalen Zustand zu erzeugen. Es geht nur darum, deine Aufmerksamkeit wieder an das zu binden, was gerade wirklich zählt.",
        self_talk: "Hier. Diese Aktion.",
        micro_reframe: "Du musst nicht alles zurückholen — nur deine nächste echte Aufgabe.",
        reframe_step: {
          trigger: "Ich habe den Drift erkannt.",
          reframe: "Ich brauche keinen perfekten Zustand, nur einen klaren Arbeitsort.",
          anchor: "Hier. Diese Aktion.",
        },
        system_function: "Return-to-Task",
        icon: "target",
      },
      {
        id: "d1-t3",
        title: "Folge nicht blind dem ersten Impuls",
        trigger: "Wenn dein erster Impuls wäre, dich zurückzunehmen, stiller zu werden, nicht mehr zu fordern oder innerlich rauszugehen",
        when_to_use: "Nach Fehlern, bei Unsicherheit, bei Frust oder wenn du dich kleiner machen willst",
        action: "Tu bewusst die funktional bessere Version: drinbleiben, anbieten, klar kommunizieren, wieder in die Aktion gehen.",
        why: "Tag 1 darf nicht nur Beobachtung bleiben. Er soll die erste kleine Musterunterbrechung auslösen.",
        explanation: "Fast jeder Mensch folgt ständig seinem ersten inneren Impuls. Heute trainierst du, dass zwischen Impuls und Handlung ein kleiner Raum entstehen kann. Nicht riesig — aber echt.",
        self_talk: "Bleib drin.",
        micro_reframe: "Heute trainierst du nicht Perfektion, sondern den ersten echten Handlungsspielraum.",
        reframe_step: {
          trigger: "Ich will mich gerade zurückziehen oder vermeiden.",
          reframe: "Genau hier entscheide ich heute zum ersten Mal bewusst anders.",
          anchor: "Bleib drin.",
        },
        system_function: "Behavior Interrupt",
        icon: "flame",
      },
    ],
    journal: {
      title: "Wo war ich heute wirklich da — und wo nicht?",
      questions: [
        { id: "d1-j1", question: "In welchem Moment habe ich heute am klarsten gemerkt, dass mein Kopf weg war?", placeholder: "Beschreibe die Szene konkret." },
        { id: "d1-j2", question: "Wodurch wurde mein Fokus heute am häufigsten weggezogen?", placeholder: "Fehler, Bewertung, Zukunft, Frust, Ablenkung ..." },
        { id: "d1-j3", question: "Konnte ich mindestens einmal bewusst zu meiner nächsten Aufgabe zurückkehren?", placeholder: "Wie sah diese Rückkehr aus?" },
        { id: "d1-j4", question: "In welchem Moment habe ich heute meinem ersten Impuls nicht einfach blind gefolgt?", placeholder: "Welche Gegenbewegung hast du gesetzt?" },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — mindestens 1 angenehme, 1 schwierige und 1 erkenntnisreiche Sache.",
      free_reflection_prompt: "Was zeigt mir dieser Tag über mein aktuelles Muster von Präsenz und Autopilot?",
    },
    gratitude_prompt: "Wofür bin ich heute dankbar — auch in einem schwierigen Moment?",
    self_talk_anchors: [
      { text: "Weg.", when: "Wenn du den Drift bemerkst" },
      { text: "Hier. Diese Aktion.", when: "Wenn du zurück an die Aufgabe gehst" },
      { text: "Bleib drin.", when: "Wenn du dich rausnehmen willst" },
    ],
    variants: {
      training: "Nutze jede Trainingssituation, in der du innerlich wegkippst, als Einstieg in den Tag.",
      rest: "Übertrage den Tag auf Handy, Gespräche, Vergleich, Grübeln und Unruhe im Alltag.",
      match: "Kurzversion: Drift erkennen → zurück zur Aktion → dem ersten Impuls nicht blind folgen.",
    },
  },
  {
    day_id: 2,
    title: "Der Fehler ist nicht das Problem",
    phase: "Phase I — Sichtbar werden",
    week: 1,
    line: "Learning vs Judgement",
    lens: "Was mich nach einem Fehler oft wirklich aus der Bahn bringt, ist nicht nur der Fehler, sondern die innere Bedeutung, die mein Kopf ihm sofort gibt.",
    primary_mechanism: "Metacognitive Defusion",
    today_trigger: "Sobald dir etwas misslingt und sofort ein innerer Satz auftaucht, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von blindem Glauben an den ersten inneren Satz zu erster Distanz und weniger automatischer Enge nach Fehlern.",
    science_bite: "Ein Fehler trifft dich nicht nur von außen. In Sekunden erzeugt dein Gehirn eine erste Bedeutung: Was sagt das über mich? Ist das bedrohlich, peinlich oder einfach Information? Genau dieser innere Satz beeinflusst, wie eng oder weit dein Fokus danach wird und wie du in die nächste Aktion gehst.",
    tasks: [
      {
        id: "d2-t1",
        title: "Fang den ersten Satz",
        trigger: "Wenn dir ein Fehler, Missmoment oder unangenehmer Kontakt passiert",
        when_to_use: "Direkt in den ersten Sekunden nach dem Fehler, bevor du viel analysierst",
        action: "Frag dich kurz: 'Was war gerade mein erster Satz?'",
        why: "Du sollst sichtbar machen, dass dein inneres System Fehler nicht einfach erlebt — es kommentiert sie sofort.",
        explanation: "Das kann sein: 'Das war schlecht', 'Heute läuft gar nichts', 'Jetzt bin ich raus', 'Was denken die anderen?' oder etwas Ähnliches. Wichtig ist nicht, wie hart oder leise der Satz ist — wichtig ist, dass du ihn erwischst.",
        self_talk: "Was war mein erster Satz?",
        micro_reframe: "Heute ist nicht der Fehler selbst der Hauptpunkt, sondern der Satz, der direkt danach auftaucht.",
        reframe_step: {
          trigger: "Etwas geht schief.",
          reframe: "Bevor ich komplett reagiere, sehe ich zuerst, was mein Kopf gerade daraus macht.",
          anchor: "Was war mein erster Satz?",
        },
        system_function: "Awareness-Trigger",
        icon: "eye",
      },
      {
        id: "d2-t2",
        title: "Gedanke, nicht Tatsache",
        trigger: "Nachdem du deinen ersten inneren Satz bemerkt hast",
        when_to_use: "Sofort nach dem Satz, solange er sich noch sehr echt anfühlt",
        action: "Sag einmal ruhig und klar: 'Das ist gerade ein Gedanke.'",
        why: "Die erste Distanz entsteht, wenn der Satz nicht sofort wie Wahrheit behandelt wird.",
        explanation: "Du musst den Gedanken nicht wegmachen. Du musst ihn auch nicht positiv ersetzen. Es reicht, wenn du die erste Trennung öffnest: Da ist ein Satz — und ich muss ihm nicht sofort komplett glauben.",
        self_talk: "Das ist gerade ein Gedanke.",
        micro_reframe: "Ich muss diesen Satz nicht sofort als Wahrheit behandeln.",
        reframe_step: {
          trigger: "Ein harter innerer Satz taucht auf.",
          reframe: "Da ist ein Gedanke. Mehr noch nicht.",
          anchor: "Das ist gerade ein Gedanke.",
        },
        system_function: "Defusion-Step",
        icon: "brain",
      },
      {
        id: "d2-t3",
        title: "Werde nicht enger",
        trigger: "Wenn du nach dem Fehler körperlich, mental oder im Verhalten kleiner wirst",
        when_to_use: "In der direkt nächsten Szene nach dem Fehler",
        action: "Setze eine bewusste Gegenbewegung: aufrichten, anbieten, kommunizieren oder wieder in die Aktion gehen.",
        why: "Fehler werden oft problematisch, weil sie nicht nur Gedanken, sondern auch sofort engeres Verhalten auslösen.",
        explanation: "Viele Spieler werden nach einem Fehler stiller, kleiner, vorsichtiger und weniger präsent. Heute trainierst du, dass der erste innere Satz nicht automatisch dein ganzes Verhalten bestimmen muss.",
        self_talk: "Nicht enger.",
        micro_reframe: "Der Fehler muss nicht sofort meinen Körper und mein Verhalten codieren.",
        reframe_step: {
          trigger: "Ich merke, dass ich kleiner werde.",
          reframe: "Jetzt setze ich eine klare Gegenbewegung.",
          anchor: "Nicht enger.",
        },
        system_function: "Behavior Protection",
        icon: "shield",
      },
    ],
    journal: {
      title: "Was macht mein Kopf aus Fehlern?",
      questions: [
        { id: "d2-j1", question: "Welcher erste innere Satz ist heute nach Fehlern oder unangenehmen Momenten am häufigsten aufgetaucht?", placeholder: "Schreib den Satz möglichst wörtlich auf." },
        { id: "d2-j2", question: "In welchem Moment hat sich ein Gedanke heute besonders wie eine Wahrheit angefühlt?", placeholder: "Beschreibe die Situation." },
        { id: "d2-j3", question: "Konnte ich mindestens einmal klar merken: Das ist gerade ein Gedanke?", placeholder: "Was hat sich dadurch verändert?" },
        { id: "d2-j4", question: "Wann bin ich nach einem Fehler enger geworden — im Körper, im Fokus oder im Verhalten?", placeholder: "Was war dein Muster?" },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas aus einem schwierigen Moment.",
      free_reflection_prompt: "Was zeigt mir dieser Tag über meine automatische Fehlerverarbeitung?",
    },
    gratitude_prompt: "Wofür kann ich heute dankbar sein, obwohl etwas schiefging?",
    self_talk_anchors: [
      { text: "Was war mein erster Satz?", when: "Direkt nach einem Fehler" },
      { text: "Das ist gerade ein Gedanke.", when: "Wenn der Satz sehr echt wirkt" },
      { text: "Nicht enger.", when: "Wenn du kleiner wirst" },
    ],
    variants: {
      training: "Nutze jeden Fehler oder Missmoment als Einstieg in den Tag.",
      rest: "Übertrage den Tag auf Selbstkritik, peinliche Momente, Frust und Vergleich im Alltag.",
      match: "Kurzversion: ersten Satz fangen → als Gedanken erkennen → nicht enger werden.",
    },
  },
  {
    day_id: 3,
    title: "Was du bewertest, steuert dich",
    phase: "Phase I — Sichtbar werden",
    week: 1,
    line: "Fear vs Love",
    lens: "Zwischen Situation und Zustand liegt meine Lesart.",
    primary_mechanism: "Threat-to-Challenge Reappraisal",
    today_trigger: "Sobald dich eine Situation innerlich verändert, enger macht, stresst oder verunsichert, wird der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von automatischer Bedeutungsgebung zu erster Bewertungsflexibilität.",
    science_bite: "Dein Zustand entsteht nicht nur durch die Situation. Dein Gehirn bewertet in Sekunden, was sie bedeutet: Gefahr, Test, Kontrollverlust, Angriff oder Trainingsreiz. Genau diese Lesart beeinflusst, wie eng oder weit, ruhig oder hektisch du danach wirst.",
    tasks: [
      {
        id: "d3-t1",
        title: "Finde die Bedeutung",
        trigger: "Wenn dich etwas stresst, nervt, frustriert, enger macht oder unsicher werden lässt",
        when_to_use: "Bei Fehlern, Kritik, starker Konkurrenz, verlorenen Aktionen, unangenehmen Übungen oder innerem Kippen",
        action: "Frag dich kurz: 'Was bedeutet das gerade für mich?'",
        why: "Du sollst sichtbar machen, welche verborgene Bedeutung dein System der Situation gerade gibt.",
        explanation: "Oft reagierst du nicht nur auf das Ereignis, sondern auf die Lesart dahinter: 'Das ist peinlich', 'Ich verliere Kontrolle', 'Das ist gegen mich', 'Das zeigt, dass ich nicht gut genug bin'. Heute willst du genau diese Bedeutung greifen.",
        self_talk: "Was bedeutet das gerade für mich?",
        micro_reframe: "Nicht nur die Situation zählt — auch die Bedeutung, die mein System ihr gibt.",
        reframe_step: {
          trigger: "Mein Zustand kippt.",
          reframe: "Zwischen Situation und Zustand liegt gerade eine Lesart.",
          anchor: "Was bedeutet das gerade für mich?",
        },
        system_function: "Meaning Awareness",
        icon: "eye",
      },
      {
        id: "d3-t2",
        title: "Öffne eine zweite Lesart",
        trigger: "Nachdem dir die erste automatische Bedeutung klar geworden ist",
        when_to_use: "Direkt nach dem Erkennen der ersten Lesart",
        action: "Ergänze innerlich: 'Es könnte auch ...' und formuliere eine zweite, funktionalere Lesart.",
        why: "Du sollst erleben, dass deine erste Bewertung nicht alternativlos ist.",
        explanation: "Es geht nicht um Schönreden. Es geht darum, neben die erste Bedrohungslese eine zweite brauchbare Lesart zu stellen: Test statt Angriff, Trainingsreiz statt Beweis gegen dich, ehrliche Reibung statt Gefahr.",
        self_talk: "Es könnte auch ...",
        micro_reframe: "Die erste Lesart ist oft automatisch, aber nicht die einzige.",
        reframe_step: {
          trigger: "Ich sehe gerade nur Gefahr, Angriff oder Defizit.",
          reframe: "Jetzt öffne ich bewusst eine zweite, funktionalere Lesart.",
          anchor: "Es könnte auch ...",
        },
        system_function: "Reappraisal Opening",
        icon: "sparkles",
      },
      {
        id: "d3-t3",
        title: "Handle nach der besseren Lesart",
        trigger: "Sobald du eine zweite Lesart geöffnet hast",
        when_to_use: "In der direkt nächsten Handlung oder Szene danach",
        action: "Setze eine klare funktionale Handlung, die zu der besseren Lesart passt.",
        why: "Reappraisal bleibt Theorie, wenn es nicht sichtbar dein Verhalten verändert.",
        explanation: "Wenn du dieselbe Situation anders liest, soll sich das direkt zeigen: präsent bleiben, wieder anbieten, klar kommunizieren, in der Szene bleiben, offen statt enger handeln.",
        self_talk: "Handle nach der besseren Lesart.",
        micro_reframe: "Eine bessere Lesart zählt erst, wenn sie die nächste Handlung verändert.",
        reframe_step: {
          trigger: "Ich habe eine zweite Lesart geöffnet.",
          reframe: "Jetzt zeige ich sie sofort in meiner nächsten Szene.",
          anchor: "Handle nach der besseren Lesart.",
        },
        system_function: "Behavior Translation",
        icon: "target",
      },
    ],
    journal: {
      title: "Wie lese ich schwierige Situationen?",
      questions: [
        { id: "d3-j1", question: "Welche Situation hat mich heute innerlich am stärksten verändert?", placeholder: "Beschreibe die Szene." },
        { id: "d3-j2", question: "Welche erste Bedeutung hat mein Kopf ihr gegeben?", placeholder: "Was hat die Situation für dich innerlich bedeutet?" },
        { id: "d3-j3", question: "Konnte ich mindestens einmal eine zweite Lesart öffnen?", placeholder: "Welche alternative Lesart war funktionaler?" },
        { id: "d3-j4", question: "Wie hat sich mein Verhalten verändert, als ich die Situation anders gelesen habe?", placeholder: "Beschreibe die nächste Handlung." },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — inklusive etwas aus einem schwierigen Moment.",
      free_reflection_prompt: "Was zeigt mir dieser Tag über mein aktuelles Bewertungssystem?",
    },
    gratitude_prompt: "Welche schwierige Situation hat mir heute gezeigt, dass meine Lesart nicht fest sein muss?",
    self_talk_anchors: [
      { text: "Was bedeutet das gerade für mich?", when: "Wenn dein Zustand kippt" },
      { text: "Es könnte auch ...", when: "Wenn du nur eine automatische Lesart siehst" },
      { text: "Handle nach der besseren Lesart.", when: "In der nächsten Szene" },
    ],
    variants: {
      training: "Auf Fehler, Kritik, Gegner, Rolle, Übungen und Stressmomente anwenden.",
      rest: "Übertrage den Tag auf Vergleich, Planänderungen, Frust, soziale Situationen und Zukunftsgrübeln.",
      match: "Kurzversion: Bedeutung sehen → zweite Lesart öffnen → danach handeln.",
    },
  },
  {
    day_id: 4,
    title: "Kontrolle beginnt mit Loslassen",
    phase: "Phase I — Sichtbar werden",
    week: 1,
    line: "Control vs Non-Control",
    lens: "Ich werde stärker, wenn ich erkenne, was gerade nicht bei mir liegt — und meine Energie zurückhole.",
    primary_mechanism: "Acceptance-based Cognitive Load Reduction",
    today_trigger: "Sobald dich etwas innerlich bindet, Energie zieht oder deinen Fokus frisst, obwohl du es gerade nicht beeinflussen kannst, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von Energiebindung an Unsteuerbares zu Rückführung auf das, was wirklich bei dir liegt.",
    science_bite: "Ein großer Teil mentaler Erschöpfung entsteht nicht nur durch das, was passiert. Er entsteht dadurch, dass dein Gehirn weiter Energie an Dinge bindet, die du im Moment nicht beeinflussen kannst. Wenn dein Kopf an etwas festhängt, das gerade nicht veränderbar ist, bleibt weniger Aufmerksamkeit für die nächste saubere Handlung. Loslassen ist deshalb hier kein Rückzug, sondern die Rückgewinnung von mentaler Kapazität.",
    tasks: [
      {
        id: "d4-t1",
        title: "Benenn das Unsteuerbare",
        trigger: "Wenn dich etwas innerlich bindet, aufregt oder Energie zieht",
        when_to_use: "Nach Fehlern, bei Entscheidungen anderer, bei Gegenspielern, bei Bewertung, bei Frust über Rolle oder Ergebnisfantasie",
        action: "Frag dich klar: 'Liegt das gerade wirklich in meiner Kontrolle?' Wenn nein, markiere innerlich: 'Nicht in meiner Kontrolle.'",
        why: "Du kannst Energie erst zurückholen, wenn du erkennst, woran du sie gerade verlierst.",
        explanation: "Viele Spieler bleiben an Dingen hängen, die längst passiert sind oder gerade nicht in ihrer Hand liegen. Heute geht es nicht darum, das sofort wegzumachen. Es geht zuerst darum, sauber zu unterscheiden, was wirklich dein Feld ist — und was nicht.",
        self_talk: "Nicht in meiner Kontrolle.",
        micro_reframe: "Nicht alles, woran mein Kopf hängt, verdient gerade weiter meine Energie.",
        reframe_step: {
          trigger: "Ich merke, dass etwas an mir zieht.",
          reframe: "Bevor ich weiter Energie verliere, prüfe ich erst: Liegt das überhaupt bei mir?",
          anchor: "Nicht in meiner Kontrolle.",
        },
        system_function: "Awareness-Trigger",
        icon: "eye",
      },
      {
        id: "d4-t2",
        title: "Hol die Energie zurück",
        trigger: "Direkt nachdem du etwas als nicht steuerbar erkannt hast",
        when_to_use: "Sofort nach Aufgabe 1, bevor dein Kopf wieder zum gleichen Punkt zurückspringt",
        action: "Richte deinen Fokus bewusst auf eine Sache, die wirklich bei dir liegt: Haltung, Kommunikation, Einsatz, nächste Aktion, Präsenz, Position oder Entscheidung.",
        why: "Loslassen wird erst praktisch, wenn du die frei werdende Energie wieder sinnvoll bindest.",
        explanation: "Viele Menschen versuchen, etwas loszulassen, ohne ihrer Aufmerksamkeit danach eine neue Richtung zu geben. Dann bleibt das System leer oder springt direkt zurück. Heute trainierst du, Energie bewusst an das Steuerbare zurückzubinden.",
        self_talk: "Das liegt bei mir.",
        micro_reframe: "Ich verliere keine Kontrolle — ich hole sie an die richtige Stelle zurück.",
        reframe_step: {
          trigger: "Ich habe erkannt, dass etwas nicht bei mir liegt.",
          reframe: "Jetzt richte ich meine Energie wieder an dem aus, was ich wirklich beeinflussen kann.",
          anchor: "Das liegt bei mir.",
        },
        system_function: "Return-to-Control",
        icon: "target",
      },
      {
        id: "d4-t3",
        title: "Füttere es nicht weiter",
        trigger: "Wenn dein Kopf wieder zu dem gleichen unsteuerbaren Thema zurück will",
        when_to_use: "Beim zweiten Kreislauf aus Ärger, innerem Argumentieren, Schuld, Rechtfertigung oder Grübeln",
        action: "Sag innerlich: 'Schon erkannt. Nicht weiter.' und geh bewusst zurück in Bewegung, Kommunikation, Präsenz oder die nächste konkrete Aufgabe.",
        why: "Oft verlierst du nicht am ersten Ärger, sondern an der zweiten Aufladung.",
        explanation: "Das eigentliche Problem ist häufig nicht nur der erste Impuls, sondern dass du das Unsteuerbare innerlich weiterfütterst. Heute trainierst du, diesen zweiten Kreislauf früher zu stoppen — nicht durch Härte, sondern durch Nicht-Weitermachen.",
        self_talk: "Schon erkannt. Nicht weiter.",
        micro_reframe: "Der zweite Kreislauf kostet oft mehr Energie als die Situation selbst.",
        reframe_step: {
          trigger: "Mein Kopf will wieder dahin zurück.",
          reframe: "Ich habe es schon gesehen. Jetzt bekommt es keine neue Energie.",
          anchor: "Schon erkannt. Nicht weiter.",
        },
        system_function: "Spiral Interrupt",
        icon: "shield",
      },
    ],
    journal: {
      title: "Woran verliere ich Energie, obwohl es nicht bei mir liegt?",
      questions: [
        { id: "d4-j1", question: "Welche Situation hat heute am meisten Energie von mir gezogen?", placeholder: "Beschreibe die Szene konkret." },
        { id: "d4-j2", question: "Lag sie wirklich in meiner Kontrolle?", placeholder: "Woran hast du das erkannt?" },
        { id: "d4-j3", question: "Worauf habe ich meine Energie danach bewusst zurückgeführt?", placeholder: "Was lag wirklich bei dir?" },
        { id: "d4-j4", question: "Wo habe ich ein unsteuerbares Thema weitergefüttert — und wo konnte ich damit aufhören?", placeholder: "Was war der Unterschied?" },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — mindestens 1 leichte, 1 schwierige und 1 präzise Sache, die dir etwas gezeigt hat.",
      free_reflection_prompt: "Was zeigt mir dieser Tag über meine Kontrollillusion und meinen Energiehaushalt?",
    },
    gratitude_prompt: "Welche schwierige Situation hat mir heute gezeigt, dass Loslassen nicht Schwäche, sondern Präzision sein kann?",
    self_talk_anchors: [
      { text: "Nicht in meiner Kontrolle.", when: "Wenn dich etwas bindet, obwohl es nicht bei dir liegt" },
      { text: "Das liegt bei mir.", when: "Wenn du Energie zurück an das Steuerbare bindest" },
      { text: "Schon erkannt. Nicht weiter.", when: "Wenn der zweite Kreislauf starten will" },
    ],
    variants: {
      training: "Nutze vergangene Fehler, Entscheidungen anderer, Gegner, Rolle und Ergebnisgedanken als Material.",
      rest: "Übertrage den Tag auf Grübeln, Vergleich, Zukunftsdenken, Frust und innere Unruhe.",
      match: "Kurzversion: Unsteuerbares benennen → Energie zurückholen → nicht weiter füttern.",
    },
  },
  {
    day_id: 5,
    title: "Ego erkennen",
    phase: "Phase I — Sichtbar werden",
    week: 1,
    line: "Ego vs Inner Excellence",
    lens: "Ich merke, wann es mir gerade mehr um mein Bild als um die Situation, die Aufgabe oder echte Qualität geht.",
    primary_mechanism: "Self-referential Processing Awareness",
    today_trigger: "Sobald du merkst, dass dein Fokus auf Wirkung, Bewertung, Beweis oder dein Bild kippt, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von Selbstbezug auf Qualität — und von Beweis auf Dienst an der Sache.",
    science_bite: "Ego ist im Training oft kein Lautsein, sondern Selbstbindung. Es zeigt sich im ständigen Denken an das eigene Bild, in der Angst, schwach auszusehen, im Bedürfnis, sich zu beweisen oder in übermäßiger Selbstkritik. Sobald dein Fokus stärker an deinem Bild hängt als an der Aufgabe selbst, wird dein System enger. Exzellenz ist etwas anderes: Sie richtet Aufmerksamkeit auf Qualität, Präzision, Beitrag und sauberes Handeln.",
    tasks: [
      {
        id: "d5-t1",
        title: "Erkenne den Bild-Moment",
        trigger: "Wenn dein Fokus plötzlich stark auf Wirkung, Bewertung oder Beweis geht",
        when_to_use: "Bei Fehlern, Vergleich, Unsicherheit, Coolness, Beweisdrang, Rückzug oder wenn du beeindrucken willst",
        action: "Sag innerlich einmal: 'Gerade geht es um mich, nicht um die Aufgabe.'",
        why: "Solange du den Selbstbezug nicht klar erkennst, bleibt 'Ego' nur ein Schlagwort.",
        explanation: "Heute geht es nicht darum, dich dafür zu verurteilen. Es geht darum, den Moment zu erkennen, in dem Leistung innerlich selbstbezogen wird: Wie wirke ich? Wie sehe ich aus? Was sagt das über mich? Genau dieser Shift soll heute sichtbar werden.",
        self_talk: "Gerade geht es um mich, nicht um die Aufgabe.",
        micro_reframe: "Ego ist oft nicht Lautsein, sondern die Rückbindung der Situation auf mein Bild.",
        reframe_step: {
          trigger: "Ich hänge stark an Wirkung oder Bewertung.",
          reframe: "Ich sehe gerade den Bild-Fokus und muss ihm nicht blind folgen.",
          anchor: "Gerade geht es um mich, nicht um die Aufgabe.",
        },
        system_function: "Self-Reference Awareness",
        icon: "eye",
      },
      {
        id: "d5-t2",
        title: "Zurück zur Qualität",
        trigger: "Direkt nachdem du den Bild-Moment erkannt hast",
        when_to_use: "Sobald du wieder an die eigentliche Aufgabe andocken willst",
        action: "Frag dich kurz: 'Was wäre hier gerade die saubere Sache?' und richte deinen Fokus darauf.",
        why: "Der erste Schritt von Ego zu Exzellenz ist die Rückverschiebung von Wirkung auf Qualität.",
        explanation: "Nicht mehr fragen: Wie wirke ich? Was denken die anderen? Sondern: Was ist die Aufgabe? Was ist die saubere Aktion? Was verlangt Qualität in diesem Moment? Genau diese Rückrichtung baut Inner Excellence.",
        self_talk: "Was ist hier die saubere Sache?",
        micro_reframe: "Nicht mein Bild ist hier mein Arbeitsort, sondern Qualität.",
        reframe_step: {
          trigger: "Ich habe den Bild-Moment erkannt.",
          reframe: "Jetzt richte ich mich wieder an der Sache statt an Wirkung aus.",
          anchor: "Was ist hier die saubere Sache?",
        },
        system_function: "Quality Redirect",
        icon: "target",
      },
      {
        id: "d5-t3",
        title: "Wähle Dienst statt Beweis",
        trigger: "Wenn du zwischen bildschonender und dienlicher Handlung wählen kannst",
        when_to_use: "In Situationen, in denen du cool wirken, Recht behalten, dich schützen oder glänzen willst",
        action: "Wähle bewusst die Sache statt den Beweis: klar kommunizieren, helfen, korrigieren lassen, mutig und präzise handeln.",
        why: "Ego wird praktisch schwächer, wenn Handlung nicht mehr primär deinem Bild dient.",
        explanation: "Heute trainierst du zum ersten Mal bewusst die Verschiebung von Beweis zu Dienst. Nicht: Wie sehe ich aus? Sondern: Was dient Team, Aufgabe, Qualität oder Wahrheit des Moments?",
        self_talk: "Diene ich meinem Bild — oder der Sache?",
        micro_reframe: "Exzellenz dient der Situation. Ego dient oft dem Bild.",
        reframe_step: {
          trigger: "Ich spüre Beweisdrang oder Bildschutz.",
          reframe: "Jetzt wähle ich bewusst die dienlichere Handlung.",
          anchor: "Diene ich meinem Bild — oder der Sache?",
        },
        system_function: "Service Over Image",
        icon: "heart",
      },
    ],
    journal: {
      title: "Wann ging es heute um mein Bild — und wann um echte Qualität?",
      questions: [
        { id: "d5-j1", question: "In welchen Momenten ging es mir heute stärker um mein Bild als um die eigentliche Aufgabe?", placeholder: "Beschreibe die Situation." },
        { id: "d5-j2", question: "Wodurch wurde dieser Bild-Fokus ausgelöst?", placeholder: "Fehler, Vergleich, Unsicherheit, Bewertung ..." },
        { id: "d5-j3", question: "Konnte ich heute mindestens einmal von Wirkung zurück auf Qualität schalten?", placeholder: "Was hat dir dabei geholfen?" },
        { id: "d5-j4", question: "Wann habe ich heute eher der Sache gedient als meinem Beweisdrang?", placeholder: "Welche Handlung war dafür ein gutes Beispiel?" },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas, das dir den Unterschied zwischen Wirkung und Qualität gezeigt hat.",
      free_reflection_prompt: "Was zeigt mir dieser Tag über mein aktuelles Verhältnis von Bild, Beweis und echter Exzellenz?",
    },
    gratitude_prompt: "Welche Situation hat mir heute etwas Wichtiges über den Unterschied zwischen Bild und Qualität gezeigt?",
    self_talk_anchors: [
      { text: "Gerade geht es um mich, nicht um die Aufgabe.", when: "Wenn dein Fokus auf Bild oder Wirkung kippt" },
      { text: "Was ist hier die saubere Sache?", when: "Wenn du zurück zu Qualität willst" },
      { text: "Diene ich meinem Bild — oder der Sache?", when: "Wenn Beweisdrang auftaucht" },
    ],
    variants: {
      training: "Nutze Beweisdrang, Wirkung, Selbstkritik, Unsicherheit und Vergleich im Training als Material.",
      rest: "Übertrage den Tag auf Gespräche, Social Media, Vergleich und stillen Selbstfokus im Alltag.",
      match: "Kurzversion: Bild-Moment erkennen → Qualität wählen → der Sache dienen.",
    },
  },
  {
    day_id: 6,
    title: "Dankbarkeit erweitert Wahrnehmung",
    phase: "Phase I — Sichtbar werden",
    week: 1,
    line: "Gratitude vs Anxiety",
    lens: "Wenn mein System eng ist, sehe ich weniger. Wenn es weiter wird, sehe ich wieder mehr als nur Mangel, Fehler, Gefahr und Druck.",
    primary_mechanism: "Affective State Shaping",
    today_trigger: "Sobald dein Blick eng wird und fast nur noch Fehler, Mangel, Gefahr oder Druck sieht, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von Mangel- und Bedrohungsfixierung zu mehr Wahrnehmungsweite und Zugang zu dem, was trotzdem schon da ist.",
    science_bite: "Dankbarkeit ist heute kein nettes Gefühl und kein Schönreden. Sie ist eine aktive Korrektur von Bedrohungsfixierung und Mangelblick. Wenn dein System eng wird, sieht es fast nur noch das, was fehlt oder schiefläuft. Wenn es weiter wird, bekommt es wieder Zugang zu Ressourcen, Möglichkeiten, Tragendem und innerer Weite.",
    tasks: [
      {
        id: "d6-t1",
        title: "Erkenne den Mangelblick",
        trigger: "Wenn dein Blick fast nur noch auf Fehler, Defizit, Gefahr oder Druck geht",
        when_to_use: "Bei Frust, Vergleich, Unsicherheit, nach Fehlern, in engen oder druckvollen Momenten",
        action: "Markiere innerlich den Zustand: 'Mangelblick.'",
        why: "Du musst zuerst sehen, wann dein Wahrnehmungsfeld enger geworden ist.",
        explanation: "Heute geht es nicht darum, Probleme zu leugnen. Es geht darum zu merken, wann dein System fast nur noch auf das Falsche, Fehlende oder Bedrohliche starrt und dadurch an Weite verliert.",
        self_talk: "Mangelblick.",
        micro_reframe: "Mein System sieht gerade nicht alles — es sieht gerade vor allem das Schwierige.",
        reframe_step: {
          trigger: "Ich sehe fast nur noch das Problem.",
          reframe: "Bevor ich weiter reagiere, erkenne ich zuerst die Enge meines Blicks.",
          anchor: "Mangelblick.",
        },
        system_function: "Awareness-Trigger",
        icon: "eye",
      },
      {
        id: "d6-t2",
        title: "Hol das Tragende mit ins Bild",
        trigger: "Direkt nachdem du den engen Blick erkannt hast",
        when_to_use: "Wenn du merkst, dass dein System fast nur noch Defizit registriert",
        action: "Benenne bewusst 2–3 Dinge, die trotzdem schon da, tragend, möglich oder wertvoll sind.",
        why: "Der Tag soll dein Wahrnehmungsfeld wieder erweitern, nicht das Problem wegzaubern.",
        explanation: "Das kann etwas Kleines oder Großes sein: ein guter Kontakt, ein Mitspieler, eine Fähigkeit, eine Chance, eine Aufgabe, ein Lernmoment, ein Körperteil, das funktioniert, eine Beziehung, ein Raum, eine Möglichkeit. Wichtig ist: mehr sehen als nur Mangel.",
        self_talk: "Es ist mehr da.",
        micro_reframe: "Weite heißt nicht, das Schwierige zu leugnen — sondern mehr als nur das Schwierige zu sehen.",
        reframe_step: {
          trigger: "Ich bin im Mangelblick.",
          reframe: "Jetzt erweitere ich bewusst mein Wahrnehmungsfeld.",
          anchor: "Es ist mehr da.",
        },
        system_function: "State Expansion",
        icon: "sparkles",
      },
      {
        id: "d6-t3",
        title: "Handle aus Weite",
        trigger: "Nachdem du deinen Blick wieder etwas geöffnet hast",
        when_to_use: "In der direkt nächsten Handlung oder Szene",
        action: "Setze die nächste Aktion aus mehr Weite statt aus Mangel- oder Bedrohungsfokus.",
        why: "Weite soll nicht nur gedacht, sondern in Verhalten übersetzt werden.",
        explanation: "Wenn dein System weiter wird, verändert sich oft direkt deine Handlung: weniger hektisch, weniger klein, weniger schützend — dafür klarer, tragfähiger, präsenter. Genau diese Übersetzung trainierst du heute.",
        self_talk: "Aus Weite.",
        micro_reframe: "Mein nächster Schritt muss nicht aus Defizit kommen.",
        reframe_step: {
          trigger: "Ich habe wieder mehr gesehen als nur das Problem.",
          reframe: "Jetzt handle ich aus diesem weiteren Zustand.",
          anchor: "Aus Weite.",
        },
        system_function: "Behavior From Breadth",
        icon: "target",
      },
    ],
    journal: {
      title: "Wo war mein Blick heute eng — und wo weiter?",
      questions: [
        { id: "d6-j1", question: "Wann war mein Blick heute am stärksten auf Mangel, Fehler oder Druck gerichtet?", placeholder: "Beschreibe die Situation." },
        { id: "d6-j2", question: "Welche 2–3 Dinge habe ich bewusst wieder mit ins Bild geholt?", placeholder: "Was war trotzdem schon da, tragend oder möglich?" },
        { id: "d6-j3", question: "Hat sich mein Zustand dadurch verändert?", placeholder: "Wenn ja: wie genau?" },
        { id: "d6-j4", question: "Wie hat sich meine nächste Handlung verändert, als mein Blick weiter wurde?", placeholder: "Beschreibe den Unterschied." },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas aus einem schwierigen Moment.",
      free_reflection_prompt: "Was zeigt mir dieser Tag über meinen Mangelblick und meine Fähigkeit, Wahrnehmung wieder zu öffnen?",
    },
    gratitude_prompt: "Was war heute trotz Schwierigkeit schon da, tragend oder wertvoll?",
    self_talk_anchors: [
      { text: "Mangelblick.", when: "Wenn dein System fast nur noch Defizit sieht" },
      { text: "Es ist mehr da.", when: "Wenn du dein Wahrnehmungsfeld wieder öffnest" },
      { text: "Aus Weite.", when: "In der nächsten Handlung" },
    ],
    variants: {
      training: "Nutze Fehler, Frust, Unsicherheit, Vergleich und Druckmomente als Hauptmaterial.",
      rest: "Übertrage den Tag auf Grübeln, Vergleich, Alltagsspannung und innere Enge.",
      match: "Kurzversion: Mangelblick erkennen → Tragendes mit ins Bild holen → aus Weite weiterhandeln.",
    },
  },
  {
    day_id: 7,
    title: "Veränderung beginnt, wenn aus einzelnen Momenten ein Muster wird",
    phase: "Phase I — Sichtbar werden",
    week: 1,
    line: "Integration",
    lens: "Meine Reaktionen folgen Mustern — und ich kann sie erkennen.",
    primary_mechanism: "Pattern Recognition",
    today_trigger: "Sobald du genug Material aus den letzten Tagen hast, nicht nur einzelne Momente, sondern Wiederholungen zu sehen, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von isolierten Einzelerlebnissen zu einem ersten inneren Modell deines Systems.",
    science_bite: "Die meisten Menschen erleben ihre inneren Reaktionen isoliert: heute unkonzentriert, gestern genervt, morgen vielleicht wieder besser. Dadurch wirken mentale Zustände zufällig, obwohl sie oft nach wiederkehrenden Mustern ablaufen. Sobald du Muster siehst, wird Veränderung präziser — denn dann arbeitest du nicht mehr gegen 'schlechte Tage', sondern an einem System.",
    tasks: [
      {
        id: "d7-t1",
        title: "Finde das Muster",
        trigger: "Wenn du auf die letzten Tage zurückschaust und merkst, dass sich bestimmte Reaktionen wiederholt haben",
        when_to_use: "Am Ende der Woche, nach dem Training oder in einem ruhigen Reflexionsmoment",
        action: "Benenne für dich: 'Mein häufigstes Muster dieser Woche war ...'",
        why: "Tag 7 soll die Woche von Einzelerlebnissen zu wiederkehrenden Mustern verdichten.",
        explanation: "Schau nicht auf jede einzelne Szene. Schau darauf, was sich wiederholt hat: Wo war dein Kopf oft weg? Welche Situationen haben dich enger gemacht? Welche Gedanken, Bewertungen oder Bildmuster tauchten häufiger auf?",
        self_talk: "Mein häufigstes Muster war ...",
        micro_reframe: "Veränderung wird präziser, wenn aus Momenten ein Muster wird.",
        reframe_step: {
          trigger: "Ich denke noch in einzelnen Situationen.",
          reframe: "Heute suche ich nicht Einzelfehler, sondern Wiederholungen.",
          anchor: "Mein häufigstes Muster war ...",
        },
        system_function: "Pattern Identification",
        icon: "eye",
      },
      {
        id: "d7-t2",
        title: "Finde den Auslöser",
        trigger: "Nachdem du dein Hauptmuster erkannt hast",
        when_to_use: "Direkt im Anschluss an Aufgabe 1",
        action: "Frag dich: 'Wann taucht dieses Muster besonders zuverlässig auf?'",
        why: "Ein Muster wird erst handhabbar, wenn sein Auslöser sichtbar wird.",
        explanation: "Nicht allgemein bleiben. Finde die Situationen dahinter: nach Fehlern, bei Bewertung, bei Unsicherheit, unter Müdigkeit, im Vergleich, in Drucksituationen oder bei innerer Spannung.",
        self_talk: "Wo zeigt es sich?",
        micro_reframe: "Ein Muster wird veränderbar, wenn ich seinen Startpunkt kenne.",
        reframe_step: {
          trigger: "Ich kenne mein Muster, aber es fühlt sich noch diffus an.",
          reframe: "Jetzt suche ich die Situation, in der es am zuverlässigsten startet.",
          anchor: "Wo zeigt es sich?",
        },
        system_function: "Trigger Mapping",
        icon: "target",
      },
      {
        id: "d7-t3",
        title: "Wähle deinen Hebel",
        trigger: "Wenn Muster und Auslöser klarer geworden sind",
        when_to_use: "Am Ende der Wochenreflexion",
        action: "Lege genau einen Hebel fest, auf den du nächste Woche bewusst achten willst.",
        why: "Tag 7 soll nicht nur Verständnis bringen, sondern eine klare Richtung für die nächste Woche setzen.",
        explanation: "Nicht alles gleichzeitig. Wähle eine Stelle, die du in Woche 2 bewusster greifen willst: Drift, Gedanken, Bildfokus, Mangelblick, Energiebindung oder etwas anderes, das besonders oft wiederkam.",
        self_talk: "Das ist mein Hebel.",
        micro_reframe: "Ich muss nicht alles lösen. Ich brauche den nächsten klaren Zugriffspunkt.",
        reframe_step: {
          trigger: "Ich sehe jetzt mehrere Dinge auf einmal.",
          reframe: "Ich wähle bewusst nur einen Hebel für die nächste Woche.",
          anchor: "Das ist mein Hebel.",
        },
        system_function: "Forward Link",
        icon: "flame",
      },
    ],
    journal: {
      title: "Welches Muster lief diese Woche wirklich?",
      questions: [
        { id: "d7-j1", question: "Welches Muster war diese Woche am stärksten?", placeholder: "Benenn zuerst nur eins." },
        { id: "d7-j2", question: "Wann ist es besonders deutlich aufgetaucht?", placeholder: "Welche Situationen oder Auslöser?" },
        { id: "d7-j3", question: "Was hat dieses Muster in mir oder in meinem Verhalten besonders deutlich gemacht?", placeholder: "Was war der rote Faden?" },
        { id: "d7-j4", question: "Was wird mein Hebel für die nächste Woche?", placeholder: "Worauf will ich gezielt achten?" },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas, das dir deine Muster klarer gezeigt hat.",
      free_reflection_prompt: "Was verstehe ich jetzt klarer über mein inneres System als noch zu Beginn der Woche?",
    },
    gratitude_prompt: "Welche schwierige Situation dieser Woche hat mir am meisten über mein System gezeigt?",
    self_talk_anchors: [
      { text: "Mein häufigstes Muster war ...", when: "Wenn du Woche 1 verdichtest" },
      { text: "Wo zeigt es sich?", when: "Wenn du den Auslöser suchst" },
      { text: "Das ist mein Hebel.", when: "Wenn du Woche 2 vorbereitest" },
    ],
    variants: {
      training: "Weniger Fokus auf einzelne Szenen, mehr auf das, was sich durch die Woche gezogen hat.",
      rest: "Ideal für einen ruhigen Integrationsmoment außerhalb des Trainings.",
      match: "Kurzversion: stärkstes Muster benennen → Trigger finden → Hebel für nächste Woche setzen.",
    },
  },
  {
    day_id: 8,
    title: "Identität entsteht nicht nur im Kopf — sie entsteht durch Verhalten",
    phase: "Phase I — Sichtbar werden",
    week: 2,
    line: "Identity vs Performance",
    lens: "Ich kann Verhalten bewusst wählen, bevor mein Gefühl perfekt ist — und genau dadurch mein Selbstbild mitformen.",
    primary_mechanism: "Identity-based Action Selection",
    today_trigger: "Sobald du nicht nur sehen willst, wie du gerade bist, sondern bewusst entscheiden willst, wie du heute in Situationen sein und handeln willst, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von passiv abgeleiteter Identität zu erster bewusst trainierter Version von dir.",
    science_bite: "Viele Menschen glauben, sie müssten sich zuerst selbstbewusst, ruhig, fokussiert oder stark fühlen, bevor sie so handeln können. In der Realität läuft Veränderung oft anders herum. Dein Gehirn lernt nicht nur aus Gedanken über dich selbst, sondern auch aus wiederholtem Verhalten. Jede Handlung ist ein Signal: So reagiere ich. So trete ich auf. So gehe ich mit Druck, Fehlern oder Unsicherheit um.",
    tasks: [
      {
        id: "d8-t1",
        title: "Definiere deine Version",
        trigger: "Vor dem Training oder vor einem wichtigen Abschnitt des Tages",
        when_to_use: "Am Anfang des Tages, vor Training, vor Match oder vor relevanten Situationen",
        action: "Formuliere für dich: 'Heute trainiere ich die Version von mir, die ...'",
        why: "Identitätscodierung braucht Klarheit. Zu ungenaue Begriffe wie 'besser' oder 'stärker' reichen nicht.",
        explanation: "Definiere nicht, was du erreichen willst, sondern wie du heute sein willst — konkret im Verhalten: ruhig nach Fehlern, präsent im Moment, klar in der Kommunikation, mutig in Entscheidungen, präzise statt bildgetrieben.",
        self_talk: "Heute trainiere ich die Version von mir, die ...",
        micro_reframe: "Ich definiere keine perfekte Zukunftsversion, sondern eine heute trainierbare Version.",
        reframe_step: {
          trigger: "Der Tag oder das Training startet.",
          reframe: "Heute entscheide ich bewusst, welche Version von mir in Situationen auftauchen soll.",
          anchor: "Heute trainiere ich die Version ...",
        },
        system_function: "Identity Set",
        icon: "target",
      },
      {
        id: "d8-t2",
        title: "Beweise sie klein",
        trigger: "Sobald die erste echte Trainings- oder Leistungssituation kommt",
        when_to_use: "In der ersten passenden Szene des Tages",
        action: "Setze eine kleine konkrete Handlung, die zu deiner gewählten Version passt.",
        why: "Identität wird nicht durch große Gedanken stabil, sondern durch kleine wiederholte Beweise.",
        explanation: "Nicht auf den perfekten Moment warten. Zeig die Richtung klein: anbieten, sprechen, drinbleiben, sauber handeln, mutiger reagieren, präsenter bleiben.",
        self_talk: "Zeig es klein.",
        micro_reframe: "Große Identitätsveränderung beginnt oft mit kleinen sichtbaren Beweisen.",
        reframe_step: {
          trigger: "Die erste echte Szene ist da.",
          reframe: "Ich brauche kein großes Zeichen — nur den ersten kleinen Beweis.",
          anchor: "Zeig es klein.",
        },
        system_function: "Behavior Evidence",
        icon: "sparkles",
      },
      {
        id: "d8-t3",
        title: "Komm zurück zur Richtung",
        trigger: "Wenn du in alte automatische Muster zurückfällst",
        when_to_use: "Nach Fehlern, Unsicherheit, Rückzug, Passivität oder altem Autopilot",
        action: "Erinnere deine gewählte Version und richte die nächste Handlung wieder daran aus.",
        why: "Identität entsteht nicht durch Perfektion, sondern durch wiederholte Rückkehr zu derselben Richtung.",
        explanation: "Du musst heute nicht durchgehend 'die neue Version' sein. Aber du sollst merken, dass du die Richtung bewusst wieder aufnehmen kannst.",
        self_talk: "Zurück zu meiner Richtung.",
        micro_reframe: "Nicht Perfektion entscheidet — sondern wie oft ich zurück zur gewählten Version komme.",
        reframe_step: {
          trigger: "Ich merke, dass ich wieder im alten Muster bin.",
          reframe: "Die Richtung ist nicht weg. Ich nehme sie wieder auf.",
          anchor: "Zurück zu meiner Richtung.",
        },
        system_function: "Identity Return",
        icon: "sunrise",
      },
    ],
    journal: {
      title: "Welche Version von mir habe ich heute trainiert?",
      questions: [
        { id: "d8-j1", question: "Welche Version von mir wollte ich heute im Training oder in wichtigen Situationen sein?", placeholder: "Beschreibe sie in einem Satz." },
        { id: "d8-j2", question: "Wodurch wurde diese Version heute sichtbar?", placeholder: "Welche kleine Handlung war ein echter Beweis?" },
        { id: "d8-j3", question: "Wann bin ich in ein altes Muster zurückgefallen?", placeholder: "Was hat das ausgelöst?" },
        { id: "d8-j4", question: "Wann ist es mir gelungen, wieder zu meiner gewählten Richtung zurückzukehren?", placeholder: "Wie sah diese Rückkehr konkret aus?" },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas, das dir deine Richtung klarer gezeigt hat.",
      free_reflection_prompt: "Was sagt mir dieser Tag darüber, wer ich nicht nur gerade bin, sondern zunehmend werde?",
    },
    gratitude_prompt: "Welche kleine Handlung heute war ein wichtiger Beweis für die Version von mir, die ich werden will?",
    self_talk_anchors: [
      { text: "Heute trainiere ich die Version von mir, die ...", when: "Vor dem Start" },
      { text: "Zeig es klein.", when: "Beim ersten Beweis" },
      { text: "Zurück zu meiner Richtung.", when: "Wenn alte Muster wieder auftauchen" },
    ],
    variants: {
      training: "Vor dem Training eine klare Version wählen und sie im Verhalten beweisen.",
      rest: "Auf Alltag übertragen: Wie willst du heute auftreten, reagieren und handeln?",
      match: "Kurzversion: Version wählen → 1–2 klare Beweise setzen → zur Richtung zurückkommen.",
    },
  },
  {
    day_id: 9,
    title: "Angst ist oft Bewertung",
    phase: "Phase I — Sichtbar werden",
    week: 2,
    line: "Fear vs Love",
    lens: "Ein Teil dessen, was ich als Angst oder Druck erlebe, entsteht daraus, wie mein System die Situation liest.",
    primary_mechanism: "Threat Appraisal Awareness",
    today_trigger: "Sobald Druck, Anspannung oder Angst auftauchen und du merkst, dass die Situation innerlich größer oder bedrohlicher wird, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von 'Druck ist einfach da' zu 'Druck wird auch durch meine Lesart gebaut'.",
    science_bite: "Druck ist nicht nur ein Gefühl, das einfach über dich kommt. Ein Teil davon entsteht daraus, wie dein System die Situation liest: als Gefahr, als Test, als Bedrohung für dein Bild oder als etwas, wovor du dich schützen musst. Genau diese Lesart beeinflusst Fokus, Körper und nächste Handlung.",
    tasks: [
      {
        id: "d9-t1",
        title: "Erkenne die Gefahren-Lesart",
        trigger: "Wenn du vor oder in einer Situation Druck, Angst, Enge oder Übererregung spürst",
        when_to_use: "Vor wichtigen Aktionen, vor Beobachtung, bei Fehlerangst, bei starken Gegnern, bei Leistungsdruck",
        action: "Frag dich kurz: 'Was liest mein System hier gerade als Gefahr?'",
        why: "Du sollst Angst nicht nur fühlen, sondern die Lesart dahinter sichtbar machen.",
        explanation: "Viele Druckmomente wirken so, als wären sie objektiv einfach bedrohlich. Heute trainierst du, die erste innere Gefahr-Lesart zu greifen: Wovor genau glaubt dein System sich gerade schützen zu müssen?",
        self_talk: "Was ist hier gerade die Gefahr?",
        micro_reframe: "Nicht nur die Situation macht Druck — auch die Bedeutung, die mein System ihr gibt.",
        reframe_step: {
          trigger: "Ich spüre Druck oder Angst.",
          reframe: "Bevor ich einfach reagiere, sehe ich zuerst, was mein System hier gerade als Gefahr liest.",
          anchor: "Was ist hier gerade die Gefahr?",
        },
        system_function: "Threat Awareness",
        icon: "eye",
      },
      {
        id: "d9-t2",
        title: "Benenn den Schutzmodus",
        trigger: "Nachdem dir klar geworden ist, was an der Situation gerade bedrohlich wirkt",
        when_to_use: "Sobald du merkst, dass dein System innerlich etwas absichern, schützen oder vermeiden will",
        action: "Sag dir einmal ehrlich, was du gerade schützen willst: Bild, Ergebnis, Kontrolle, Zugehörigkeit oder Status.",
        why: "Hinter Druck steckt oft nicht nur Angst, sondern eine konkrete Schutzlogik.",
        explanation: "Wenn dir klar wird, was dein System hier schützen will, wird die Reaktion weniger diffus und du bekommst mehr Zugriff auf den Moment.",
        self_talk: "Was will ich gerade schützen?",
        micro_reframe: "Hinter meiner Enge steckt oft ein Schutzversuch meines Systems.",
        reframe_step: {
          trigger: "Mir wird die Gefahr-Lesart klar.",
          reframe: "Jetzt sehe ich genauer, was mein System hier absichern will.",
          anchor: "Was will ich gerade schützen?",
        },
        system_function: "Protection Mapping",
        icon: "shield",
      },
      {
        id: "d9-t3",
        title: "Öffne die funktionalere Lesart",
        trigger: "Wenn du Gefahr-Lesart und Schutzmodus erkannt hast",
        when_to_use: "In der direkt nächsten Szene oder kurz vor der nächsten relevanten Handlung",
        action: "Erlaube dir bewusst eine zweite Lesart: Test, Reibung, ehrliche Herausforderung oder Wachstumsreiz — und handle aus dieser Richtung.",
        why: "Tag 9 soll nicht beim Erkennen enden, sondern die erste Verschiebung von Bedrohung zu Funktion öffnen.",
        explanation: "Du musst Angst nicht sofort wegmachen. Es reicht, wenn du neben die Bedrohungslese eine funktionalere Alternative stellst. Genau dort beginnt die erste offene, weniger schutzgetriebene Reaktion.",
        self_talk: "Das könnte auch ein Test sein.",
        micro_reframe: "Die Situation muss nicht nur Gefahr sein — sie kann auch eine ehrliche Herausforderung sein.",
        reframe_step: {
          trigger: "Ich sehe Gefahr und Schutzlogik.",
          reframe: "Ich öffne bewusst eine zweite Lesart, die mehr Handlung erlaubt.",
          anchor: "Das könnte auch ein Test sein.",
        },
        system_function: "Reappraisal Shift",
        icon: "sparkles",
      },
    ],
    journal: {
      title: "Wie hat mein System Druck heute gelesen?",
      questions: [
        { id: "d9-j1", question: "Welche Situation hat heute am meisten Druck, Angst oder Enge erzeugt?", placeholder: "Beschreibe die Szene konkret." },
        { id: "d9-j2", question: "Was genau hat mein System daran als Gefahr gelesen?", placeholder: "Was war innerlich bedrohlich?" },
        { id: "d9-j3", question: "Was wollte ich in diesem Moment schützen?", placeholder: "Bild, Ergebnis, Kontrolle, Zugehörigkeit, Status ..." },
        { id: "d9-j4", question: "Welche funktionalere zweite Lesart war heute möglich — oder hätte möglich sein können?", placeholder: "Wie hättest du die Situation auch lesen können?" },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas aus einem Druckmoment.",
      free_reflection_prompt: "Was zeigt mir dieser Tag darüber, wie mein System Angst, Druck und Schutz organisiert?",
    },
    gratitude_prompt: "Welche Drucksituation hat mir heute etwas Wichtiges über mein System gezeigt?",
    self_talk_anchors: [
      { text: "Was ist hier gerade die Gefahr?", when: "Wenn Druck oder Enge aufkommt" },
      { text: "Was will ich gerade schützen?", when: "Wenn du die Schutzlogik klarer sehen willst" },
      { text: "Das könnte auch ein Test sein.", when: "Wenn du eine funktionalere Lesart öffnen willst" },
    ],
    variants: {
      training: "Nutze Fehlerangst, Beobachtung, starke Gegner, Leistungsdruck und Bewertung als Hauptmaterial.",
      rest: "Übertrage den Tag auf Gespräche, Erwartungen, soziale Unsicherheit, Vergleich und Zukunftsdruck.",
      match: "Kurzversion: Gefahr-Lesart sehen → Schutzmodus benennen → zweite Lesart öffnen.",
    },
  },
  {
    day_id: 10,
    title: "Confidence ist keine Stimmung",
    phase: "Phase I — Sichtbar werden",
    week: 2,
    line: "Confidence vs Self-Doubt",
    lens: "Ich kann funktional handeln, auch wenn mein Gefühl noch nicht perfekt ist.",
    primary_mechanism: "Self-efficacy Framing",
    today_trigger: "Sobald du merkst, dass du erst sicherer, lockerer oder 'besser drauf' sein willst, bevor du handelst, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von gefühlsabhängiger Confidence zu handlungsgebundener Confidence.",
    science_bite: "Confidence ist nicht perfekte innere Sicherheit. Sie wird oft stabiler, wenn dein System erlebt: Ich kann auch mit Zweifel, Unsicherheit oder ohne perfektes Gefühl funktional handeln. Genau daraus entsteht echte Handlungszuversicht.",
    tasks: [
      {
        id: "d10-t1",
        title: "Erkenne das Warten auf Gefühl",
        trigger: "Wenn du innerlich erst sicherer, ruhiger, klarer oder 'mehr drin' sein willst, bevor du handelst",
        when_to_use: "Vor wichtigen Aktionen, bei Unsicherheit, nach Fehlern, vor Gesprächen oder wenn du auf 'das richtige Gefühl' wartest",
        action: "Sag dir einmal klar: 'Ich warte gerade auf Gefühl.'",
        why: "Viele Spieler verwechseln Confidence mit guter Energie oder perfektem inneren Zustand.",
        explanation: "Heute sollst du sichtbar machen, wie oft du Handlung an Stimmung koppelst. Genau dieses Warten macht Confidence instabil, weil sie dann nur dann da ist, wenn du dich gerade gut fühlst.",
        self_talk: "Ich warte gerade auf Gefühl.",
        micro_reframe: "Confidence hängt nicht nur daran, wie ich mich fühle, sondern auch daran, wie ich handle.",
        reframe_step: {
          trigger: "Ich merke, dass ich erst anders drauf sein will.",
          reframe: "Heute erkenne ich zuerst die Abhängigkeit vom Gefühl.",
          anchor: "Ich warte gerade auf Gefühl.",
        },
        system_function: "State Dependence Awareness",
        icon: "eye",
      },
      {
        id: "d10-t2",
        title: "Handle vor voller Sicherheit",
        trigger: "Nachdem du bemerkt hast, dass du auf das richtige Gefühl wartest",
        when_to_use: "In der direkt nächsten kleinen, klaren und funktionalen Handlung",
        action: "Setze trotzdem eine saubere Handlung: anbieten, sprechen, fordern, in der Szene bleiben oder Präsenz zeigen.",
        why: "Confidence soll heute an Handlung gebunden werden, nicht nur an Gefühl.",
        explanation: "Es geht nicht um Blindheit oder Hype. Es geht um einen funktionalen Schritt trotz Unsicherheit. Genau so lernt dein System: Ich kann handeln, auch wenn ich mich noch nicht perfekt fühle.",
        self_talk: "Trotzdem handeln.",
        micro_reframe: "Ich brauche kein perfektes Gefühl, um eine saubere Handlung zu setzen.",
        reframe_step: {
          trigger: "Ich habe das Warten auf Gefühl erkannt.",
          reframe: "Jetzt setze ich einen kleinen realen Beweis durch Handlung.",
          anchor: "Trotzdem handeln.",
        },
        system_function: "Action Before Mood",
        icon: "flame",
      },
      {
        id: "d10-t3",
        title: "Speichere die Evidenz",
        trigger: "Direkt nachdem du trotz Unsicherheit gehandelt hast",
        when_to_use: "Nach einer kleinen sauberen Handlung, besonders wenn du sie sonst übersehen würdest",
        action: "Markiere innerlich: 'Das zählt.'",
        why: "Dein System soll Handlung als echten Confidence-Beweis lesen lernen.",
        explanation: "Viele Spieler sehen nur perfekte Szenen oder gutes Gefühl als Confidence-Beweis. Heute speicherst du etwas anderes: Ich habe trotz Unsicherheit gehandelt. Genau das ist bereits reale Handlungszuversicht.",
        self_talk: "Das zählt.",
        micro_reframe: "Confidence wächst oft nicht nur vor Handlung, sondern durch sie.",
        reframe_step: {
          trigger: "Ich habe trotz Unsicherheit gehandelt.",
          reframe: "Diese Handlung ist nicht klein oder wertlos — sie ist echte Evidenz.",
          anchor: "Das zählt.",
        },
        system_function: "Evidence Encoding",
        icon: "sparkles",
      },
    ],
    journal: {
      title: "Wo habe ich heute auf Gefühl gewartet — und wo trotzdem gehandelt?",
      questions: [
        { id: "d10-j1", question: "In welchem Moment habe ich heute besonders gemerkt, dass ich erst sicherer oder 'besser drauf' sein wollte?", placeholder: "Beschreibe die Situation konkret." },
        { id: "d10-j2", question: "Welche kleine funktionale Handlung habe ich trotzdem gesetzt?", placeholder: "Was war dein konkreter Schritt?" },
        { id: "d10-j3", question: "Wie hat sich diese Handlung auf meinen Zustand oder meine nächste Szene ausgewirkt?", placeholder: "Was hat sich verändert?" },
        { id: "d10-j4", question: "Was zeigt mir das darüber, wie Confidence bei mir wirklich entsteht?", placeholder: "Formuliere es so klar wie möglich." },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas aus einem Moment, in dem du dich nicht perfekt gefühlt hast.",
      free_reflection_prompt: "Was zeigt mir dieser Tag darüber, wie stark ich Confidence bisher an Gefühl statt an Handlung gebunden habe?",
    },
    gratitude_prompt: "Welche kleine Handlung heute war ein echter Confidence-Beweis?",
    self_talk_anchors: [
      { text: "Ich warte gerade auf Gefühl.", when: "Wenn du auf die richtige Stimmung wartest" },
      { text: "Trotzdem handeln.", when: "In der nächsten kleinen funktionalen Handlung" },
      { text: "Das zählt.", when: "Wenn du die Handlung bewusst als Evidenz speicherst" },
    ],
    variants: {
      training: "Achte besonders auf Momente, in denen du erst lockerer, sicherer oder 'mehr drin' sein willst, bevor du handelst.",
      rest: "Übertrage den Tag auf Gespräche, Entscheidungen, Arbeit, Auftreten und Alltagshandlungen.",
      match: "Kurzversion: Warten auf Gefühl erkennen → trotzdem handeln → Handlung als Beweis speichern.",
    },
  },
  {
    day_id: 11,
    title: "Lernen braucht Unsicherheit",
    phase: "Phase I — Sichtbar werden",
    week: 2,
    line: "Growth vs Winning",
    lens: "Wenn ich nur dort bleibe, wo mein System sich schon sicher fühlt, lerne ich oft weniger, als ich denke.",
    primary_mechanism: "Prediction Error / Exploration",
    today_trigger: "Sobald du merkst, dass du lieber das tust, was schon klappt, statt das, was dich wirklich wachsen lässt, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von Sicherheitsschleifen zu bewusst gewähltem Lernraum.",
    science_bite: "Dein Gehirn lernt besonders stark dort, wo etwas nicht ganz so läuft, wie es schon erwartet wurde. Wenn du nur in sicheren Schleifen bleibst, stabilisierst du oft eher Bekanntes, statt wirklich etwas Neues zu entwickeln. Unsicherheit ist deshalb heute nicht das Problem, sondern oft der Preis echter Entwicklung.",
    tasks: [
      {
        id: "d11-t1",
        title: "Erkenne die Sicherheitsschleife",
        trigger: "Wenn du dazu neigst, nur das zu tun, was sich sicher, kompetent oder ordentlich anfühlt",
        when_to_use: "Bei Übungen, in technischen Situationen, in Duellen, in Lernphasen oder wenn du lieber auf Bekanntes zurückgreifst",
        action: "Frag dich kurz: 'Bleibe ich gerade im Sicheren — oder im Lernraum?'",
        why: "Echte Entwicklung wird oft nicht nur durch Fehlervermeidung blockiert, sondern durch zu viel Sicherheitssuche.",
        explanation: "Viele Spieler sehen nur offensichtliche Vermeidung. Schwieriger zu erkennen ist die stille Lernbremse: nur saubere Lösungen wählen, nur Bekanntes spielen, nur dort aktiv werden, wo man ordentlich wirkt. Heute machst du diese Schleife sichtbar.",
        self_talk: "Sicher oder Lernraum?",
        micro_reframe: "Nicht alles, was sich gut anfühlt, bringt mich gerade wirklich weiter.",
        reframe_step: {
          trigger: "Ich greife automatisch zur sicheren Variante.",
          reframe: "Bevor ich sie wähle, prüfe ich: Ist das gerade wirklich Entwicklung?",
          anchor: "Sicher oder Lernraum?",
        },
        system_function: "Exploration Awareness",
        icon: "eye",
      },
      {
        id: "d11-t2",
        title: "Wähle einen echten Lernreiz",
        trigger: "Nachdem du bemerkt hast, dass du in der Sicherheitsschleife bist",
        when_to_use: "In einer Situation, in der du bewusst etwas Anspruchsvolleres, Offeneres oder Unsichereres wählen kannst",
        action: "Wähle heute mindestens einmal bewusst die Variante, die dich fordert statt nur bestätigt.",
        why: "Tag 11 soll nicht nur Unsicherheit erkennen, sondern einen ersten aktiven Schritt in echten Lernraum auslösen.",
        explanation: "Das heißt nicht Chaos oder blinder Mut. Es heißt: Nimm den Lernreiz, nicht nur die saubere Selbstbestätigung. Such den Kontakt, fordere mehr Verantwortung, bleib in einer schwierigen technischen Situation, geh nicht nur in die sichere Wiederholung.",
        self_talk: "Geh in den Lernraum.",
        micro_reframe: "Unsicherheit ist heute kein Beweis gegen mich, sondern oft die Tür zu Entwicklung.",
        reframe_step: {
          trigger: "Ich habe die Sicherheitsschleife erkannt.",
          reframe: "Jetzt wähle ich bewusst eine Version, die mich wirklich fordert.",
          anchor: "Geh in den Lernraum.",
        },
        system_function: "Exploration Choice",
        icon: "flame",
      },
      {
        id: "d11-t3",
        title: "Schütze nicht dein Bild, schütze den Lernprozess",
        trigger: "Wenn Unsicherheit direkt Beweisdrang, Rückzug oder Bildschutz auslöst",
        when_to_use: "Vor allem dann, wenn du dich in der herausfordernden Situation plötzlich kleiner, vorsichtiger oder defensiver machen willst",
        action: "Bleib in der Situation offen genug, dass Lernen weiter möglich bleibt.",
        why: "Der eigentliche Bruch ist nicht nur, in Unsicherheit hineinzugehen, sondern dort nicht sofort wieder in Schutzlogik zu kippen.",
        explanation: "Viele Spieler gehen kurz in den Lernraum und springen beim ersten unangenehmen Signal direkt zurück in Bildschutz. Heute ist der entscheidende Schritt, die Offenheit kurz zu halten, statt sie sofort wieder zu schließen.",
        self_talk: "Offen bleiben.",
        micro_reframe: "Nicht mein Bild muss heute geschützt werden, sondern mein Lernraum.",
        reframe_step: {
          trigger: "Unsicherheit löst sofort Schutz aus.",
          reframe: "Ich muss mich hier nicht sofort absichern. Ich bleibe kurz offen genug, um wirklich zu lernen.",
          anchor: "Offen bleiben.",
        },
        system_function: "Learning Protection",
        icon: "sparkles",
      },
    ],
    journal: {
      title: "Wo habe ich heute Sicherheit gesucht — und wo Lernraum gewählt?",
      questions: [
        { id: "d11-j1", question: "In welchen Momenten wollte ich heute lieber im Sicheren bleiben, statt wirklich zu lernen?", placeholder: "Beschreibe die Situation möglichst konkret." },
        { id: "d11-j2", question: "Wo habe ich heute bewusst einen echten Lernreiz gewählt?", placeholder: "Was war daran unsicher, offen oder fordernd?" },
        { id: "d11-j3", question: "Wann wollte mein System in Unsicherheit sofort wieder Schutz oder Bestätigung suchen?", placeholder: "Wie hat sich das gezeigt?" },
        { id: "d11-j4", question: "Was zeigt mir das darüber, wie stark ich Lernen noch an Sicherheit knüpfe?", placeholder: "Formuliere es so klar wie möglich." },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas, das unangenehm war und dir echten Lernraum gezeigt hat.",
      free_reflection_prompt: "Was zeigt mir dieser Tag darüber, wie ich bisher Sicherheit mit Entwicklung verwechselt habe?",
    },
    gratitude_prompt: "Welche unangenehme Situation heute war vielleicht genau der Lernraum, den ich gebraucht habe?",
    self_talk_anchors: [
      { text: "Sicher oder Lernraum?", when: "Wenn du zur bequemen Variante greifen willst" },
      { text: "Geh in den Lernraum.", when: "Wenn du bewusst die forderndere Option wählst" },
      { text: "Offen bleiben.", when: "Wenn Unsicherheit sofort Schutz auslöst" },
    ],
    variants: {
      training: "Nutze technische Situationen, Duelle, neue Muster und fordernde Übungsformen als Material.",
      rest: "Übertrage den Tag auf unangenehme Aufgaben, schwierige Gespräche, Lernen, Disziplin und Entscheidungen im Alltag.",
      match: "Kurzversion: Sicherheitsschleife erkennen → echten Lernraum wählen → nicht sofort in Schutz kippen.",
    },
  },
  {
    day_id: 12,
    title: "Exzellenz ist nicht Wirkung",
    phase: "Phase I — Sichtbar werden",
    week: 2,
    line: "Ego vs Inner Excellence",
    lens: "Ich kann Qualität wählen, ohne dass mein Fokus ständig auf Wirkung, Bild oder Performance nach außen rutscht.",
    primary_mechanism: "Image-to-Quality Reorientation",
    today_trigger: "Sobald du merkst, dass du eher gut wirken, beeindrucken oder dein Bild schützen willst, als sauber zu handeln, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von Wirkung zu Qualität — und von Selbstinszenierung zu echter Exzellenz.",
    science_bite: "Wirkung und Qualität sind nicht dasselbe. Viele Spieler handeln so, dass sie stark, cool, sicher oder besonders wirken. Exzellenz funktioniert anders: Sie richtet Aufmerksamkeit auf die Aufgabe, die Präzision, den Beitrag und die saubere Ausführung. Sobald dein Fokus stärker an Wirkung hängt als an echter Qualität, wird Leistung oft enger, künstlicher oder defensiver.",
    tasks: [
      {
        id: "d12-t1",
        title: "Erkenne den Wirkungsfokus",
        trigger: "Wenn du stark daran hängst, wie du rüberkommst, wie du aussiehst oder wie andere dich wahrnehmen",
        when_to_use: "Bei Beobachtung, Vergleich, Fehlern, Lob, Unsicherheit, Social Pressure oder Beweisdrang",
        action: "Frag dich kurz: 'Geht es mir hier gerade um Wirkung — oder um Qualität?'",
        why: "Tag 12 muss zuerst sichtbar machen, wann Aufmerksamkeit von der Aufgabe auf Außenwirkung kippt.",
        explanation: "Wirkungsfokus kann laut oder still sein: beeindrucken wollen, cool wirken, keine Schwäche zeigen, zu stark an Lob oder Kritik hängen, eine Rolle spielen statt ehrlich zu handeln. Heute machst du diesen Fokus sichtbar.",
        self_talk: "Wirkung oder Qualität?",
        micro_reframe: "Gut wirken und gut handeln sind nicht automatisch dasselbe.",
        reframe_step: {
          trigger: "Ich hänge stark daran, wie ich wirke.",
          reframe: "Bevor ich reagiere, kläre ich zuerst: Suche ich gerade Wirkung oder echte Qualität?",
          anchor: "Wirkung oder Qualität?",
        },
        system_function: "Image Awareness",
        icon: "eye",
      },
      {
        id: "d12-t2",
        title: "Frage nach der sauberen Sache",
        trigger: "Nachdem du den Wirkungsfokus erkannt hast",
        when_to_use: "Sobald du wieder zur Aufgabe und echten Exzellenz zurückfinden willst",
        action: "Frag dich: 'Was ist hier die saubere Sache?' und richte dich daran aus.",
        why: "Der Wechsel von Wirkung zu Exzellenz braucht einen klaren neuen Aufmerksamkeitsort.",
        explanation: "Nicht: Wie sehe ich aus? Nicht: Was denken die anderen? Sondern: Was ist technisch, menschlich, sportlich oder situativ die saubere Handlung? Genau dieser Fokus trennt Exzellenz von Selbstdarstellung.",
        self_talk: "Was ist hier die saubere Sache?",
        micro_reframe: "Exzellenz richtet sich an der Wahrheit des Moments aus, nicht an Wirkung.",
        reframe_step: {
          trigger: "Ich habe den Wirkungsfokus erkannt.",
          reframe: "Jetzt gehe ich weg von Außenwirkung und zurück zu echter Qualität.",
          anchor: "Was ist hier die saubere Sache?",
        },
        system_function: "Quality Redirect",
        icon: "target",
      },
      {
        id: "d12-t3",
        title: "Wähle ehrliche Qualität",
        trigger: "Wenn du zwischen performativer und echter Handlung wählen kannst",
        when_to_use: "In Situationen, in denen du beeindrucken, dich schützen oder 'gut aussehen' könntest",
        action: "Wähle bewusst die ehrlichere, dienlichere und qualitativ sauberere Handlung.",
        why: "Exzellenz wird erst real, wenn sie Verhalten übernimmt und nicht nur eine schöne Idee bleibt.",
        explanation: "Das kann heißen: Hilfe annehmen, klarer kommunizieren, eine Korrektur annehmen, auf Aufgabe statt Show gehen, weniger performen und mehr sauber arbeiten. Tag 12 will echte Qualität sichtbarer machen als Wirkung.",
        self_talk: "Qualität vor Wirkung.",
        micro_reframe: "Was langfristig trägt, ist nicht gute Wirkung, sondern echte Qualität.",
        reframe_step: {
          trigger: "Ich könnte jetzt performen oder sauber handeln.",
          reframe: "Heute wähle ich nicht die schönere Show, sondern die ehrlichere Qualität.",
          anchor: "Qualität vor Wirkung.",
        },
        system_function: "Embodied Excellence",
        icon: "heart",
      },
    ],
    journal: {
      title: "Wann ging es heute um Wirkung — und wann um echte Qualität?",
      questions: [
        { id: "d12-j1", question: "In welchen Momenten ging es mir heute stärker um Wirkung als um echte Qualität?", placeholder: "Beschreibe die Situation konkret." },
        { id: "d12-j2", question: "Wodurch wurde dieser Wirkungsfokus ausgelöst?", placeholder: "Bewertung, Unsicherheit, Vergleich, Lob, Fehler ..." },
        { id: "d12-j3", question: "Konnte ich heute mindestens einmal zurück zur sauberen Sache schalten?", placeholder: "Wie sah diese Rückkehr aus?" },
        { id: "d12-j4", question: "Wann habe ich heute eher ehrliche Qualität gewählt als gute Wirkung?", placeholder: "Welche Handlung war dafür ein gutes Beispiel?" },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas, das dir den Unterschied zwischen Wirkung und Qualität klarer gemacht hat.",
      free_reflection_prompt: "Was zeigt mir dieser Tag über mein aktuelles Verhältnis von Wirkung, Bild und Exzellenz?",
    },
    gratitude_prompt: "Welche Situation heute hat mir geholfen, Wirkung und echte Qualität besser zu unterscheiden?",
    self_talk_anchors: [
      { text: "Wirkung oder Qualität?", when: "Wenn dein Fokus auf Außenwirkung kippt" },
      { text: "Was ist hier die saubere Sache?", when: "Wenn du zurück zur Aufgabe willst" },
      { text: "Qualität vor Wirkung.", when: "Wenn du die Handlung bewusst wählen musst" },
    ],
    variants: {
      training: "Nutze Beobachtung, Vergleich, Lob, Fehler, Unsicherheit und Beweisdrang als Hauptmaterial.",
      rest: "Übertrage den Tag auf Social Media, Gespräche, Vergleich, Selbstbildpflege und performatives Verhalten im Alltag.",
      match: "Kurzversion: Wirkung oder Aufgabe? → Was ist die saubere Sache? → Qualität vor Wirkung.",
    },
  },
  {
    day_id: 13,
    title: "Gedanken sind Ereignisse, keine Befehle",
    phase: "Phase I — Sichtbar werden",
    week: 2,
    line: "Learning vs Judgement",
    lens: "Nicht jeder innere Kommentar verdient sofort Gehorsam.",
    primary_mechanism: "Metacognitive Defusion",
    today_trigger: "Sobald dein Kopf laut wird und Gedanken so klingen, als müssten sie sofort geglaubt oder befolgt werden, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von Gedanke = Regisseur zu Gedanke = inneres Ereignis, das nicht automatisch mein Verhalten bestimmen muss.",
    science_bite: "Innere Sprache wirkt oft wie Wahrheit oder Befehl: 'Lass das', 'Du bist raus', 'Heute läuft gar nichts', 'Mach bloß keinen Fehler'. Genau deshalb steuern Gedanken Verhalten so stark. Der erste Schritt ist nicht, alle Gedanken zu stoppen, sondern zu merken: Da ist ein Kommentar — aber ich muss ihm nicht automatisch folgen.",
    tasks: [
      {
        id: "d13-t1",
        title: "Hör den Kommentar",
        trigger: "Wenn innerlich ein harter, warnender, bewertender oder drängender Gedanke auftaucht",
        when_to_use: "Bei Fehlern, Druck, Selbstkritik, Vergleich, Unsicherheit, Grübeln oder innerer Unruhe",
        action: "Greif den Gedanken in einer kurzen inneren Formulierung: 'Mein Kopf sagt gerade ...'",
        why: "Du sollst die innere Sprache nicht nur erleben, sondern als Kommentar hörbar machen.",
        explanation: "Gedanken wirken oft so schnell und direkt, dass sie wie Realität erscheinen. Heute verlangsamst du den Prozess minimal und machst den Kommentar als Kommentar sichtbar.",
        self_talk: "Mein Kopf sagt gerade ...",
        micro_reframe: "Was in mir auftaucht, ist nicht automatisch ein Befehl.",
        reframe_step: {
          trigger: "Ein lauter oder harter Gedanke taucht auf.",
          reframe: "Bevor ich ihm glaube, mache ich ihn erst einmal als Kommentar sichtbar.",
          anchor: "Mein Kopf sagt gerade ...",
        },
        system_function: "Thought Awareness",
        icon: "brain",
      },
      {
        id: "d13-t2",
        title: "Gedanke oder Befehl?",
        trigger: "Nachdem du den Kommentar gehört hast",
        when_to_use: "Direkt nach Aufgabe 1, solange der Gedanke noch Zugkraft hat",
        action: "Frag dich kurz: 'Ist das gerade ein Gedanke — oder behandle ich ihn schon wie einen Befehl?'",
        why: "Tag 13 soll die Befehlskraft innerer Sprache brechen, nicht nur Gedanken benennen.",
        explanation: "Viele Gedanken wirken nicht nur wie Information, sondern wie Handlungsanweisung. Genau diese automatische Gehorsamsreaktion soll heute sichtbar werden.",
        self_talk: "Gedanke oder Befehl?",
        micro_reframe: "Nicht jeder innere Satz verdient sofort Gehorsam.",
        reframe_step: {
          trigger: "Der Gedanke zieht direkt mein Verhalten mit.",
          reframe: "Jetzt prüfe ich: Rede ich hier mit einem Befehl — oder mit einem Ereignis?",
          anchor: "Gedanke oder Befehl?",
        },
        system_function: "Defusion Check",
        icon: "shield",
      },
      {
        id: "d13-t3",
        title: "Zurück an die Aufgabe",
        trigger: "Wenn du merkst, dass ein Gedanke Verhalten, Fokus oder Körper übernehmen will",
        when_to_use: "In der direkt nächsten Aktion oder Szene",
        action: "Binde dein Verhalten bewusst zurück an die Aufgabe statt an den Kommentar.",
        why: "Tag 13 soll Gedankenarbeit direkt mit Verhalten verknüpfen.",
        explanation: "Es reicht nicht, nur zu erkennen, dass ein Gedanke da ist. Heute trainierst du, Verhalten nicht automatisch von innerer Sprache dirigieren zu lassen, sondern wieder an die Aufgabe zu koppeln.",
        self_talk: "Zurück an die Aufgabe.",
        micro_reframe: "Mein Kommentar muss nicht mein Regisseur sein.",
        reframe_step: {
          trigger: "Ich merke, dass der Gedanke mich zieht.",
          reframe: "Jetzt führe ich mein Verhalten zurück an die reale Aufgabe.",
          anchor: "Zurück an die Aufgabe.",
        },
        system_function: "Behavior Rebinding",
        icon: "target",
      },
    ],
    journal: {
      title: "Welche Gedanken wollten heute mein Regisseur sein?",
      questions: [
        { id: "d13-j1", question: "Welche inneren Kommentare waren heute am lautesten oder am häufigsten?", placeholder: "Schreib sie möglichst konkret auf." },
        { id: "d13-j2", question: "Wann hat sich ein Gedanke heute eher wie ein Befehl als wie ein inneres Ereignis angefühlt?", placeholder: "Beschreibe die Situation." },
        { id: "d13-j3", question: "Konnte ich heute mindestens einmal merken: Das ist ein Gedanke, kein Regisseur?", placeholder: "Was hat das verändert?" },
        { id: "d13-j4", question: "Wann habe ich mein Verhalten trotz innerem Kommentar zurück an die Aufgabe gebunden?", placeholder: "Wie sah das konkret aus?" },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — mindestens 1 leichte, 1 schwierige und 1 Sache, die dir gezeigt hat, dass Gedanken nicht automatisch dein Verhalten führen müssen.",
      free_reflection_prompt: "Was zeigt mir dieser Tag über meine innere Sprache und ihre Befehlskraft?",
    },
    gratitude_prompt: "Welche Situation heute hat mir gezeigt, dass ein Gedanke nicht automatisch mein Regisseur sein muss?",
    self_talk_anchors: [
      { text: "Mein Kopf sagt gerade ...", when: "Wenn der innere Kommentar laut wird" },
      { text: "Gedanke oder Befehl?", when: "Wenn du Zugkraft im Gedanken spürst" },
      { text: "Zurück an die Aufgabe.", when: "Wenn du Verhalten wieder anbinden willst" },
    ],
    variants: {
      training: "Nutze Fehler, Druck, Selbstkritik, Vergleich und innere Warnsätze als Hauptmaterial.",
      rest: "Übertrage den Tag auf Vergleich, Grübeln, Prokrastination, Social Media, Gespräche und Entscheidungen im Alltag.",
      match: "Kurzversion: Kommentar hören → Gedanke oder Befehl? → zurück an die Aufgabe.",
    },
  },
  {
    day_id: 14,
    title: "Ergebnisdenken raubt Gegenwart",
    phase: "Phase I — Sichtbar werden",
    week: 2,
    line: "Process vs Result",
    lens: "Sobald mein Fokus zu stark am Ausgang hängt, verliere ich oft Gegenwart und Prozessqualität.",
    primary_mechanism: "Outcome Attentional Capture",
    today_trigger: "Sobald dein Kopf auf Ausgang, Bewertung, Endresultat oder spätere Konsequenzen springt, statt bei der aktuellen Aufgabe zu bleiben, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von Ergebnisbindung zu Prozesspunkt und Gegenwart.",
    science_bite: "Ergebnisdenken wirkt oft wie Fokus, ist aber häufig Aufmerksamkeitsraub. Sobald dein Kopf stärker beim Ausgang als bei der aktuellen Aufgabe lebt, steht dir weniger Präsenz für Wahrnehmung, Entscheidung und Ausführung zur Verfügung. Der Prozess ist deshalb nicht eine nette Idee, sondern dein eigentlicher Arbeitsort.",
    tasks: [
      {
        id: "d14-t1",
        title: "Erkenne den Ausgangs-Zug",
        trigger: "Wenn dein Kopf stark zum Ergebnis, zu Bewertung oder zu späteren Konsequenzen zieht",
        when_to_use: "Vor wichtigen Szenen, nach Fehlern, unter Beobachtung, in Druckphasen oder wenn es 'zählen' soll",
        action: "Frag dich kurz: 'Bin ich gerade beim Ausgang — oder bei der Aktion?'",
        why: "Du sollst Ergebnisbindung zuerst als Aufmerksamkeitsproblem erkennen.",
        explanation: "Viele Spieler denken, sie müssten ans Ergebnis denken, um ernst zu sein. In Wahrheit zieht sie genau das oft aus der Gegenwart. Heute machst du diesen Ausgangs-Zug sichtbar.",
        self_talk: "Ausgang oder Aktion?",
        micro_reframe: "Ergebnisdenken fühlt sich wichtig an, zieht mich aber oft aus meiner eigentlichen Arbeit.",
        reframe_step: {
          trigger: "Mein Kopf springt zum Ausgang.",
          reframe: "Bevor ich weiter in Richtung Ergebnis kippe, prüfe ich meinen aktuellen Aufmerksamkeitsort.",
          anchor: "Ausgang oder Aktion?",
        },
        system_function: "Outcome Awareness",
        icon: "eye",
      },
      {
        id: "d14-t2",
        title: "Finde deinen Prozesspunkt",
        trigger: "Nachdem du Ergebnisbindung erkannt hast",
        when_to_use: "Direkt danach, bevor du weiter in Bewertung oder Zukunft gehst",
        action: "Bestimme eine konkrete Sache, die jetzt wirklich deine Aufgabe ist.",
        why: "Der Prozess wird nur dann handhabbar, wenn er konkret statt diffus ist.",
        explanation: "Nicht 'mehr fokussiert sein'. Nicht 'im Moment bleiben'. Sondern etwas Klareres: erster Kontakt, Laufweg, Körperspannung, Kommunikation, Timing, Haltung, Ballattacke, nächste technische Aufgabe.",
        self_talk: "Mein Prozesspunkt ist ...",
        micro_reframe: "Ich brauche nicht den ganzen Ausgang. Ich brauche meinen nächsten Arbeitsort.",
        reframe_step: {
          trigger: "Ich habe den Ausgangs-Zug erkannt.",
          reframe: "Jetzt gebe ich meiner Aufmerksamkeit wieder einen konkreten Prozesspunkt.",
          anchor: "Mein Prozesspunkt ist ...",
        },
        system_function: "Process Redirect",
        icon: "target",
      },
      {
        id: "d14-t3",
        title: "Bewerte später, handle jetzt",
        trigger: "Wenn dein Kopf die Szene schon bewerten, absichern oder gegen spätere Folgen kontrollieren will",
        when_to_use: "In der direkt nächsten Aktion oder Szene",
        action: "Schieb Bewertung bewusst nach hinten und geh jetzt voll an deinen Prozesspunkt.",
        why: "Der Tag soll nicht nur Erkenntnis bringen, sondern dein Verhalten wieder in Gegenwart und Aufgabe verankern.",
        explanation: "Bewerten kannst du später. Heute ist entscheidend: Bin ich gerade an meiner Aufgabe oder schon im Ergebnisfilm? Du trainierst, Handlung und Präsenz wieder vor Bewertung zu setzen.",
        self_talk: "Bewertung später.",
        micro_reframe: "Nicht jede Szene muss sofort beurteilt werden. Erst arbeiten, dann auswerten.",
        reframe_step: {
          trigger: "Ich will die Szene schon absichern oder bewerten.",
          reframe: "Jetzt arbeite ich erst. Bewertung kann warten.",
          anchor: "Bewertung später.",
        },
        system_function: "Process Protection",
        icon: "shield",
      },
    ],
    journal: {
      title: "Wo hat mich Ergebnisdenken heute aus der Aufgabe gezogen?",
      questions: [
        { id: "d14-j1", question: "In welchen Momenten war mein Kopf heute stärker beim Ausgang als bei der aktuellen Aktion?", placeholder: "Beschreibe die Situation." },
        { id: "d14-j2", question: "Was war in dieser Situation mein konkreter Prozesspunkt?", placeholder: "Woran konntest du wirklich arbeiten?" },
        { id: "d14-j3", question: "Konnte ich mindestens einmal Bewertung nach hinten schieben und wieder an die Aufgabe gehen?", placeholder: "Wie sah das konkret aus?" },
        { id: "d14-j4", question: "Was zeigt mir das darüber, wie stark Ergebnisbindung noch meine Gegenwart raubt?", placeholder: "Formuliere den Kern möglichst klar." },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas aus einem Moment, in dem dein Kopf laut beim Ausgang war.",
      free_reflection_prompt: "Was zeigt mir dieser Tag über meinen Aufmerksamkeitsort unter Bedeutung, Bewertung oder Druck?",
    },
    gratitude_prompt: "Welche Situation heute hat mir gezeigt, dass Prozess nicht Theorie, sondern mein Arbeitsort ist?",
    self_talk_anchors: [
      { text: "Ausgang oder Aktion?", when: "Wenn dein Kopf zum Ergebnis zieht" },
      { text: "Mein Prozesspunkt ist ...", when: "Wenn du den Arbeitsort konkret machen willst" },
      { text: "Bewertung später.", when: "Wenn du dich wieder an Gegenwart binden willst" },
    ],
    variants: {
      training: "Nutze Druckphasen, Fehler, Beobachtung, Vergleich und bedeutungsvolle Szenen als Material.",
      rest: "Übertrage den Tag auf Zukunftsdenken, Erwartungen, Leistungsgrübeln und Alltagssituationen mit Ergebnisbindung.",
      match: "Kurzversion: Ausgang oder Aktion? → Prozesspunkt finden → Bewertung später.",
    },
  },
  {
    day_id: 15,
    title: "Präsenz kann aktiv zurückgeholt werden",
    phase: "Phase II — Umcodieren",
    week: 3,
    line: "Presence",
    lens: "Präsenz ist nicht nur etwas, das ich verliere oder habe — ich kann sie aktiv wiederherstellen.",
    primary_mechanism: "Attentional Reset",
    today_trigger: "Sobald du merkst, dass dein Kopf weg ist oder Ergebnis, Gedanken, Fehler oder Spannung dich aus der Gegenwart ziehen, ist der Tag aktiv.",
    core_shift: "Heute verschiebst du dich von Präsenz als Beobachtung zu Präsenz als steuerbarer Rückkehrbewegung.",
    science_bite: "In Woche 1 ging es darum, Drift überhaupt zu erkennen. Ab heute beginnt etwas Neues: Rückkehr wird trainierbar. Dein System muss nicht darauf warten, dass Präsenz einfach wiederkommt. Es kann lernen, einen klaren Rückkehrimpuls zu setzen und Aufmerksamkeit aktiv an die Aufgabe zurückzubinden.",
    tasks: [
      {
        id: "d15-t1",
        title: "Erkenne den Verlust schneller",
        trigger: "Wenn du merkst, dass dein Fokus weggeht oder Ergebnis, Gedanken, Fehler oder Spannung dich ziehen",
        when_to_use: "In echten Leistungssituationen, nach Fehlern, in Druckmomenten oder wenn dein Kopf plötzlich nicht mehr bei der Szene ist",
        action: "Markiere den Verlust früher und klarer: 'Nicht da.'",
        why: "Phase II beginnt nicht mit Perfektion, sondern mit schnellerer und präziserer Rückkehrvorbereitung.",
        explanation: "Der Unterschied zu Tag 1 ist heute: Du sollst den Verlust nicht nur irgendwann bemerken, sondern früher und direkter. Je früher du ihn erkennst, desto kleiner wird der Abstand zur Rückkehr.",
        self_talk: "Nicht da.",
        micro_reframe: "Der Verlust ist nicht das Ende der Präsenz, sondern der Startpunkt der Rückkehr.",
        reframe_step: {
          trigger: "Ich merke, dass mein Kopf weg ist.",
          reframe: "Gut — jetzt setze ich die Rückkehr bewusst ein, statt nur den Verlust zu registrieren.",
          anchor: "Nicht da.",
        },
        system_function: "Faster Awareness",
        icon: "eye",
      },
      {
        id: "d15-t2",
        title: "Setze das Rückkehrsignal",
        trigger: "Direkt nachdem du den Verlust erkannt hast",
        when_to_use: "Sofort nach Aufgabe 1, bevor dein Kopf wieder in Bewertung, Ausgang oder Kommentar kippt",
        action: "Setze bewusst dein Rückkehrsignal und richte deinen Fokus sofort an einen klaren Aufmerksamkeitsanker.",
        why: "Präsenz soll ab heute nicht nur bemerkt, sondern aktiv zurückgeholt werden.",
        explanation: "Das Rückkehrsignal ist kein Motivationsspruch, sondern ein praktischer Umschaltmoment. Es sagt deinem System: Zurück. Hier. Diese Sache. Der Anker muss konkret sein: Ball, Kontakt, Gegner, Position, Atmung, Kommunikation, Prozesspunkt.",
        self_talk: "Zurück. Hier.",
        micro_reframe: "Ich muss nicht warten, bis ich wieder präsent bin. Ich kann Präsenz bewusst einleiten.",
        reframe_step: {
          trigger: "Ich habe den Verlust erkannt.",
          reframe: "Jetzt setze ich nicht nur Einsicht, sondern aktive Rückkehr.",
          anchor: "Zurück. Hier.",
        },
        system_function: "Active Reset",
        icon: "sunrise",
      },
      {
        id: "d15-t3",
        title: "Verankere die Rückkehr in Handlung",
        trigger: "Nachdem du deinen Aufmerksamkeitsanker wieder gesetzt hast",
        when_to_use: "In der direkt nächsten Aktion",
        action: "Zeige die Rückkehr sofort in einer klaren, sauberen Handlung.",
        why: "Präsenz wird nur dann stabiler, wenn Rückkehr nicht nur innerlich, sondern auch verhaltensbezogen gespeichert wird.",
        explanation: "Nicht nur wieder 'fokussiert fühlen' wollen. Sondern in der nächsten Szene sichtbar machen: klarer Kontakt, wieder anbieten, sauberer Laufweg, klare Kommunikation, aktivere Präsenz.",
        self_talk: "Zeig die Rückkehr.",
        micro_reframe: "Die Rückkehr ist erst vollständig, wenn sie in meiner Handlung sichtbar wird.",
        reframe_step: {
          trigger: "Ich habe den Anker wieder gesetzt.",
          reframe: "Jetzt speichere ich die Rückkehr durch eine sichtbare saubere Handlung.",
          anchor: "Zeig die Rückkehr.",
        },
        system_function: "Embodied Return",
        icon: "target",
      },
    ],
    journal: {
      title: "Wie habe ich Präsenz heute aktiv zurückgeholt?",
      questions: [
        { id: "d15-j1", question: "In welchen Momenten habe ich heute schneller gemerkt, dass ich nicht mehr ganz da war?", placeholder: "Beschreibe die Situation." },
        { id: "d15-j2", question: "Welches Rückkehrsignal oder welcher Aufmerksamkeitsanker hat heute am besten funktioniert?", placeholder: "Was hat dich konkret zurückgebracht?" },
        { id: "d15-j3", question: "Konnte ich die Rückkehr heute mindestens einmal direkt in Handlung sichtbar machen?", placeholder: "Wie sah diese Handlung aus?" },
        { id: "d15-j4", question: "Was zeigt mir das darüber, wie steuerbar Präsenz für mich bereits werden kann?", placeholder: "Formuliere die Einsicht möglichst klar." },
      ],
      gratitude_instruction: "Schreibe 5 Dinge auf, für die du heute dankbar bist — auch etwas aus einem Moment, in dem du Präsenz bewusst zurückgeholt hast.",
      free_reflection_prompt: "Was zeigt mir dieser Tag über den Unterschied zwischen Präsenz bemerken und Präsenz aktiv wiederherstellen?",
    },
    gratitude_prompt: "Welcher Moment heute hat mir gezeigt, dass Präsenz nicht nur verloren gehen, sondern auch bewusst zurückkommen kann?",
    self_talk_anchors: [
      { text: "Nicht da.", when: "Wenn du den Verlust schneller erkennst" },
      { text: "Zurück. Hier.", when: "Wenn du das Rückkehrsignal setzt" },
      { text: "Zeig die Rückkehr.", when: "In der direkt nächsten Handlung" },
    ],
    variants: {
      training: "Nutze Fehler, Ergebnisdenken, Druck, innere Kommentare und Spannungsmomente als Material für aktive Rückkehr.",
      rest: "Übertrage den Tag auf Handy, Gespräche, Grübeln, Unruhe und Alltagssituationen, in denen dein Kopf weggeht.",
      match: "Kurzversion: Verlust früher merken → Rückkehrsignal setzen → Rückkehr in Handlung zeigen.",
    },
  },
];
