/**
 * Freiwillige Vertiefung für das 56-Tage-Programm.
 *
 * Diese Texte erklären den Tagesgedanken in klarer Alltagssprache. Sie sind
 * bewusst keine zweite Mission und kein Ersatz für den kurzen Science Bite.
 * Training, Wettkampf und Ruhetag teilen dieselbe Bedeutung; nur die konkrete
 * Ausführung wird vom bestehenden Kontext-Adapter verändert.
 */
export const PROGRAM_DAY_EXPLANATIONS: Record<number, string> = {
  1: "Dein Kopf wird im Training immer wieder abschweifen. Vielleicht hängst du noch bei einem Fehler, denkst an das Ergebnis oder fragst dich, was andere über dich denken. Das Problem ist nicht, dass das passiert. Entscheidend ist, dass du es bemerkst. Sobald du merkst, dass dein Kopf weg ist, fragst du dich: Was ist jetzt meine nächste Aktion? Dann richtest du deinen Blick und deine Handlung genau darauf.",
  2: "Manchmal bist du mehr damit beschäftigt, wie du wirkst, als mit dem, was du gerade tun musst. Du willst sicher, stark oder fehlerfrei aussehen. Dadurch fehlt dir Aufmerksamkeit für die eigentliche Aufgabe. Frag dich deshalb: Was braucht die Aufgabe gerade wirklich? Wähle eine passende Qualität wie Ruhe, Mut, Geduld oder klare Kommunikation und zeig sie in deiner nächsten Handlung.",
  3: "Du kennst den Weg zurück zur nächsten Aktion bereits. Heute geht es darum, dass dir dieser Weg schneller und mit weniger Hilfe einfällt. Versuch deinen Satz zuerst selbst zu erinnern. Verbinde ihn danach sofort mit einer konkreten Handlung. So bleibt der Satz nicht nur etwas, das dir bekannt vorkommt, sondern wird zu etwas, das du wirklich nutzen kannst.",
  4: "Du hast gerade einen Fehler gemacht. Das kannst du nicht mehr ändern, aber der Fehler kann dir zeigen, woran du noch arbeiten kannst. Wenn du dich weiter darüber aufregst oder dich selbst bewertest, fehlt dir Aufmerksamkeit für die nächste Situation. Hol deshalb genau eine brauchbare Information aus dem Fehler und nutze sie bei deiner nächsten passenden Handlung.",
  5: "Die Frage nach der Aufgabe hilft dir nur, wenn daraus eine klare Handlung entsteht. Frag dich nicht nur, was die Aufgabe braucht. Entscheide dich für genau eine Qualität, die jetzt wichtig ist. Das kann zum Beispiel Ruhe, Tempo, Mut oder klare Kommunikation sein. Zeig diese Qualität anschließend in deiner nächsten Handlung.",
  6: "Etwas kann unfair, ärgerlich oder enttäuschend sein. Du musst es nicht gut finden. Wenn du aber weiter gegen etwas kämpfst, das du gerade nicht ändern kannst, fehlt dir Kraft für deinen eigenen Handlungsspielraum. Trenne deshalb klar: Was steht fest und was kann ich noch beeinflussen? Dann handelst du an genau diesem Punkt weiter.",
  7: "Zuerst musst du merken, wo deine Aufmerksamkeit gerade ist. Erst danach kannst du entscheiden, wie du handeln willst. Wenn dein Kopf beim Ergebnis, bei deiner Wirkung oder bei einem inneren Kommentar hängt, komm zuerst zur nächsten Aktion zurück. Falls noch unklar ist, wie du sie ausführen willst, fragst du danach, welche Qualität die Aufgabe braucht. Du bearbeitest nicht alles gleichzeitig, sondern gehst Schritt für Schritt.",
  8: "Ein Gedanke oder Gefühl kann sich sehr stark anfühlen und dich sofort zu einer Handlung drängen. Vielleicht willst du dich zurückziehen, etwas vermeiden oder hektisch reagieren. Du musst den Gedanken nicht wegdrücken. Bemerke kurz, was gerade in dir passiert, und erinnere dich daran: Das ist kein Befehl. Danach entscheidest du, welche Handlung wirklich zu deiner Aufgabe passt.",
  9: "Nach einem Fehler kann dein Kopf sofort viele Ursachen und Korrekturen suchen. In der laufenden Situation ist das meistens zu viel. Eine brauchbare Information reicht, damit du wieder handeln kannst. Die größere Analyse darf später kommen. Heute trainierst du, eine kleine Korrektur mitzunehmen und deine Aufmerksamkeit wieder voll auf die nächste Handlung zu richten.",
  10: "Nur weil sich eine Handlung unsicher anfühlt, bedeutet das nicht, dass sie falsch ist. Es bedeutet aber auch nicht automatisch, dass du sie machen solltest. Prüfe zuerst: Ist die Handlung sicher, erlaubt und für die Aufgabe sinnvoll? Wenn ja, probiere sie kontrolliert aus. Du musst dir damit nichts beweisen. Du triffst eine klare sportliche Entscheidung und bekommst echtes Feedback.",
  11: "Ein Problem kann real und ärgerlich sein. Zusätzlich kann dein Kopf immer wieder fordern, dass es anders sein müsste. Dieser zusätzliche Kampf verändert die Situation nicht, bindet aber weiter deine Aufmerksamkeit. Du sollst deinen Ärger nicht verbieten. Erkenne nur, wann du immer wieder gegen denselben unveränderbaren Punkt kämpfst, und richte dich dann auf das aus, was noch bei dir liegt.",
  12: "Du kannst hohe Qualität zeigen, weil die Aufgabe sie braucht. Du kannst aber auch versuchen, dir oder anderen damit etwas zu beweisen. Von außen kann beides ähnlich aussehen. Wenn du etwas beweisen willst, bleibt ein Teil deiner Aufmerksamkeit bei deinem Bild. Dein Anspruch darf hoch bleiben. Lass nur die Aufgabe entscheiden, wie dieser Anspruch in deiner Handlung aussieht.",
  13: "Ein erster Gedanke kann dich sehr schnell in eine Richtung ziehen. Vielleicht sagt dein Kopf: Lass es, geh kein Risiko ein oder jetzt musst du es allen zeigen. Wenn du diesen ersten Impuls bemerkst, entsteht ein kurzer Moment, in dem du wieder selbst entscheiden kannst. Du musst den Gedanken nicht entfernen. Du entscheidest nur, ob die Handlung, zu der er dich drängt, wirklich zu deiner Aufgabe passt.",
  14: "Du darfst gewinnen und ein bestimmtes Ergebnis erreichen wollen. Während der aktuellen Aktion brauchst du deine Aufmerksamkeit aber bei der Ausführung. Wenn dein Kopf schon beim Ausgang, beim Stand oder bei den Folgen ist, merkst du das kurz und kommst zur nächsten Handlung zurück. Du gibst dein Ziel nicht auf. Du konzentrierst dich auf den Teil, den du gerade wirklich beeinflussen kannst.",
  15: "Wenn etwas schiefläuft, kann dieses eine Problem deine ganze Aufmerksamkeit einnehmen. Das Problem ist real, aber es ist meistens nicht die gesamte Situation. Frag dich deshalb: Was ist außerdem da? Vielleicht funktioniert trotzdem etwas, jemand hilft dir oder du hast noch eine andere Möglichkeit. Du sollst nichts schönreden. Du öffnest deinen Blick, damit du mehr von der Realität siehst und besser entscheiden kannst.",
  16: "Dein Kopf kann auch bei einer sinnvollen Handlung weiter auf vollständige Sicherheit warten. Dann wird Warten schnell zur Gewohnheit. Prüfe deshalb die reale Situation: Ist die Handlung sicher, erlaubt und passend vorbereitet? Wenn ja, wähle einen angemessenen Versuch. Du gehst kein blindes Risiko ein. Du lässt Unsicherheit nur nicht automatisch jede sinnvolle Handlung stoppen.",
  17: "Nach einem Fehler willst du vielleicht sofort viele Dinge korrigieren. Für die nächste Handlung ist eine kleine, klare Veränderung oft hilfreicher. Entscheide, welche eine Korrektur dir jetzt am meisten bringt, und setze sie beim nächsten passenden Versuch um. Alles, was mehr Analyse braucht, kannst du dir für später merken. So bleibst du lernfähig, ohne dich in der Situation zu überladen.",
  18: "Müdigkeit, Frust oder fehlende Motivation können real sein. Du musst diese Gefühle nicht wegreden. Prüfe ehrlich, was heute sicher und sinnvoll möglich ist. Danach richtest du dich auf den nächsten passenden Schritt aus. Dieser Schritt darf kleiner sein als sonst. Wichtig ist, dass dein aktueller Zustand nicht automatisch jede noch mögliche Handlung für dich entscheidet.",
  19: "Ärger entsteht manchmal in einer Situation und wird danach durch dieselben Gedanken immer weiter verstärkt. Dein Kopf spielt den Moment erneut ab, fügt neue Urteile hinzu und hält die Spannung aktiv. Du musst die erste Reaktion nicht verhindern. Bemerke nur, wenn du denselben unveränderbaren Moment erneut fütterst. Dann fragst du, was du jetzt beeinflussen kannst, und gibst dieser Handlung deine Aufmerksamkeit.",
  20: "Schnelle Reaktionen wirken oft wie ein einziger Ablauf. Tatsächlich passiert zuerst etwas, dann taucht ein Gedanke oder Gefühl auf, daraus entsteht ein Impuls und danach handelst du. Wenn du diese Schritte erkennst, findest du den kurzen Moment, in dem du selbst entscheiden kannst. Heute geht es nicht darum, alles langsam zu machen. Du willst nur den Punkt erkennen, an dem eine andere Handlung möglich wird.",
  21: "Wenn du dich stark mit deiner Wirkung, Bewertung oder Position beschäftigst, hilft dir die Frage nach deinem Beitrag. Im Team kann das Kommunikation, Unterstützung oder eine klare Rolle sein. Im Einzelsport kann es Vorbereitung, Disziplin oder eine saubere Ausführung sein. Frag dich: Was braucht die Aufgabe gerade von mir? Wähle einen konkreten Beitrag und mach ihn in deiner nächsten Handlung sichtbar.",
  22: "Unter Belastung kann ein Problem fast dein gesamtes Bild bestimmen. Andere reale Informationen sind weiterhin da, bekommen aber kaum noch Aufmerksamkeit. Wenn du deinen Blick öffnest, ersetzt oder verkleinerst du das Problem nicht. Du nimmst zusätzlich wahr, was funktioniert, was dich trägt und was noch möglich ist. Mit diesem vollständigeren Bild kannst du deine nächste Handlung klarer wählen.",
  23: "Eine unsichere Handlung kann sich wie eine Prüfung deiner ganzen Person anfühlen. Dann wirkt ein möglicher Fehler größer, als er für die eigentliche Aufgabe ist. Prüfe die Handlung deshalb nach ihrem wirklichen Nutzen: Ist sie sicher, hilft sie der Aufgabe und kannst du etwas daraus lernen? Das Ergebnis des Versuchs entscheidet nicht über deinen Wert. Du entscheidest nur, ob dieser Versuch gerade sinnvoll ist.",
  24: "Eine gute Handlung macht dich nicht sofort zu einem anderen Menschen. Sie zeigt dir aber, welches Verhalten du wiederholen kannst. Denk an eine konkrete Situation, in der du bewusst gut nach deiner Aufgabe gehandelt hast. Benenne, was du wirklich getan hast und welche Qualität darin sichtbar wurde. Danach überlegst du, wie du genau diese Qualität in einer neuen Situation wieder zeigen kannst.",
  25: "Zweifel, Unlust oder Unsicherheit können auch dann da sein, wenn eine Handlung sinnvoll und möglich ist. Wenn du immer wartest, bis dein Inneres voll zustimmt, entscheidet dein momentaner Zustand für dich. Bemerke deshalb ehrlich, was gerade in dir auftaucht. Prüfe danach, was die Aufgabe wirklich braucht. Dann entscheidest du selbst, ohne auf ein anderes Gefühl warten zu müssen.",
  26: "Eine unsichere Situation kann sich im ersten Moment gefährlich oder peinlich anfühlen. Reale Gefahr nimmst du immer ernst. Wenn keine reale Gefahr besteht, prüfst du genauer: Bin ich vorbereitet, passt die Handlung zur Aufgabe und wie kann ein sicherer nächster Schritt aussehen? Du ignorierst dein Gefühl nicht. Du prüfst nur, ob dein erster Eindruck schon die ganze Situation zeigt.",
  27: "Du kannst nicht garantieren, dass eine Handlung gelingt. Du kannst aber beeinflussen, mit welcher Qualität du sie ausführst. Wenn der Ausgang offen ist, fragst du deshalb nicht nur, wie du einen Fehler vermeiden kannst. Frag dich, was die Aufgabe jetzt braucht: zum Beispiel Mut, Geduld, Klarheit oder Präzision. Dann übernimmst du Verantwortung für deine Ausführung, auch wenn das Ergebnis unsicher bleibt.",
  28: "Du hast bisher verschiedene Wege kennengelernt, mit Fehlern, Druck, Unsicherheit, Gedanken und fehlendem Fokus umzugehen. Heute kommt nichts Neues dazu. Denk an eine Situation, in der du festgehangen hast, und finde zuerst heraus, was genau das Problem war. Wähle danach eine bekannte Reaktion, die dir dort wirklich geholfen hätte. Du brauchst nicht alles gleichzeitig. Eine passende Reaktion reicht.",
  29: "Oft merkst du erst spät, dass deine Aufmerksamkeit schon länger weg ist. Vorher gab es meistens ein kleines Signal: Dein Blick blieb hängen, ein Gedanke wiederholte sich oder du hast nur noch halb zugehört. Denk rückblickend an dieses erste Signal. Wenn du es beim nächsten Mal bemerkst, nutzt du sofort deinen bekannten Satz. Dadurch wird der Weg zurück kürzer.",
  30: "Eine intensive oder sichtbare Handlung kann der Aufgabe helfen. Sie kann aber auch vor allem dazu dienen, stark oder besonders zu wirken. Frag dich deshalb, welche Qualität die Aufgabe wirklich braucht und welchen konkreten Beitrag deine Handlung leistet. Du darfst intensiv und mutig handeln. Du entfernst nur den zusätzlichen Druck, mit dieser Handlung etwas über dich beweisen zu müssen.",
  31: "Nach einem Fehler passiert oft mehr als nur die falsche Aktion. Ein Urteil über dich taucht auf, dein Blick wird enger und deine nächste Handlung verändert sich. Wenn du diesen Ablauf erkennst, kannst du früher eingreifen. Trenne den Fehler von dem Urteil, das dein Kopf daraus macht. Hol eine brauchbare Information heraus und entscheide danach neu, wie du handeln willst.",
  32: "Du hast etwas erlebt, das du nicht mehr ändern kannst. Vielleicht war es unfair, frustrierend oder einfach anders, als du es wolltest. Dein Kopf kann trotzdem immer wieder daran festhalten. Beschreibe kurz, was wirklich passiert ist, und bemerke die Gedanken, die dich weiter daran binden. Frag dich dann: Was kann ich jetzt beeinflussen? Nutze genau eine Antwort und geh dort weiter.",
  33: "Etwas passiert, ein Gedanke oder Gefühl taucht auf und kurz danach willst du reagieren. Diese Schritte laufen oft so schnell, dass sie wie eine einzige automatische Reaktion wirken. Benenne zuerst, was gerade in dir auftaucht. Erkenne dann, zu welcher Handlung es dich drängt. Genau dort kannst du entscheiden, ob diese Handlung wirklich zu deiner Aufgabe passt.",
  34: "Eine Herausforderung kann zu groß, schlecht vorbereitet oder wirklich gefährlich sein. Sie kann aber auch nur ungewohnt und trotzdem sinnvoll sein. Prüfe deshalb Sicherheit und Vorbereitung. Passe danach Größe, Tempo oder Schwierigkeit so an, dass ein sinnvoller nächster Versuch entsteht. Du suchst weder das größte Risiko noch die leichteste Lösung, sondern einen Schritt, an dem du lernen kannst.",
  35: "In einer belastenden Situation hat dein Blick vielleicht fast nur noch das Problem aufgenommen. Andere Informationen waren weiterhin da, aber für deine Entscheidung kaum noch sichtbar. Geh diese Szene noch einmal durch. Finde zwei reale Dinge, die du damals nicht wahrgenommen hast. Frag dich danach, welche neue Handlung durch das vollständigere Bild möglich geworden wäre.",
  36: "Wenn viele Reize, Fehler oder Gedanken gleichzeitig auf dich einwirken, kann deine Aufmerksamkeit in alle Richtungen gehen. Du musst nicht alles auf einmal lösen. Bemerke kurz, dass dein Kopf gerade überall ist. Wähle dann genau eine nächste Aktion und richte Blick und Handlung darauf. Eine klare Aktion gibt deiner Aufmerksamkeit auch im Chaos wieder eine Richtung.",
  37: "Manchmal weißt du, welche Qualität die Aufgabe braucht, aber die Ausführung fühlt sich noch unsicher an. Bestimme zuerst die Qualität, die heute führt. Prüfe danach, in welcher Größe und Form du sie sicher zeigen kannst. Dann führst du genau diesen Versuch aus. So bleiben Aufgabenqualität und Sicherheitsprüfung verbunden, ohne zu zwei konkurrierenden Aufgaben zu werden.",
  38: "Nach einem Fehler können zwei Dinge gleichzeitig passieren: Du bekommst eine brauchbare Information und du ärgerst dich über etwas, das bereits feststeht. Trenne beides. Nimm aus deinem eigenen Anteil genau eine Korrektur mit. Den unveränderbaren Teil musst du nicht gut finden, aber du musst ihn auch nicht in die nächste Handlung tragen.",
  39: "Nach einem Fehler taucht vielleicht sofort ein harter Satz auf: Ich kann das nicht oder jetzt ist alles weg. Dieser Satz fühlt sich wichtig an, ist aber zuerst nur ein Gedanke. Bemerke ihn, ohne ihm automatisch zu folgen. Prüfe danach sachlich, welche Information wirklich im Fehler steckt. Diese Information und nicht der erste innere Satz bestimmt deine nächste Handlung.",
  40: "Eine schwierige Handlung ist nicht automatisch besser. Sie kann der Aufgabe helfen, dir eine sinnvolle Lernchance geben oder nur spektakulär wirken. Prüfe deshalb, was die Aufgabe braucht, ob die Handlung sicher ist und was du wirklich daraus lernen kannst. Du musst Schwierigkeit weder suchen noch vermeiden. Du wählst die Handlung mit dem größten sinnvollen Nutzen.",
  41: "Wenn Fehler, Müdigkeit und Spannung sich stapeln, siehst du oft nur noch, was zusätzlich nicht funktioniert. Du musst diese Belastung nicht schönreden. Nimm sie ehrlich wahr und öffne danach deinen Blick für weitere reale Informationen. Was funktioniert trotzdem, wer oder was hilft dir und welche kleine Möglichkeit bleibt? Wähle daraus eine Handlung, die wirklich in deinem Einfluss liegt.",
  42: "Wenn mehrere Reaktionen nacheinander kommen, wirkt die ganze Situation schnell kompliziert. Vielleicht ist zuerst dein Fokus weg, dann kämpfst du gegen das Geschehene und danach übernimmt ein Gedanke. Du musst nicht alles gleichzeitig bearbeiten. Finde die Stelle, an der du gerade wirklich festhängst. Wähle dann genau eine bekannte Reaktion, die dich von dort zur nächsten Handlung bringt.",
  43: "Du kennst den Satz für den Rückweg inzwischen. Heute brauchst du nicht noch einmal die ganze Erklärung. Achte auf das erste kleine Zeichen, dass deine Aufmerksamkeit weggeht. Versuch deinen Satz selbst zu erinnern und benenne danach sofort deine nächste Aktion. Das Ziel ist nicht, dass du mehr weißt, sondern dass dir das Gelernte im richtigen Moment schneller zur Verfügung steht.",
  44: "Eine wichtige Handlung kann sich wie ein Test deiner ganzen Person anfühlen. Dann willst du vielleicht besonders stark, perfekt oder beeindruckend handeln. Dein Anspruch darf hoch bleiben. Frag dich aber, welche Qualität die Aufgabe wirklich braucht, und führe sie ruhig aus. Du musst mit einer einzelnen Handlung weder deinen Wert noch deine gesamte Entwicklung beweisen.",
  45: "Ein Fehler beschreibt eine misslungene Handlung, nicht deinen Wert als Mensch oder Athlet. Beschreibe deshalb zuerst sachlich, was passiert ist. Wähle eine Information, die du beim nächsten Versuch nutzen kannst. Dann gehst du wieder in die Handlung. Du machst den Fehler nicht kleiner, aber auch nicht größer, als er wirklich ist.",
  46: "Du musst eine unveränderbare Situation nicht gut finden. Entscheidend ist, ob dein Kopf weiter Kraft daran bindet oder wieder eine mögliche Handlung findet. Bemerke, wenn du erneut gegen denselben feststehenden Punkt kämpfst. Ruf dann deine Einflussfrage ab und wähle genau eine Sache, die weiterhin bei dir liegt. Erfolg bedeutet heute nicht, dass dein Ärger verschwindet, sondern dass Handlung wieder möglich wird.",
  47: "Ein lauter Gedanke verschwindet nicht immer, nur weil du ihn erkennst. Du musst ihn auch nicht bekämpfen oder durch einen positiven Satz ersetzen. Benenne ihn als Gedanken und lass ihn kurz da sein. Danach wählst du deine Handlung nach der Aufgabe. Stabilität bedeutet nicht, keine schwierigen Gedanken zu haben, sondern trotz ihnen bewusster handeln zu können.",
  48: "Wenn etwas schwerer läuft als erwartet, sagt dir die Schwierigkeit noch nicht automatisch, dass du aufhören oder einfach härter kämpfen sollst. Prüfe, was sie dir wirklich zeigt. Fehlt Vorbereitung, ist der Versuch zu groß oder ist das gerade eine passende Lernchance? Passe deinen nächsten Schritt entsprechend an. So wird Schwierigkeit zu einer Information für deine Entscheidung.",
  49: "Du musst nicht warten, bis ein großes Problem deinen Blick verengt. Auch an einem normalen Tag nimmt deine Aufmerksamkeit manche Dinge wahr und lässt andere im Hintergrund. Wähle einen gewöhnlichen Moment und frag dich: Was ist außerdem da? Nimm zwei weitere reale Informationen wahr. Damit übst du einen breiteren Blick, bevor du ihn unter starker Belastung brauchst.",
  50: "Mehrere gute oder schlechte Aktionen können dich in die nächste Situation mitziehen. Vielleicht willst du etwas retten, beweisen oder nach einem Erfolg zu viel erzwingen. Bemerke, wie der bisherige Verlauf an dir zieht. Komm dann zur aktuellen Aufgabe zurück und bestimme nur für diese eine Aktion die wichtigste Qualität. Der Verlauf darf etwas mit dir machen, aber er gibt deiner nächsten Handlung nicht automatisch die Richtung.",
  51: "Nach einem Fehler bekommst du eine sportliche Information und oft gleichzeitig einen harten inneren Kommentar. Er kann dir sagen, was der Fehler über dich, den Ausgang oder die Meinung anderer bedeutet. Erkenne diesen Satz zuerst als Gedanken. Hol danach genau eine brauchbare Information aus dem Fehler. So bleibt mehr Aufmerksamkeit für deine Korrektur und die nächste Handlung.",
  52: "Ein unveränderbarer Teil der Situation kann fast dein ganzes Bild bestimmen. Benenne zuerst ehrlich, was feststeht. Öffne dann deinen Blick für weitere reale Informationen: Was funktioniert noch, welche Hilfe gibt es und was ist weiterhin möglich? Wähle daraus genau einen Punkt, den du beeinflussen kannst. Du redest die Realität nicht schön und bleibst trotzdem handlungsfähig.",
  53: "Eine schwierige Handlung sollte nicht nur mutig aussehen. Prüfe, ob sie sicher ist, der Aufgabe hilft und dir eine echte Lernchance gibt. Ein eigener persönlicher Grund kann dich dabei unterstützen, aber du musst keinen großen Sinn erfinden. Danach entscheidest du bewusst, ob du die Herausforderung annimmst, anpasst oder begründet lässt.",
  54: "Dein Kopf kann vor einer Handlung auf neue Bestätigung warten: erst noch ein Erfolg, Lob oder ein besseres Gefühl, dann kannst du sicher handeln. Bemerke, worauf du gerade wartest. Dieser Wunsch darf da sein, entscheidet aber nicht automatisch für dich. Prüfe die Aufgabe und führe die nächste passende Handlung mit dem aus, was du bereits kannst.",
  55: "Du wirst nicht dadurch zu dem Menschen oder Athleten, der du sein willst, weil du es dir einfach sagst. Du beweist es dir durch deine Handlungen. Jedes Mal, wenn du nach einem Fehler zurückkommst, trotz Unsicherheit handelst oder dich wieder auf deine Aufgabe konzentrierst, zeigst du dir, wie du handeln möchtest. Wähle zwei solche Handlungen und formuliere daraus deinen Standard für die Zukunft.",
  56: "Am Ende des Programms geht es nicht darum, ein perfekter Mensch zu sein oder immer richtig zu reagieren. Du willst erkennen, was gerade passiert, eine passende bekannte Reaktion wählen und danach handeln. Vielleicht ist dein Fokus weg, ein Fehler beschäftigt dich oder ein Gedanke zieht dich in eine Richtung. Erkenne zuerst die Art des Problems. Dann wählst du genau eine passende Reaktion und setzt sie in eine konkrete Handlung um.",
};

export const getProgramDayExplanation = (day: number): string | null =>
  PROGRAM_DAY_EXPLANATIONS[day] ?? null;
