/**
 * Freiwillige Vertiefung für das 56-Tage-Programm.
 *
 * Der Science Bite erklärt den Mechanismus. Die Mission führt die Handlung.
 * Diese Texte schließen stattdessen eine Verständnislücke: Sie zeigen eine
 * universelle Sportsituation, grenzen ein typisches Missverständnis ab oder
 * erklären, was diesen Entwicklungsschritt von einem früheren unterscheidet.
 * Training, Wettkampf und Ruhetag teilen dieselbe Bedeutung; nur die konkrete
 * Ausführung wird vom bestehenden Kontext-Adapter verändert.
 */
export const PROGRAM_DAY_EXPLANATIONS: Record<number, string> = {
  1: "Stell dir vor, eine Aktion ist vorbei, aber dein Kopf hängt noch dort fest. Vielleicht denkst du an einen Fehler, den Spielstand oder die Reaktion anderer. Abschweifen bedeutet nicht, dass dein Fokus schlecht ist. Aufmerksamkeit bewegt sich ständig. Entscheidend ist, ob du bemerkst, dass du nicht mehr bei der aktuellen Situation bist. Zurückkommen heißt auch nicht, dass alle Gedanken verschwinden. Es heißt nur, dass die nächste Aktion wieder Vorrang bekommt.",
  2: "Du kannst dieselbe Handlung aus zwei verschiedenen Gründen wählen: weil sie der Aufgabe hilft oder weil du damit stark und sicher wirken möchtest. Von außen sieht das oft gleich aus. Der Unterschied liegt darin, worauf du währenddessen achtest. Bei der Aufgabe achtest du auf das, was die Situation braucht. Beim Eindruck beobachtest du zusätzlich dich selbst. Dadurch kann eine eigentlich einfache Entscheidung unnötig schwer werden.",
  3: "Etwas wiederzuerkennen fühlt sich schnell wie echtes Können an. Du liest einen bekannten Satz und denkst: Klar, den kenne ich. Unter Druck muss er dir aber ohne diese Hilfe einfallen. Genau darin unterscheidet sich Erinnern vom bloßen Wiedererkennen. Wenn der Satz noch nicht sofort auftaucht, ist das kein Scheitern. Es zeigt dir nur ehrlich, wie verfügbar das Gelernte gerade schon ist.",
  4: "Stell dir vor, ein Pass kommt nicht an, ein Schlag geht daneben oder du entscheidest dich zu spät. Dass du kurz enttäuscht oder sauer bist, ist normal. Entscheidend ist, was danach passiert. Aus einem Fehler zu lernen bedeutet nicht, ihn schönzureden oder sofort alles zu analysieren. Du trennst die hilfreiche Information von Gedanken wie „Ich bin schlecht“. Die Information hilft deinem nächsten Versuch. Das Urteil über dich nicht.",
  5: "Eine Qualität beschreibt nicht, wie du dich fühlen möchtest, sondern wie deine Handlung aussehen soll. Ruhe kann bedeuten, nicht zu überhasten. Klarheit kann bedeuten, deutlich zu kommunizieren. Mut kann bedeuten, eine passende Aktion wirklich auszuführen. Du musst nicht mehrere Qualitäten gleichzeitig zeigen. Eine klare Richtung ist hilfreicher als eine lange Liste, die dich während der Situation zusätzlich beschäftigt.",
  6: "Akzeptieren bedeutet nicht, dass du eine Entscheidung, einen Fehler oder eine unfaire Situation gut findest. Es bedeutet auch nicht, passiv zu werden. Du erkennst lediglich, welcher Teil bereits feststeht. Dadurch musst du keine Kraft mehr dafür verwenden, diesen vergangenen Teil innerlich rückgängig zu machen. Dein Handeln beginnt dort, wo du noch Einfluss hast.",
  7: "Zurückkommen und eine Handlung gut ausführen sind nicht dasselbe. Zuerst braucht deine Aufmerksamkeit wieder einen Ort. Erst wenn du bei der aktuellen Situation bist, kann eine Frage nach Ruhe, Mut oder Klarheit wirklich helfen. Versuchst du beides gleichzeitig zu lösen, entstehen schnell zwei Aufgaben im Kopf. Die Reihenfolge hält den Ablauf einfach: erst wieder da sein, dann die Ausführung klären.",
  8: "Du stehst vor einer schwierigen Aktion und dein Kopf sagt sofort: „Mach das lieber nicht.“ Dieser Gedanke kann richtig oder falsch sein. Du musst ihn weder glauben noch bekämpfen. „Gedanken sind keine Befehle“ bedeutet nicht, dass du Warnsignale ignorierst oder immer das Gegenteil machst. Es bedeutet: Der erste Gedanke entscheidet nicht automatisch. Du prüfst die Situation und wählst danach bewusst deine Handlung.",
  9: "Mitten in einer schnellen Situation ist eine vollständige Fehleranalyse oft zu groß. Vielleicht waren Technik, Timing und Entscheidung gleichzeitig nicht ideal. Das alles kann später wichtig sein. Für den nächsten Versuch brauchst du aber nur die Information, die du sofort umsetzen kannst. Eine kleine Korrektur ist deshalb nicht oberflächlich. Sie schützt deine Aufmerksamkeit, bis genug Ruhe für die gründliche Analyse da ist.",
  10: "Unsicherheit ist ein Gefühl und noch keine fertige Bewertung der Situation. Eine neue Aktion kann sich unsicher anfühlen, obwohl sie vorbereitet und sinnvoll ist. Eine andere kann sich mutig anfühlen, obwohl sie unnötig riskant ist. Deshalb geht es weder darum, Angst immer zu überwinden, noch darum, ihr immer zu folgen. Sicherheit, Regeln und Nutzen für die Aufgabe bleiben die Grenze.",
  11: "Ein unangenehmes Ereignis verursacht bereits Ärger oder Enttäuschung. Danach kann ein zweiter Kampf beginnen: Dein Kopf fordert immer wieder, dass es nicht hätte passieren dürfen. Dieser Kampf ist nicht dasselbe wie das eigentliche Problem. Du sollst das erste Gefühl nicht wegdrücken. Du erkennst nur, wenn dein Kopf dieselbe unveränderbare Realität immer wieder neu bekämpft.",
  12: "Hoher Anspruch ist nicht das Problem. Schwierig wird es, wenn jede sichtbare Handlung gleichzeitig beweisen soll, wie gut oder stark du bist. Dann trägt die Aktion plötzlich zwei Aufgaben: sportlich funktionieren und dein Bild schützen. Du darfst weiterhin mutig, präzise und intensiv handeln. Die Qualität gehört aber zur Aufgabe und ist kein Urteil darüber, wie wertvoll du bist.",
  13: "Zwischen einem Gedanken und einer Handlung liegt oft ein schneller Zug. Nach „Das wird peinlich“ willst du vielleicht vermeiden. Nach „Zeig es allen“ willst du vielleicht übertreiben. Dieser Zug ist der Impuls. Heute geht es nicht nur darum, den Gedanken zu bemerken, sondern zu erkennen, wohin er dein Verhalten schiebt. Genau dort wird eine bewusste Entscheidung möglich.",
  14: "Ein Ziel und dein aktueller Fokus erfüllen verschiedene Aufgaben. Das Ziel gibt die Richtung vor: gewinnen, eine Zeit erreichen oder eine Leistung zeigen. Während der Ausführung hilft dir das Ergebnis aber nicht bei jedem einzelnen Schritt. Du gibst dein Ziel nicht auf, wenn du es kurz aus dem Mittelpunkt nimmst. Du arbeitest nur an der Stelle, an der das Ergebnis gerade tatsächlich entstehen kann.",
  15: "Nach einem Gegentreffer, Rückstand oder schlechten Versuch wirkt dieser eine Punkt schnell riesig. Dabei können gleichzeitig Mitspieler frei sein, Teile deiner Leistung funktionieren oder mehrere Lösungen offenstehen. Du sollst den negativen Teil weder leugnen noch schönreden. Du verhinderst lediglich, dass eine auffällige Information alle anderen verdrängt und dadurch deine Auswahl unnötig kleiner wird.",
  16: "Du kannst eine Situation sorgfältig prüfen und dich trotzdem nicht vollkommen sicher fühlen. Dieses fehlende Sicherheitsgefühl bedeutet nicht automatisch, dass noch mehr Warten nötig ist. Vollständige Gewissheit gibt es bei vielen sportlichen Entscheidungen nicht. Die wichtige Grenze bleibt real: Ist die Handlung sicher, erlaubt und passend vorbereitet? Danach darf eine Entscheidung fallen, obwohl ein Rest Unsicherheit bleibt.",
  17: "Eine kleine Korrektur ist nicht dasselbe wie eine kleine Lernbereitschaft. Unter Zeitdruck schützt sie dich davor, fünf Veränderungen gleichzeitig in die nächste Aktion mitzunehmen. Später kannst du Technik, Entscheidung und Ablauf ausführlich durchgehen. Im Moment wählst du nur den Teil, der sofort nutzbar ist. So bleiben Lernen und Handeln miteinander verbunden, ohne miteinander zu konkurrieren.",
  18: "Müdigkeit, Frust oder wenig Motivation verändern, was heute möglich ist. Sie entscheiden aber nicht automatisch, dass gar nichts mehr möglich ist. Handlungsfähig zu bleiben heißt nicht, Erholung, Schmerzen oder echte Grenzen zu ignorieren. Ein sinnvoller Schritt darf kleiner oder ruhiger sein als sonst. Du passt die Handlung an deinen Zustand an, statt sie vollständig von ihm bestimmen zu lassen.",
  19: "Nach einer strittigen Entscheidung reagiert dein Körper vielleicht sofort mit Spannung. Das geschieht zunächst von allein. Minuten später kann die Belastung jedoch weiterlaufen, weil du den Ablauf erneut durchgehst und zusätzliche Bewertungen hinzufügst. Der Unterschied ist wichtig: Das erste Gefühl musst du nicht verhindern. Du willst nur nicht jede weitere Runde selbst antreiben und dadurch länger an der Vergangenheit festhängen.",
  20: "Eine schnelle Reaktion fühlt sich oft wie ein einziger Vorgang an. Tatsächlich gibt es mehrere Teile: Etwas passiert, in dir taucht etwas auf, daraus entsteht ein Impuls und anschließend folgt Verhalten. Diese Teile zu erkennen bedeutet nicht, im Sport alles langsam zu zerdenken. Du lernst lediglich, an welcher Stelle dein Verhalten noch nicht festgelegt ist.",
  21: "Ein Beitrag muss nichts Großes oder Spektakuläres sein. In einem Team kann es klare Kommunikation, Unterstützung oder das zuverlässige Erfüllen deiner Rolle sein. Im Einzelsport kann es eine saubere Vorbereitung, Geduld oder konzentrierte Ausführung sein. Es geht nicht darum, dich für andere aufzuopfern oder besonders wichtig zu wirken. Dein Beitrag ist einfach das, was du in diesem Moment sinnvoll zur Aufgabe beitragen kannst.",
  22: "Unter Belastung verschwinden hilfreiche Informationen nicht wirklich. Sie bekommen nur weniger Aufmerksamkeit. Du siehst dann vielleicht fast ausschließlich den Rückstand oder den Fehler und übersiehst freie Räume, Unterstützung oder funktionierende Teile deiner Leistung. Ein breiterer Blick ist deshalb keine Liste positiver Gedanken. Er liefert deiner nächsten Entscheidung wieder mehr echte Informationen.",
  23: "Eine sichtbare, unsichere Handlung kann sich wie eine Prüfung deiner ganzen Person anfühlen. Dann scheint ein möglicher Fehler zu zeigen, ob du mutig, talentiert oder gut genug bist. Tatsächlich zeigt der Versuch zunächst nur, wie diese eine Handlung gelaufen ist. Das soziale Risiko darf sich unangenehm anfühlen, ohne dass daraus ein Urteil über deinen Wert entsteht.",
  24: "Eine gute Handlung ist ein konkreter Beweis dafür, was du bereits tun kannst. Sie ist aber kein Beweis, dass du ab jetzt immer so handeln wirst. Genau deshalb sind reale Szenen hilfreicher als große Sätze wie „Ich bin selbstbewusst“. Du erinnerst dich nicht nur an ein gutes Gefühl, sondern an ein Verhalten, das du unter ähnlichen Bedingungen erneut zeigen kannst.",
  25: "Bereitschaft ist nicht dasselbe wie Fähigkeit. Du kannst zweifeln, keine Lust haben oder dich noch nicht bereit fühlen und trotzdem zu einer sicheren, sinnvollen Handlung fähig sein. Das bedeutet nicht, deinen Körper oder echte Grenzen zu ignorieren. Du trennst lediglich die sachliche Möglichkeit von dem Wunsch, dich vorher vollkommen bereit zu fühlen.",
  26: "Peinlichkeit und Gefahr können sich im ersten Moment ähnlich stark anfühlen, sind aber nicht dasselbe. Wenn andere deinen Versuch sehen, kann dein Körper Alarm geben, obwohl keine reale Gefahr besteht. Reale Risiken werden weiterhin ernst genommen. Bei sozialer Unsicherheit prüfst du zusätzlich, ob dein erstes Gefühl gerade die tatsächliche Gefahr beschreibt oder vor allem mögliche Bewertung.",
  27: "Vor einer wichtigen Aktion willst du vielleicht vor allem sicherstellen, dass sie gelingt. Das kannst du nie vollständig kontrollieren. Du kannst aber beeinflussen, ob du klar, geduldig oder mutig ausführst. Qualität ist deshalb kein Ersatz für das Ergebnis. Sie ist der Teil der Leistung, den du während eines offenen Ausgangs tatsächlich steuern kannst.",
  28: "Die verschiedenen Sätze im Programm sind nicht sieben Antworten auf jedes Problem. Ein Fehler braucht etwas anderes als ein enger Blick oder ein Gedanke, der dich zum Rückzug drängt. Mehr Auswahl hilft nur, wenn du zuerst erkennst, was gerade passiert. Reife bedeutet hier nicht, alles gleichzeitig anzuwenden, sondern aus mehreren bekannten Möglichkeiten eine passende auszuwählen.",
  29: "Frühe Zeichen von Wegdriften sehen bei jedem etwas anders aus. Vielleicht bleibt dein Blick hängen, du hörst Anweisungen nur noch halb oder derselbe Gedanke läuft mehrfach durch. Das Zeichen ist kein neuer Fehler, über den du dich ärgern musst. Es ist ein Hinweis, dass deine Aufmerksamkeit gerade beginnt, die Aufgabe zu verlassen. Je früher du ihn kennst, desto weniger weit musst du zurück.",
  30: "Zwei gleich aussehende Handlungen können innerlich verschieden organisiert sein. Du kannst laut kommunizieren, weil die Situation Klarheit braucht, oder weil du unbedingt stark wirken möchtest. Die zweite Motivation macht die Handlung nicht automatisch falsch. Sie kann aber zusätzliche Aufmerksamkeit an dein Bild binden. Du prüfst deshalb nicht, ob du gut wirkst, sondern welchen echten Nutzen deine Handlung hat.",
  31: "Ein Fehler endet nicht immer mit der misslungenen Aktion. Danach kann ein Urteil über dich entstehen, dein Blick enger werden und dein nächster Versuch sich verändern. Dieser Ablauf erklärt, warum ein einzelner Fehler mehrere weitere Situationen beeinflussen kann. Heute steht deshalb nicht nur die erste Korrektur im Mittelpunkt, sondern die Kette, die der Fehler danach in dir auslösen kann.",
  32: "Nach einer unfairen oder frustrierenden Szene vermischt dein Kopf leicht den Fakt mit allem, was er darüber denkt. Der Fakt ist das, was wirklich passiert ist. Gedanken wie „Das darf nicht sein“ oder „Jetzt ist alles kaputt“ sind zusätzliche Reaktionen. Diese Trennung löscht den Frust nicht. Sie macht sichtbar, welcher Teil Vergangenheit ist und welcher Teil noch von dir gestaltet werden kann.",
  33: "Du kennst die automatische Kette bereits. Heute suchst du sie nicht erst lange im Rückblick, sondern erkennst sie möglichst nah am echten Moment. Der entscheidende Punkt liegt dort, wo ein Gedanke oder Gefühl bereits Druck macht, die Handlung aber noch nicht ausgeführt ist. Dieser kurze Zwischenraum reicht. Du brauchst keine vollständige Ruhe, um anders zu entscheiden.",
  34: "Eine passende Herausforderung liegt zwischen Unterforderung und Überforderung. Wenn du einen Versuch kleiner, langsamer oder besser vorbereitet machst, weichst du nicht automatisch aus. Du gestaltest eine Größe, in der Lernen möglich bleibt. Umgekehrt ist die schwierigste Variante nicht automatisch die mutigste oder beste. Entscheidend sind Sicherheit, Vorbereitung und ein sinnvoller Lernreiz.",
  35: "Eine Szene im Rückblick noch einmal anzusehen bedeutet nicht, die Vergangenheit umzuschreiben. Du prüfst, welche Informationen damals außerhalb deines engen Blicks lagen. Vielleicht war Hilfe verfügbar, ein Teil funktionierte oder es gab eine weitere Möglichkeit. Dadurch erkennst du nicht, was garantiert passiert wäre. Du lernst, welches größere Bild du in einer ähnlichen zukünftigen Situation früher brauchst.",
  36: "In einer hektischen Phase reden mehrere Menschen, Bewegungen ändern sich schnell und vielleicht ist gerade zusätzlich etwas misslungen. Du musst diese Umgebung weder beruhigen noch vollständig überblicken. Entscheidend ist, dass nicht jeder Reiz denselben Stellenwert bekommt. Ein klarer Arbeitsort im Moment reicht, damit du trotz der Unruhe wieder sinnvoll am Geschehen teilnehmen kannst.",
  37: "Stell dir vor, eine mutige Lösung wäre sportlich richtig, die volle Variante ist aber gerade schlecht vorbereitet. Dann musst du weder auf Mut verzichten noch blind handeln. Du kannst denselben Anspruch in einer kontrollierteren Form zeigen. Die gewünschte Art deiner Ausführung bleibt erhalten; nur Größe, Tempo oder Vorbereitung werden an die reale Lage angepasst.",
  38: "Nach einem Fehler kannst du gleichzeitig etwas lernen und über äußere Bedingungen verärgert sein. Wenn beides zusammenbleibt, trägt deine nächste Aktion leicht auch den Protest über den vergangenen Moment. Trennen bedeutet nicht, die Bedingungen zu entschuldigen. Du behältst die Information aus deinem eigenen Anteil, ohne die unveränderbare Szene weiter in deiner Ausführung mitzunehmen.",
  39: "Nach einem Fehler klingt ein innerer Satz oft wie eine fertige Auswertung: „Ich kann das nicht“ oder „Jetzt ist alles weg“. Er enthält aber nicht automatisch die brauchbare sportliche Information. Du musst diesen Satz weder widerlegen noch durch etwas Positives ersetzen. Die wichtige Trennung lautet: Der Gedanke bewertet die Lage, die Fehleranalyse beschreibt, was tatsächlich verändert werden kann.",
  40: "Schwierigkeit kann drei verschiedene Dinge bedeuten: Die Aufgabe braucht diese anspruchsvolle Handlung, sie bietet dir eine sinnvolle Lernchance oder sie sieht lediglich beeindruckend aus. Mehr Schwierigkeit ist deshalb nicht automatisch mehr Entwicklung. Auch eine einfache Aktion kann die höchste Qualität besitzen. Der Nutzen entscheidet, nicht die Wirkung nach außen.",
  41: "Stell dir vor, du bist müde, hast gerade einen Fehler gemacht und ärgerst dich zusätzlich über eine Entscheidung. Schnell fühlt es sich an, als würde jetzt alles gegen dich laufen. Den Blick zu öffnen bedeutet nicht, positiv zu denken oder Probleme kleinzureden. Die Belastung bleibt real. Du nimmst nur wieder die Informationen hinzu, die dein enger Blick gerade ausblendet: Was funktioniert trotzdem? Welche Hilfe ist da? Welche Möglichkeit bleibt?",
  42: "Nach einer schwierigen Situation kann alles gleichzeitig falsch wirken. Vielleicht bist du noch bei der Vergangenheit, bewertest dich zusätzlich und weißt dadurch nicht, wie es weitergeht. Das heißt nicht, dass du mehrere mentale Probleme auf einmal lösen musst. Suche den ersten Punkt, der dich aktuell vom Handeln abhält. Oft reicht dort eine passende bekannte Reaktion, damit der übrige Ablauf wieder einfacher wird.",
  43: "Weniger Erklärung bedeutet an diesem Tag nicht weniger Lernen. Im Gegenteil: Du prüfst, ob dir der bekannte Rückweg ohne Hilfe zur Verfügung steht. Wenn du noch nachlesen musst, ist das eine ehrliche Information und kein Problem. Wiederholtes eigenes Abrufen macht den Weg mit der Zeit kürzer. Das Ziel ist nicht ein neuer Satz, sondern schnellerer Zugriff auf den bekannten.",
  44: "Ruhige Qualität kann genauso sichtbar und stark sein wie eine spektakuläre Leistung. Der Unterschied ist, dass sie nicht ständig zeigen muss, was sie über dich bedeutet. Du darfst führen, Verantwortung übernehmen und einen hohen Anspruch haben. Reife Stärke wird nicht kleiner. Sie braucht nur nicht nach jeder Handlung neue Bestätigung für dein Selbstbild.",
  45: "Eine sachliche Beschreibung schützt dich nicht vor Verantwortung. Sie macht den Fehler sogar genauer: zu spät entschieden, Abstand falsch gewählt oder nicht klar kommuniziert. „Ich bin schlecht“ klingt hart, enthält aber keine brauchbare Korrektur. Wenn du Handlung und Person trennst, kannst du den Fehler vollständig ernst nehmen, ohne aus einer einzelnen Szene ein Gesamturteil über dich zu machen.",
  46: "Akzeptanz erkennst du nicht daran, dass der Ärger sofort verschwindet. Du kannst weiterhin enttäuscht sein und trotzdem wieder handeln. Genau das unterscheidet Akzeptanz von einem guten Gefühl. Der Fortschritt liegt darin, dass eine unveränderbare Situation nicht mehr deine gesamte Aufmerksamkeit bindet. Handlung wird wieder möglich, obwohl die Reaktion noch da sein darf.",
  47: "Ein schwieriger Gedanke kann bleiben, nachdem du ihn bemerkt hast. Das bedeutet nicht, dass die Übung nicht funktioniert. Erfolg heißt hier nicht mentale Stille. Erfolg heißt, dass der Gedanke weniger Macht über dein Verhalten bekommt. Du musst ihn weder bekämpfen noch freundlich finden. Er darf vorhanden sein, während deine Handlung weiterhin von der Aufgabe geführt wird.",
  48: "Ein Versuch läuft deutlich schlechter als erwartet. Das kann bedeuten, dass dir eine Grundlage fehlt, dass du zu viel auf einmal willst oder dass du gerade an einer sinnvollen Grenze übst. Von außen fühlt sich alles einfach nur schwer an. Darum wäre sowohl sofortiges Aufgeben als auch blindes Durchziehen zu schnell. Zuerst brauchst du eine ehrliche Einschätzung dessen, was die Reibung tatsächlich verursacht.",
  49: "Einen breiteren Blick kannst du auch trainieren, wenn gerade nichts Dramatisches passiert. Das ist keine erzwungene Dankbarkeit und keine Suche nach etwas Besonderem. In einem normalen Moment bemerkst du lediglich, welche Informationen sonst leicht im Hintergrund bleiben. Dadurch wird diese Art zu sehen vertrauter, bevor du sie unter Druck wirklich brauchst.",
  50: "Eine Serie guter oder schlechter Aktionen erzeugt schnell eine Geschichte: „Heute läuft alles“ oder „Jetzt kippt es“. Diese Geschichte kann deine nächste Entscheidung stärker beeinflussen als die aktuelle Situation. Den Verlauf wahrzunehmen ist weiterhin wichtig. Du behandelst ihn nur nicht als automatische Anweisung. Die nächste Aktion bekommt ihre Richtung aus dem, was jetzt gebraucht wird.",
  51: "Eine Aktion misslingt und fast gleichzeitig erscheint der Satz: „Jetzt geht es wieder los.“ Beides fühlt sich wie eine einzige Botschaft an, sind aber zwei verschiedene Dinge. Die Ausführung zeigt etwas über Timing oder Entscheidung. Der innere Kommentar erzählt bereits eine größere Geschichte. In diesem Entwicklungsschritt trennst du beides innerhalb derselben Situation, damit die Geschichte die sportliche Korrektur nicht überdeckt.",
  52: "Einen unveränderbaren Fakt anzuerkennen reicht manchmal noch nicht. Dein Blick kann trotzdem so eng bleiben, dass du weitere Möglichkeiten übersiehst. Deshalb kommen hier zwei bekannte Bewegungen zusammen: Die Realität wird nicht bekämpft und gleichzeitig wieder vollständiger wahrgenommen. Das ist kein positives Umdeuten. Du siehst schlicht mehr von dem, was wahr und noch nutzbar ist.",
  53: "Eine passende Herausforderung braucht keinen großen Lebenssinn. Ein persönlicher Grund kann helfen, etwa Verantwortung für dein Team oder deine eigene Entwicklung. Er darf aber nicht dazu dienen, eine schlechte oder gefährliche Entscheidung bedeutungsvoll aussehen zu lassen. Zuerst zählen Sicherheit, Nutzen für die Aufgabe und Lernchance. Bedeutung kann diese Entscheidung stärken, aber nicht ersetzen.",
  54: "Nach einem Erfolg oder Lob fühlt sich Sicherheit oft leichter an. Reifere Sicherheit zeigt sich, wenn gerade kein neues Signal dazukommt. Das ist nicht dasselbe wie blindes Selbstvertrauen. Du handelst weiterhin nach Vorbereitung und Aufgabe. Du verlangst nur nicht vor jeder neuen Aktion erneut einen Beweis, dass du gut genug oder bereit bist.",
  55: "„Ich bin immer mutig“ klingt stark, lässt sich aber kaum ehrlich prüfen. Ein Satz wie „Nach Fehlern arbeite ich weiter“ beschreibt dagegen sichtbares Verhalten. Ein einzelner guter Moment legt deine Identität nicht endgültig fest. Viele ähnliche Entscheidungen zeigen dir mit der Zeit jedoch, wie du verlässlich auftreten möchtest. Darum besteht ein tragfähiger persönlicher Maßstab aus Handlungen und nicht aus großen Etiketten.",
  56: "Am Ende brauchst du nicht für jede Situation alle bekannten Sätze. Das System funktioniert, wenn du zuerst die Art des Problems erkennst und danach eine passende Reaktion findest. Ein enger Blick braucht etwas anderes als ein Fehler oder ein lauter Gedanke. Zusammenhalt bedeutet deshalb nicht, immer gleich zu reagieren. Er bedeutet, aus demselben klaren Grundprinzip passend handeln zu können.",
};

export const getProgramDayExplanation = (day: number): string | null =>
  PROGRAM_DAY_EXPLANATIONS[day] ?? null;
