export type QuestionPrivacy =
  | "profile_only"
  | "private_only"
  | "aggregate_allowed"
  | "private_and_aggregate"
  | "validated_assessment"
  | "daily_pulse";

export type ScoringDirection =
  | "higher_is_better"
  | "lower_is_better"
  | "categorical"
  | "not_scored";

export type QuestionType = "text" | "scale" | "choice" | "multi";

export type RewireQuestionOption = {
  id: string;
  text: string;
  score?: number;
};

export type RewireQuestion = {
  id: string;
  category: string;
  type: QuestionType;
  text: string;
  helper?: string;
  lowLabel?: string;
  highLabel?: string;
  options?: RewireQuestionOption[];
  dimension?: string;
  scoringDirection: ScoringDirection;
  privacy: QuestionPrivacy;
  retestEligible: boolean;
  coachAggregateDimension?: string | null;
  includeInScore?: boolean;
};

export type DevelopmentIndexTiming = "pre" | "mid" | "post";

export type DevelopmentIndexQuestion = RewireQuestion & {
  timing?: Array<Extract<DevelopmentIndexTiming, "mid" | "post">>;
};

export type RewireQuestionCategory = {
  id: string;
  title: string;
  description: string;
  icon: string;
  intro: string;
};

export const ONBOARDING_V2_VERSION = "v2";
export const ONBOARDING_V2_INSTRUMENT_ID = "onboarding_v2";

export const ONBOARDING_V2_CATEGORIES: RewireQuestionCategory[] = [
  { id: "sport_profile", title: "Sportprofil", description: "Sport, Rolle und Kontext.", icon: "⚙️", intro: "Wir starten mit deinem sportlichen Kontext. Diese Angaben helfen, dein Programm passend einzuordnen." },
  { id: "identity_selfworth", title: "Selbstwert & Identität", description: "Wie stark Leistung und Wert verbunden sind.", icon: "🪞", intro: "Diese Fragen helfen dir, Muster zwischen Leistung, Bewertung und Selbstbild zu erkennen." },
  { id: "mistakes_evaluation", title: "Fehler & Bewertung", description: "Was nach Fehlern passiert.", icon: "↩️", intro: "Fehler sind im Sport unvermeidbar. Entscheidend ist, wie schnell du zurückfindest." },
  { id: "pressure_emotions", title: "Druck & Emotionen", description: "Handlungsfähigkeit unter innerer Aktivierung.", icon: "🌊", intro: "Druck und Emotionen sind nicht das Problem. Entscheidend ist, ob du trotzdem handeln kannst." },
  { id: "focus_presence", title: "Fokus & Präsenz", description: "Aufmerksamkeit im aktuellen Moment.", icon: "🎯", intro: "Hier geht es darum, wie du Fokus verlierst, bemerkst und zurückholst." },
  { id: "motivation_purpose", title: "Motivation & Sinn", description: "Was dich wirklich antreibt.", icon: "⚡", intro: "Motivation ist nicht nur Energie. Sie entscheidet, ob du auch ohne Bühne weiterarbeitest." },
  { id: "recovery_load", title: "Erholung & Belastung", description: "Wie du Pause, Schlaf und Last wahrnimmst.", icon: "🌙", intro: "Entwicklung braucht Belastung und Erholung. Beides gehört zum System." },
  { id: "environment_team", title: "Umfeld & Team", description: "Sicherheit, Vertrauen und Erwartungen.", icon: "🤝", intro: "Dein Umfeld kann Druck verstärken oder Entwicklung ermöglichen." },
  { id: "growth_learning", title: "Lernen & Wachstum", description: "Wie du mit Unsicherheit und Rückschlägen arbeitest.", icon: "📈", intro: "Lernen zeigt sich besonders dort, wo es noch nicht leicht ist." },
  { id: "deep_sport_profile", title: "Druckprofil", description: "Konkrete Situationen aus deinem Sport.", icon: "🔬", intro: "Zum Abschluss schärfen wir dein persönliches Sportprofil für die tägliche Praxis." },
];

export const ONBOARDING_V2_QUESTIONS: RewireQuestion[] = [
  { id: "sport-01", category: "sport_profile", type: "choice", text: "Welchen Sport betreibst du?", options: [{ id: "football", text: "Fußball" }, { id: "basketball", text: "Basketball" }, { id: "handball", text: "Handball" }, { id: "tennis", text: "Tennis" }, { id: "athletics", text: "Leichtathletik" }, { id: "other", text: "Anderer Sport" }], scoringDirection: "not_scored", privacy: "profile_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "sport-02", category: "sport_profile", type: "text", text: "Welche Position oder Rolle spielst du meistens?", helper: "Sei so konkret wie möglich, z. B. in deiner Rolle (Innenverteidiger-Beispiel), Point Guard, Torwart oder Quarterback.", scoringDirection: "not_scored", privacy: "profile_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "sport-03", category: "sport_profile", type: "choice", text: "Auf welchem Leistungsniveau spielst du aktuell?", options: [{ id: "youth", text: "Nachwuchs / Jugend" }, { id: "amateur", text: "Amateur" }, { id: "competitive_amateur", text: "Leistungsorientierter Amateurbereich" }, { id: "semi_pro", text: "Semi-professionell" }, { id: "pro", text: "Professionell / Vollzeit" }, { id: "college", text: "College / University" }], scoringDirection: "not_scored", privacy: "profile_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "id-01", category: "identity_selfworth", type: "scale", text: "Wie stark hängt dein Selbstwert aktuell von deiner sportlichen Leistung ab?", lowLabel: "fast gar nicht", highLabel: "sehr stark", dimension: "selfworth_performance_link", scoringDirection: "lower_is_better", privacy: "private_only", retestEligible: true, coachAggregateDimension: null, includeInScore: true },
  { id: "id-02", category: "identity_selfworth", type: "choice", text: "Was passiert innerlich am ehesten, wenn du schlecht gespielt hast?", options: [{ id: "a", text: "Ich hinterfrage schnell meinen Wert als Athleten.", score: 1 }, { id: "b", text: "Ich ärgere mich, kann es aber relativ gut einordnen.", score: 5 }, { id: "c", text: "Ich suche direkt nach einer konkreten Korrektur.", score: 8 }, { id: "d", text: "Ich trenne die Leistung klar von meinem Wert.", score: 10 }], dimension: "selfworth_after_bad_performance", scoringDirection: "categorical", privacy: "private_only", retestEligible: true, coachAggregateDimension: null, includeInScore: true },
  { id: "id-03", category: "identity_selfworth", type: "text", text: "Wer bist du, wenn dein Sport für einen Moment keine Rolle spielt?", helper: "Antworte kurz und ehrlich. Es muss nicht perfekt klingen.", dimension: "identity_beyond_sport", scoringDirection: "not_scored", privacy: "private_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "id-04", category: "identity_selfworth", type: "scale", text: "Wie stark versuchst du im Sport, ein bestimmtes Bild von dir aufrechtzuerhalten?", lowLabel: "kaum", highLabel: "sehr stark", dimension: "image_protection", scoringDirection: "lower_is_better", privacy: "private_and_aggregate", retestEligible: true, coachAggregateDimension: "Bildschutz / Bewertungsdruck", includeInScore: true },
  { id: "id-05", category: "identity_selfworth", type: "choice", text: "Wenn jemand deine Fähigkeiten öffentlich infrage stellt, was passiert am ehesten?", options: [{ id: "a", text: "Es trifft mich stark und bleibt lange in meinem Kopf.", score: 1 }, { id: "b", text: "Ich will sofort beweisen, dass die Person falschliegt.", score: 3 }, { id: "c", text: "Ich prüfe kurz, ob etwas Wahres daran ist.", score: 7 }, { id: "d", text: "Ich bleibe bei meinem Standard und meiner nächsten Aufgabe.", score: 10 }], dimension: "criticism_response", scoringDirection: "categorical", privacy: "private_and_aggregate", retestEligible: true, coachAggregateDimension: "Kritik- und Bewertungsreaktion", includeInScore: true },
  { id: "err-01", category: "mistakes_evaluation", type: "scale", text: "Wie stark beeinflusst ein einzelner Fehler dein nächstes Verhalten?", lowLabel: "fast gar nicht", highLabel: "sehr stark", dimension: "mistake_impact", scoringDirection: "lower_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Fehlerreaktion", includeInScore: true },
  { id: "err-02", category: "mistakes_evaluation", type: "scale", text: "Wie schnell findest du nach einem Fehler zurück zur nächsten Aufgabe?", lowLabel: "sehr langsam", highLabel: "sehr schnell", dimension: "mistake_recovery", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Fehlererholung", includeInScore: true },
  { id: "err-03", category: "mistakes_evaluation", type: "choice", text: "Was ist nach einem Fehler meistens dein erster innerer Impuls?", options: [{ id: "a", text: "Ich will den Fehler sofort ungeschehen machen.", score: 2 }, { id: "b", text: "Ich ärgere mich und werde enger.", score: 3 }, { id: "c", text: "Ich suche nach der konkreten Information im Fehler.", score: 8 }, { id: "d", text: "Ich resette mich und gehe in die nächste Aktion.", score: 10 }], dimension: "first_impulse_after_mistake", scoringDirection: "categorical", privacy: "private_and_aggregate", retestEligible: true, coachAggregateDimension: "Fehlerdeutung", includeInScore: true },
  { id: "err-04", category: "mistakes_evaluation", type: "scale", text: "Wie sehr beschäftigt dich, was andere nach einem Fehler über dich denken könnten?", lowLabel: "kaum", highLabel: "sehr stark", dimension: "evaluation_after_mistake", scoringDirection: "lower_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Bewertungsdruck nach Fehlern", includeInScore: true },
  { id: "err-05", category: "mistakes_evaluation", type: "choice", text: "Wie siehst du Fehler meistens?", options: [{ id: "a", text: "Als Zeichen, dass ich nicht gut genug bin.", score: 1 }, { id: "b", text: "Als etwas, das ich vermeiden muss.", score: 3 }, { id: "c", text: "Als unangenehm, aber normal im Lernen.", score: 7 }, { id: "d", text: "Als konkrete Information für meine nächste Anpassung.", score: 10 }], dimension: "mistake_meaning", scoringDirection: "categorical", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Growth / Fehlerdeutung", includeInScore: true },
  { id: "err-06", category: "mistakes_evaluation", type: "text", text: "Welcher Satz taucht nach Fehlern bei dir am häufigsten im Kopf auf?", helper: "Schreib ihn möglichst wörtlich auf.", dimension: "inner_sentence_after_mistake", scoringDirection: "not_scored", privacy: "private_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "err-07", category: "mistakes_evaluation", type: "scale", text: "Wie oft spielst du nach einem Fehler vorsichtiger, um nicht noch einmal aufzufallen?", lowLabel: "fast nie", highLabel: "sehr oft", dimension: "protection_after_mistake", scoringDirection: "lower_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Schutzmodus nach Fehlern", includeInScore: true },
  { id: "press-01", category: "pressure_emotions", type: "choice", text: "Was spürst du vor wichtigen Wettkämpfen am häufigsten?", options: [{ id: "a", text: "Nervosität oder Angst" }, { id: "b", text: "Aufregung und Vorfreude" }, { id: "c", text: "Druck, funktionieren zu müssen" }, { id: "d", text: "Ruhe und Klarheit" }, { id: "e", text: "Eine Mischung, die schwer zu beschreiben ist" }], dimension: "pre_competition_state", scoringDirection: "not_scored", privacy: "aggregate_allowed", retestEligible: false, coachAggregateDimension: "Wettkampfzustand", includeInScore: false },
  { id: "press-02", category: "pressure_emotions", type: "scale", text: "Wie stark verändert Druck deine Entscheidungen im Wettkampf?", lowLabel: "kaum", highLabel: "sehr stark", dimension: "pressure_decision_change", scoringDirection: "lower_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Druckanfälligkeit", includeInScore: true },
  { id: "press-03", category: "pressure_emotions", type: "scale", text: "Wie gut kannst du starke Emotionen spüren, ohne sofort aus ihnen zu handeln?", lowLabel: "kaum", highLabel: "sehr gut", dimension: "emotion_action_space", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Emotionsregulation", includeInScore: true },
  { id: "press-04", category: "pressure_emotions", type: "choice", text: "Was machst du meistens, wenn Frust im Wettkampf hochkommt?", options: [{ id: "a", text: "Ich reagiere sichtbar und verliere kurz Kontrolle.", score: 1 }, { id: "b", text: "Ich schlucke es runter, aber innerlich bleibt es aktiv.", score: 3 }, { id: "c", text: "Ich bemerke es und brauche etwas Zeit zur Rückkehr.", score: 6 }, { id: "d", text: "Ich erkenne es und komme bewusst zurück zur Aufgabe.", score: 10 }], dimension: "frustration_response", scoringDirection: "categorical", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Frustregulation", includeInScore: true },
  { id: "press-05", category: "pressure_emotions", type: "scale", text: "Wie stabil bleibst du emotional, wenn ein Wettkampf gegen dich läuft?", lowLabel: "sehr instabil", highLabel: "sehr stabil", dimension: "negative_momentum_stability", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Stabilität bei negativem Momentum", includeInScore: true },
  { id: "press-06", category: "pressure_emotions", type: "text", text: "Welche Emotion zeigst du im Sport am wenigsten — und warum?", helper: "Optional: kurz und ehrlich.", dimension: "hidden_emotion", scoringDirection: "not_scored", privacy: "private_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "focus-01", category: "focus_presence", type: "scale", text: "Wie oft bist du im Training oder Wettkampf wirklich voll im Moment?", lowLabel: "fast nie", highLabel: "sehr oft", dimension: "presence_frequency", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Präsenz", includeInScore: true },
  { id: "focus-02", category: "focus_presence", type: "multi", text: "Was zieht dich am häufigsten aus dem Fokus?", options: [{ id: "mistake", text: "Fehler" }, { id: "score", text: "Ergebnis / Spielstand" }, { id: "evaluation", text: "Bewertung durch andere" }, { id: "opponent", text: "Gegner / Konkurrenz" }, { id: "fatigue", text: "Müdigkeit oder körperlicher Schmerz" }, { id: "self_doubt", text: "Selbstzweifel" }, { id: "frustration", text: "Frust" }, { id: "past_actions", text: "Gedanken an vergangene Aktionen" }, { id: "future_consequences", text: "Gedanken an zukünftige Konsequenzen" }], dimension: "focus_blockers", scoringDirection: "not_scored", privacy: "aggregate_allowed", retestEligible: false, coachAggregateDimension: "Fokusblocker", includeInScore: false },
  { id: "focus-03", category: "focus_presence", type: "scale", text: "Wie schnell merkst du, dass dein Kopf vom aktuellen Moment weggezogen wurde?", lowLabel: "sehr spät", highLabel: "sehr schnell", dimension: "metacognitive_awareness", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Metakognition", includeInScore: true },
  { id: "focus-04", category: "focus_presence", type: "scale", text: "Wie schnell kommst du nach Ablenkung wieder zur nächsten Aufgabe zurück?", lowLabel: "sehr langsam", highLabel: "sehr schnell", dimension: "attention_return", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Aufmerksamkeitsrückkehr", includeInScore: true },
  { id: "focus-05", category: "focus_presence", type: "text", text: "Beschreibe kurz einen Moment, in dem du dich im Sport komplett im Flow gefühlt hast.", dimension: "flow_memory", scoringDirection: "not_scored", privacy: "private_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "mot-01", category: "motivation_purpose", type: "choice", text: "Was treibt dich im Sport am stärksten an?", options: [{ id: "fear", text: "Angst, nicht gut genug zu sein", score: 2 }, { id: "comparison", text: "Der Wunsch, besser als andere zu sein", score: 4 }, { id: "process", text: "Freude am Prozess und an Entwicklung", score: 9 }, { id: "recognition", text: "Anerkennung von außen", score: 5 }, { id: "contribution", text: "Beitrag für Team, Aufgabe oder etwas Größeres", score: 10 }, { id: "unknown", text: "Ich weiß es noch nicht genau", score: 5 }], dimension: "motivation_source", scoringDirection: "categorical", privacy: "private_and_aggregate", retestEligible: true, coachAggregateDimension: "Motivationsquelle", includeInScore: true },
  { id: "mot-02", category: "motivation_purpose", type: "scale", text: "Wie motiviert bist du an Tagen, an denen niemand zuschaut?", lowLabel: "kaum", highLabel: "sehr stark", dimension: "intrinsic_motivation", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Intrinsische Motivation", includeInScore: true },
  { id: "mot-03", category: "motivation_purpose", type: "scale", text: "Wie oft handelst du im Sport eher aus Angst vor Fehlern als aus Freude an Entwicklung?", lowLabel: "fast nie", highLabel: "sehr oft", dimension: "fear_vs_growth", scoringDirection: "lower_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Fear vs Growth", includeInScore: true },
  { id: "mot-04", category: "motivation_purpose", type: "text", text: "Warum machst du deinen Sport wirklich?", helper: "Eine ehrliche kurze Antwort reicht.", dimension: "personal_why", scoringDirection: "not_scored", privacy: "private_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "mot-05", category: "motivation_purpose", type: "scale", text: "Wie stark fühlst du, dass dein Sport für mehr steht als nur Ergebnisse?", lowLabel: "gar nicht", highLabel: "sehr stark", dimension: "meaning_beyond_results", scoringDirection: "higher_is_better", privacy: "private_only", retestEligible: true, coachAggregateDimension: null, includeInScore: true },
  { id: "rec-01", category: "recovery_load", type: "choice", text: "Wie fühlst du dich meistens an Ruhetagen?", options: [{ id: "guilty", text: "Schuldig, weil ich trainieren sollte.", score: 2 }, { id: "restless", text: "Unruhig, weil ich schwer abschalten kann.", score: 3 }, { id: "relieved", text: "Erleichtert, weil ich Pause brauche.", score: 6 }, { id: "intentional", text: "Bewusst ruhig, weil ich Regeneration ernst nehme.", score: 10 }, { id: "mixed", text: "Unterschiedlich, je nach Belastung.", score: 6 }], dimension: "rest_day_response", scoringDirection: "categorical", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Recovery-Haltung", includeInScore: true },
  { id: "rec-02", category: "recovery_load", type: "scale", text: "Wie gut ist deine Schlafqualität in einer normalen Trainingswoche?", lowLabel: "sehr schlecht", highLabel: "sehr gut", dimension: "sleep_quality_baseline", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Schlafqualität", includeInScore: true },
  { id: "rec-03", category: "recovery_load", type: "scale", text: "Wie gut merkst du, wann dein Körper oder Kopf echte Erholung braucht?", lowLabel: "kaum", highLabel: "sehr gut", dimension: "recovery_awareness", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Recovery Awareness", includeInScore: true },
  { id: "rec-04", category: "recovery_load", type: "scale", text: "Wie oft trainierst du weiter, obwohl dein Körper klar nach Pause verlangt?", lowLabel: "fast nie", highLabel: "sehr oft", dimension: "overtraining_risk_behavior", scoringDirection: "lower_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Überlastungsrisiko", includeInScore: true },
  { id: "rec-05", category: "recovery_load", type: "scale", text: "Wie gut kannst du mental abschalten, wenn Training oder Wettkampf vorbei ist?", lowLabel: "kaum", highLabel: "sehr gut", dimension: "mental_recovery", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Mentale Erholung", includeInScore: true },
  { id: "env-01", category: "environment_team", type: "scale", text: "Wie offen kannst du mit deinem Coach über mentale Herausforderungen sprechen?", lowLabel: "gar nicht", highLabel: "sehr offen", dimension: "coach_trust", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Coach-Vertrauen", includeInScore: true },
  { id: "env-02", category: "environment_team", type: "scale", text: "Wie stark fühlst du dich in deinem Team sicher genug, Fehler zu machen und weiterzulernen?", lowLabel: "gar nicht", highLabel: "sehr stark", dimension: "psychological_safety_team", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Psychologische Sicherheit", includeInScore: true },
  { id: "env-03", category: "environment_team", type: "choice", text: "Wie gehst du meistens mit Erwartungen von Familie, Coach oder Umfeld um?", options: [{ id: "energizing", text: "Sie motivieren mich und geben mir Energie.", score: 8 }, { id: "pressure", text: "Sie belasten mich und erzeugen Druck.", score: 2 }, { id: "ignore", text: "Ich versuche sie auszublenden.", score: 4 }, { id: "talk", text: "Ich spreche offen darüber.", score: 9 }, { id: "neutral", text: "Sie spielen für mich kaum eine Rolle.", score: 7 }], dimension: "expectation_handling", scoringDirection: "categorical", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Erwartungsdruck", includeInScore: true },
  { id: "env-04", category: "environment_team", type: "text", text: "Welche Person in deinem Umfeld beeinflusst deinen mentalen Zustand am stärksten?", dimension: "key_environment_influence", scoringDirection: "not_scored", privacy: "private_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "grow-01", category: "growth_learning", type: "scale", text: "Wie stark glaubst du, dass du deine mentale Leistung systematisch trainieren kannst?", lowLabel: "kaum", highLabel: "sehr stark", dimension: "mental_trainability_belief", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Growth Mindset", includeInScore: true },
  { id: "grow-02", category: "growth_learning", type: "choice", text: "Was bedeutet ein Rückschlag für dich meistens?", options: [{ id: "not_good_enough", text: "Ein Zeichen, dass ich nicht gut genug bin.", score: 1 }, { id: "forget", text: "Etwas, das ich schnell vergessen will.", score: 3 }, { id: "normal", text: "Eine unangenehme, aber normale Erfahrung.", score: 6 }, { id: "information", text: "Eine Information, mit der ich besser werden kann.", score: 9 }, { id: "next_level", text: "Eine Chance, mein nächstes Level zu finden.", score: 10 }], dimension: "setback_meaning", scoringDirection: "categorical", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Rückschlagdeutung", includeInScore: true },
  { id: "grow-03", category: "growth_learning", type: "scale", text: "Wie bereit bist du, Dinge zu üben, in denen du dich noch unsicher fühlst?", lowLabel: "kaum bereit", highLabel: "sehr bereit", dimension: "uncertainty_practice_willingness", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Unsicherheitsfähigkeit", includeInScore: true },
  { id: "grow-04", category: "growth_learning", type: "scale", text: "Wie oft suchst du im Training bewusst Situationen, die dich fordern?", lowLabel: "fast nie", highLabel: "sehr oft", dimension: "challenge_seeking", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Challenge Orientation", includeInScore: true },
  { id: "grow-05", category: "growth_learning", type: "scale", text: "Wie schnell wechselst du nach Kritik von Verteidigung zu Lernen?", lowLabel: "sehr langsam", highLabel: "sehr schnell", dimension: "feedback_learning_shift", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Feedbackfähigkeit", includeInScore: true },
  { id: "dp-01", category: "deep_sport_profile", type: "multi", text: "Was sind deine stärksten Druckquellen?", options: [{ id: "own_pressure", text: "eigener Leistungsdruck" }, { id: "coach", text: "Coach / Trainerteam" }, { id: "family", text: "Eltern / Familie" }, { id: "teammates", text: "Trainingspartner / Konkurrenz" }, { id: "role", text: "Spielzeit / Rolle im Team" }, { id: "result", text: "Ergebnis / Tabelle" }, { id: "scouts", text: "Scouts / Sichtbarkeit" }, { id: "social_media", text: "soziale Medien / Öffentlichkeit" }], dimension: "pressure_sources", scoringDirection: "not_scored", privacy: "private_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "dp-02", category: "deep_sport_profile", type: "text", text: "Welche konkrete Aktion klappt im Training gut, aber unter Druck im Wettkampf deutlich schlechter?", dimension: "training_game_pressure_gap", scoringDirection: "not_scored", privacy: "private_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "dp-03", category: "deep_sport_profile", type: "scale", text: "Wie lange grübelst du nach einer Niederlage oder einem schlechten Wettkampf?", lowLabel: "kaum", highLabel: "sehr lange", dimension: "rumination_after_loss", scoringDirection: "lower_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Grübelneigung", includeInScore: true },
  { id: "dp-04", category: "deep_sport_profile", type: "text", text: "Beschreibe deine häufigste Drucksituation im Sport. Was passiert in diesem Moment in dir?", dimension: "common_pressure_situation", scoringDirection: "not_scored", privacy: "private_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "dp-05", category: "deep_sport_profile", type: "choice", text: "Was brauchst du am meisten, wenn du unter Druck stehst?", options: [{ id: "structure", text: "klare Struktur" }, { id: "less_input", text: "Ruhe und weniger Input" }, { id: "encouragement", text: "Ermutigung" }, { id: "hard_talk", text: "harte Ansprache" }, { id: "time", text: "eigene Zeit zum Sortieren" }, { id: "next_task", text: "konkrete nächste Aufgabe" }], dimension: "pressure_support_need", scoringDirection: "not_scored", privacy: "private_only", retestEligible: false, coachAggregateDimension: null, includeInScore: false },
  { id: "dp-06", category: "deep_sport_profile", type: "scale", text: "Wie gut kennst du deine eigenen mentalen Muster im Wettkampf?", lowLabel: "kaum", highLabel: "sehr gut", dimension: "self_pattern_awareness", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Selbstkenntnis", includeInScore: true },
];

export const DEVELOPMENT_INDEX_VERSION = "v1";
export const DEVELOPMENT_INDEX_INSTRUMENT_ID = "rewire_development_index";

export const REWIRE_DEVELOPMENT_INDEX = {
  id: DEVELOPMENT_INDEX_INSTRUMENT_ID,
  title: "RewirePerform Development Index",
  description: "Interner Entwicklungsindex für Selbstregulation, Prozessfokus und Druckkompetenz.",
  timing: ["pre", "mid", "post"] as const,
  scale: { min: 1, max: 10 },
  disclaimer:
    "Dieser Wert ist ein interner Entwicklungsindex. Er beschreibt beobachtete Veränderungen in deinen Antworten zu Selbstregulation, Prozessfokus und Druckkompetenz. Er ist keine Diagnose und kein medizinischer Messwert.",
  items: [
    { id: "rd-01", category: "rewire_development_index", type: "scale", text: "Wenn mir im Wettkampf ein Fehler passiert, finde ich innerhalb der nächsten Aktion wieder zurück zu meiner Aufgabe.", dimension: "fehlererholung", lowLabel: "fast nie", highLabel: "fast immer", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Fehlererholung", includeInScore: true },
    { id: "rd-02", category: "rewire_development_index", type: "scale", text: "Wenn andere mich bewerten könnten, verändert sich mein Wettkampf deutlich.", dimension: "bewertungsdruck", lowLabel: "kaum", highLabel: "sehr stark", scoringDirection: "lower_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Bewertungsdruck", includeInScore: true },
    { id: "rd-03", category: "rewire_development_index", type: "scale", text: "In wichtigen Momenten kann ich bei meiner nächsten Aufgabe bleiben, statt gedanklich beim Ergebnis zu sein.", dimension: "prozessfokus", lowLabel: "kaum", highLabel: "sehr gut", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Prozessfokus", includeInScore: true },
    { id: "rd-04", category: "rewire_development_index", type: "scale", text: "Nach einer schlechten Leistung fühlt es sich schnell so an, als wäre ich als Athleten weniger wert.", dimension: "selbstwertkopplung", lowLabel: "fast nie", highLabel: "sehr oft", scoringDirection: "lower_is_better", privacy: "private_and_aggregate", retestEligible: true, coachAggregateDimension: "Selbstwertkopplung", includeInScore: true },
    { id: "rd-05", category: "rewire_development_index", type: "scale", text: "Wenn Frust, Wut oder Nervosität hochkommt, kann ich sie wahrnehmen und trotzdem handlungsfähig bleiben.", dimension: "emotionsregulation", lowLabel: "kaum", highLabel: "sehr gut", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Emotionsregulation", includeInScore: true },
    { id: "rd-06", category: "rewire_development_index", type: "scale", text: "Wenn etwas schwer ist oder nicht sofort klappt, sehe ich darin eher Training als ein Zeichen, dass ich nicht gut genug bin.", dimension: "growth_mindset", lowLabel: "kaum", highLabel: "sehr stark", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Growth Mindset", includeInScore: true },
    { id: "rd-07", category: "rewire_development_index", type: "scale", text: "Unter Druck merke ich schnell, wenn mein Kopf abschweift, und bringe mich zurück in den Moment.", dimension: "praesenz", lowLabel: "fast nie", highLabel: "fast immer", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Präsenz", includeInScore: true },
    { id: "rd-08", category: "rewire_development_index", type: "scale", text: "Wenn ich pausiere oder regeneriere, habe ich schnell das Gefühl, nicht genug zu tun.", dimension: "recovery_schuld", lowLabel: "kaum", highLabel: "sehr stark", scoringDirection: "lower_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Recovery-Haltung", includeInScore: true },
    { id: "rd-09", category: "rewire_development_index", type: "scale", text: "Ich fühle mich im Team sicher genug, ehrlich zu sein, Fehler zu machen und weiterzulernen.", dimension: "teamverbundenheit", lowLabel: "gar nicht", highLabel: "sehr stark", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Teamverbundenheit", includeInScore: true },
    { id: "rd-10", category: "rewire_development_index", type: "scale", text: "Ich bin bereit, auch dann eine gute Aktion zu machen, wenn ich nicht sicher bin, ob sie perfekt klappt.", dimension: "unsicherheitsfaehigkeit", lowLabel: "kaum bereit", highLabel: "sehr bereit", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Challenge Orientation", includeInScore: true },
    { id: "rd-11", category: "rewire_development_index", type: "scale", text: "Wenn etwas unfair gegen mich oder mein Team läuft, komme ich schnell zurück zu dem, was ich kontrollieren kann.", dimension: "unfairness_regulation", lowLabel: "fast nie", highLabel: "fast immer", scoringDirection: "higher_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Unfairness-Regulation", includeInScore: true },
    { id: "rd-12", category: "rewire_development_index", type: "scale", text: "Mein Vertrauen in mich schwankt stark mit meiner letzten Leistung oder dem letzten Feedback.", dimension: "confidence_abhaengigkeit", lowLabel: "kaum", highLabel: "sehr stark", scoringDirection: "lower_is_better", privacy: "aggregate_allowed", retestEligible: true, coachAggregateDimension: "Confidence-Stabilität", includeInScore: true },
    { id: "rd-13", category: "rewire_development_index", type: "scale", text: "In wichtigen Momenten kann ich mich auf Beitrag, Aufgabe und Team ausrichten statt nur auf mich selbst.", dimension: "purpose_beitrag", lowLabel: "kaum", highLabel: "sehr gut", scoringDirection: "higher_is_better", privacy: "private_and_aggregate", retestEligible: true, coachAggregateDimension: "Beitragsorientierung", includeInScore: true },
    { id: "rd-14", category: "rewire_development_index", type: "scale", text: "Ich spiele oft mit dem inneren Gefühl, etwas beweisen zu müssen.", dimension: "beweisdrang", lowLabel: "kaum", highLabel: "sehr stark", scoringDirection: "lower_is_better", privacy: "private_and_aggregate", retestEligible: true, coachAggregateDimension: "Beweisdrang", includeInScore: true },
    { id: "rd-15", category: "rewire_development_index", type: "text", text: "Was hat sich in deinem Umgang mit Druck, Fehlern oder Bewertung seit dem Start am stärksten verändert?", dimension: "wichtigste_veraenderung", scoringDirection: "not_scored", privacy: "private_only", retestEligible: true, coachAggregateDimension: null, includeInScore: false, timing: ["mid", "post"] },
    { id: "rd-16", category: "rewire_development_index", type: "text", text: "Welches Muster willst du als Nächstes weiter verändern oder stabilisieren?", dimension: "naechster_entwicklungshebel", scoringDirection: "not_scored", privacy: "private_only", retestEligible: true, coachAggregateDimension: null, includeInScore: false, timing: ["mid", "post"] },
  ] as DevelopmentIndexQuestion[],
  subscores: {
    fehler_und_rueckkehr: ["rd-01", "rd-05", "rd-11"],
    druck_und_bewertung: ["rd-02", "rd-04", "rd-12", "rd-14"],
    prozess_und_praesenz: ["rd-03", "rd-07", "rd-10"],
    growth_und_recovery: ["rd-06", "rd-08"],
    team_und_purpose: ["rd-09", "rd-13"],
  },
};
