// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type RequiredClientEnv =
  | "VITE_SUPABASE_URL"
  | "VITE_SUPABASE_PUBLISHABLE_KEY"
  | "VITE_SUPABASE_PROJECT_ID";

function requireClientEnv(key: RequiredClientEnv) {
  const value = import.meta.env[key];
  if (!value) {
    throw new Error(`Missing ${key}. Configure RewirePerform runtime environment before deploying this build.`);
  }
  return value;
}

const SUPABASE_URL = requireClientEnv("VITE_SUPABASE_URL");
const SUPABASE_PUBLISHABLE_KEY = requireClientEnv("VITE_SUPABASE_PUBLISHABLE_KEY");
const SUPABASE_PROJECT_ID = requireClientEnv("VITE_SUPABASE_PROJECT_ID");

if (SUPABASE_URL !== `https://${SUPABASE_PROJECT_ID}.supabase.co`) {
  throw new Error("Supabase URL and project ID do not describe the same runtime target.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
